### ISSUE TITLE
Cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by Bera** [ogham/exa#100]
After downloaded package exa 32 64 bits linux.

Executing on Lububtu 32 bits machine

4.2.0-30-generic #35-Ubuntu SMP Fri Feb 19 13:51:55 UTC 2016 i686 i686 i686 GNU/Linux

**Comment by ogham** [comment]
Sorry, I don't provide a 32-bit version. (`uname -m` will print `x86_64` on a 64-bit machine, and something like `i686` on a 32-bit machine). Although...

**Comment by ogham** [comment]
Try this: [exa_linux_i686.zip](https://github.com/ogham/exa/files/150841/exa_linux_i686.zip)

I compiled it on Ubuntu 14.04.3 x32. Does it work? If so, I'll start providing 32-bit Linux builds along with the others.

**Comment by Bera** [comment]
Worked like a charm!

Thank you guys a lot!

Can I close this issue?



Em seg, 29 de fev de 2016 às 09:14, Benjamin Sago <notifications@github.com>
escreveu:

**Comment by Bera** [comment]
With this file this app worked. Thanks a lot!

**Comment by ogham** [comment]
:+1:
