### ISSUE TITLE
Is it possible to add custom icons to exa?

### ISSUE THREAD

**Issue by CT-66** [ogham/exa#1001]
I don't really like the way the default icons look. Is it possible to change the icons of individual file types/folders? Is it possible to do this through environmental variables. 

Thanks!

**Comment by ariasuni** [comment]
No, it’s not possible currently. See #535 and https://github.com/ogham/exa/issues/665#issuecomment-821897568.

**Comment by CT-66** [comment]
Thanks

**Comment by MollyTheMudWitch** [comment]
Huh.  Seems pretty easy to do, even in Rust... unless you lot have written yourselves into something of a corner.  The interest in icon customization is nearly as old as exa itself now.  The threads you linked just have vague conversations about what a config file might look like, nothing solid, no real decisions.

Is exa still a live project?
