### ISSUE TITLE
On Ubuntu 20.10 (Groovy Gorilla) and later, package link is broken

### ISSUE THREAD

**Issue by Rassska** [ogham/exa#1014]
Hi there!
Would be great to resolve that!

Thanks, Rasul!

**Comment by SOSANA** [comment]
any updates? tried to down with Ubuntu and no success

**Comment by ariasuni** [comment]
@SOSANA What are you talking about? Here we’re talking about the link in the README. What’s your version of Ubuntu and what steps did you follow?

**Comment by SOSANA** [comment]
Please disregard as I am using ubuntu 20.04 and miss read both documentation and title of this issue.

**Comment by manaslupisani** [comment]
via https://the.exa.website/#installation "On Ubuntu 20.10 (Groovy Gorilla) and later, install the [exa](https://packages.ubuntu.com/groovy/exa) package.", where https://packages.ubuntu.com/groovy/exa results in a 404. 

So currently, exa packages in Ubuntu for the last 5 versions: 
[Doesn't exist] https://packages.ubuntu.com/xenial/exa
[Doesn't exist] https://packages.ubuntu.com/bionic/exa
[Doesn't exist] https://packages.ubuntu.com/focal/exa
[Exists!] https://packages.ubuntu.com/impish/exa
[Exists!] https://packages.ubuntu.com/jammy/exa

How about for any unsupported version, either a) instruct how to download and install the .deb or b) point to the guide on installing from src?

**Comment by ariasuni** [comment]
Yeah the website is unmaintained, but the README link will be correct after I merge #1020.

**Comment by ariasuni** [comment]
Closed in favor of https://github.com/ogham/exa/issues/757

exa is unmaintained, use [the active fork eza](https://github.com/eza-community/eza) instead (see https://github.com/ogham/exa/issues/1243).
