### ISSUE TITLE
Icon sizes in different terminals

### ISSUE THREAD

**Issue by vaskark** [ogham/exa#1019]
I'm using exa and have found that icon sizes vary in different terminals, ie. alacritty, as seen here:

[alacritty](https://i.imgur.com/wxhRHwW.png)

Whereas it looks a lot better in kitty:

[kitty](https://i.imgur.com/086WOV9.png)

Most other terminals, like urxvt and st, display icons as kitty does.
Is there anything I can do to make alacritty conform to these icon sizes?
Thanks.

**Comment by ariasuni** [comment]
I can’t see the images, they are probably private. You can drag-and-drop your images on the redaction area of GitHub to upload, or click on the small banner at the bottom of it, just above the buttons.

Regarding your issue, it lies on the terminal-side, exa does not and cannot change the size of the font. You should check alacritty settings, or open a bug report there: https://github.com/alacritty/alacritty/issues.

(please re-open with pictures if I’m wrong somehow)
