### ISSUE TITLE
exa --all seems to trigger --oneline

### ISSUE THREAD

**Issue by ddelange** [ogham/exa#1021]
I replaced my cargo install of exa
```
Replaced package `exa v0.10.1 (https://github.com/ogham/exa.git#dc5c42a0)` with `exa v0.10.1 (https://github.com/ogham/exa.git#42659f93)` (executable `exa`)
```

and running `exa --all` now outputs one file per line, as if it triggers `--oneline`.

I reverted to the old commit using
```
cargo install --git https://github.com/ogham/exa.git --rev dc5c42a0
```

and the behaviour is back to normal

**Comment by j-tai** [comment]
Caused by af208285e8a0fb383f59372c966bdb77f94006e9

**Comment by j-tai** [comment]
Looks like a duplicate of #990

**Comment by ddelange** [comment]
Thanks, let's close this one as a duplicate then 👍
