### ISSUE TITLE
what to get icons to show in iterm2 

### ISSUE THREAD

**Issue by AbhimanyuAryan** [ogham/exa#1029]
<img width="701" alt="Screenshot 2022-02-15 at 9 57 06 PM" src="https://user-images.githubusercontent.com/8083613/154105208-14abdb95-5631-49c7-ac00-d18658901059.png">

using `ProFont for Powerline` `zsh shell` `macbook m1`

<img width="328" alt="Screenshot 2022-02-15 at 9 57 36 PM" src="https://user-images.githubusercontent.com/8083613/154105286-bedf95c1-41e7-4758-b280-1801ca22eb93.png">

**Comment by ariasuni** [comment]
See https://github.com/ogham/exa/issues/568#issuecomment-753356833.
