### ISSUE TITLE
Missing left side of icon on Kitty

### ISSUE THREAD

**Issue by taq** [ogham/exa#1033]
I know it can be a question of the terminal used (Kitty), but would love to have a tip about how to try to fix this.

Seems that when using Kitty, the left side of the icons is missing, not matter what font is used. Here is on Ubuntu regular terminal, with Ubuntu Mono, and its ok (notice a little crop on the first column on the left):

![image](https://user-images.githubusercontent.com/9789/154327734-24a3f4af-6745-4dd1-8dd5-dcce7f11c54d.png)

Here, all icons left side are missing on Kitty:

![image](https://user-images.githubusercontent.com/9789/154328035-1640afe7-ddf5-46a3-ad14-12c161616563.png)

I saw that there were another issue about icons spacing, but not was implemented about that. Is this issue related with the icons spacing/aligment?

**Comment by StewAlexander-com** [comment]
Exa probably is just adding the icons to the left of the standard output of ls

This works in general as the screen size is likely big enough to accommodate the icon, but in this situation Kitty may not be "padding" the left edge of the screen as much as a standard terminal, the result being the icon clipping being seen.

As a used I'd try the grid, long view, or changing the font size without changing the terminal window size to see if one can get it to "fit"

From a development perspective it may require sending the output of the command into something like ncurses that could possibly pad the exa output with a certain number of empty pixels around it, to make sure the full output doesn't get truncated (i.e clipped)

**Comment by lxhom** [comment]
Have you tried using the default settings of Kitty? Seems like it's either a configuration or font issue, works fine on my machine with the default config (you can use `kitty -c /dev/null` to use the default config)
![image](https://user-images.githubusercontent.com/73352734/155245224-3f003c4b-3860-4802-8a36-50b1679b37a2.png)

**Comment by taq** [comment]
Hey @lxhom 

I tried here with `kitty -c /dev/null` but got similar results. :-(

![image](https://user-images.githubusercontent.com/9789/156016865-2652bf3e-74cc-4e4f-9709-7a796f194b1c.png)

**Comment by StewAlexander-com** [comment]
@taq someone suggested [lsd](https://github.com/Peltoche/lsd) as an alternative on another thread 

Might do what you want, check it out

**Comment by taq** [comment]
Thanks, I'll check it out. What a name! 😀

**Comment by ariasuni** [comment]
Hum what. I don’t think using lsd fixed the bug in exa, but I guess it’s ok to let it closed since the problem seems to lie in Kitty anyway (on my side icons are ridiculously small, but perfectly fine in other terminal emulators…).

But anyway did `lsd` really fix your problem?? the outputs of `exa --icons` and `lsd` look identical to me here…

**Comment by taq** [comment]
@ariasuni not really, some icons seems to be "cropped" also.

**Comment by 0ptimista** [comment]
Facing the same issue here. 

Any solutions?

**Comment by Luminous-Coder** [comment]
Same issue.
Every icon has no left side. Not sure, but I think it doesn't due to the padding of window but the width of a character; I don't know how to deal with it however.
