### ISSUE TITLE
Is it possible to tag a new release with support for Julia icons

### ISSUE THREAD

**Issue by AbhimanyuAryan** [ogham/exa#1037]
I am using `exa` with homebrew instead of building from source. This issue: https://github.com/ryanoasis/nerd-fonts/issues/792 suggest, support for `julia` has recently been added.  

However it's quite painful to build from source and do it every time newer updates are available. Instead it's much cleaner, let homebrew manage formulae: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/exa.rb 

So I was wondering if it's possible to tag a new stable release with support for Julia icons which can then be updated in `exa.rb`?

**Comment by AbhimanyuAryan** [comment]
compiled from source I think `exa` has some bug `--grid` doesn't work `exa --grid --color=auto --icons` still shows list

**Comment by ariasuni** [comment]
Nothing is planned.

**Comment by ariasuni** [comment]
To clarify: I’m still working on exa (when I have the time) but the original author isn’t active anymore, and I don’t really have the time to make releases (also I can’t edit the website).
