### ISSUE TITLE
Failure to build version `0.10.1` from crates.io

### ISSUE THREAD

**Issue by Phate6660** [ogham/exa#1040]
If exa fails to compile, or if there is a problem during the build process, then please include the following information in your report:

- The version of rustc you are compiling it with (`rustc 1.61.0-nightly (458262b13 2022-03-09)`)
- Your operating system and hardware platform (Arch Linux -- AMD64)
- The Rust build target:

<details>
<summary>rustc --print cfg</summary>
<pre>
debug_assertions
panic="unwind"
target_abi=""
target_arch="x86_64"
target_endian="little"
target_env="gnu"
target_family="unix"
target_feature="fxsr"
target_feature="llvm14-builtins-abi"
target_feature="sse"
target_feature="sse2"
target_has_atomic="16"
target_has_atomic="32"
target_has_atomic="64"
target_has_atomic="8"
target_has_atomic="ptr"
target_has_atomic_equal_alignment="16"
target_has_atomic_equal_alignment="32"
target_has_atomic_equal_alignment="64"
target_has_atomic_equal_alignment="8"
target_has_atomic_equal_alignment="ptr"
target_has_atomic_load_store="16"
target_has_atomic_load_store="32"
target_has_atomic_load_store="64"
target_has_atomic_load_store="8"
target_has_atomic_load_store="ptr"
target_os="linux"
target_pointer_width="64"
target_thread_local
target_vendor="unknown"
unix
</pre>
</details>

If you are seeing compilation errors, please include the output of the build process.

---

<details>
<summary>cargo install exa</summary>
<pre>
error: failed to compile `exa v0.10.1`, intermediate artifacts can be found at `/tmp/cargo-installVvXrQS`

Caused by:
  could not compile `exa`

Caused by:
  process didn't exit successfully: `rustc --crate-name exa --edition=2018 /home/valley/.cargo/registry/src/github.com-1ecc6299db9ec823/exa-0.10.1/src/main.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type bin --emit=dep-info,link -C opt-level=3 -C lto --cfg 'feature="default"' --cfg 'feature="git"' --cfg 'feature="git2"' -C metadata=0dfbc1d2e39fbe25 -C extra-filename=-0dfbc1d2e39fbe25 --out-dir /tmp/cargo-installVvXrQS/release/deps -L dependency=/tmp/cargo-installVvXrQS/release/deps --extern ansi_term=/tmp/cargo-installVvXrQS/release/deps/libansi_term-74e0a1343b19f5d1.rlib --extern datetime=/tmp/cargo-installVvXrQS/release/deps/libdatetime-9eedfec4233beac5.rlib --extern git2=/tmp/cargo-installVvXrQS/release/deps/libgit2-b422e16d4d32d8ad.rlib --extern glob=/tmp/cargo-installVvXrQS/release/deps/libglob-e196ddfbe6d75e5e.rlib --extern lazy_static=/tmp/cargo-installVvXrQS/release/deps/liblazy_static-5fe00a514209d586.rlib --extern libc=/tmp/cargo-installVvXrQS/release/deps/liblibc-a681e152e740a443.rlib --extern locale=/tmp/cargo-installVvXrQS/release/deps/liblocale-dac877776eb40d3b.rlib --extern log=/tmp/cargo-installVvXrQS/release/deps/liblog-5783da2f1aaef89a.rlib --extern natord=/tmp/cargo-installVvXrQS/release/deps/libnatord-956715d3243a89d3.rlib --extern num_cpus=/tmp/cargo-installVvXrQS/release/deps/libnum_cpus-56ae362eaf6d4375.rlib --extern number_prefix=/tmp/cargo-installVvXrQS/release/deps/libnumber_prefix-8dfaa214cb146ca4.rlib --extern scoped_threadpool=/tmp/cargo-installVvXrQS/release/deps/libscoped_threadpool-be34b58a971d9714.rlib --extern term_grid=/tmp/cargo-installVvXrQS/release/deps/libterm_grid-91166018127eeb1a.rlib --extern term_size=/tmp/cargo-installVvXrQS/release/deps/libterm_size-d3a20a16ee603585.rlib --extern unicode_width=/tmp/cargo-installVvXrQS/release/deps/libunicode_width-03a51620ef32e820.rlib --extern users=/tmp/cargo-installVvXrQS/release/deps/libusers-eeb61e929bb68a75.rlib --extern zoneinfo_compiled=/tmp/cargo-installVvXrQS/release/deps/libzoneinfo_compiled-8752b331edb2690d.rlib --cap-lints allow -L native=/tmp/cargo-installVvXrQS/release/build/libgit2-sys-50b87023ac7bf50f/out/build` (signal: 8, SIGFPE: erroneous arithmetic operation)
</pre>
</details>

**Comment by Phate6660** [comment]
Update: `exa` (version 0.9.0) fails to build.

**Comment by Phate6660** [comment]
Update: compiling on latest master was successful on stable!

**Comment by ariasuni** [comment]
Isn’t this an issue in the Rust nightly build you’re using, then?

**Comment by ariasuni** [comment]
It’s an upstream bug in LLVM, see here for the issue in [the rust-lang repository](https://github.com/rust-lang/rust/issues/94762).

**Comment by hgy59** [comment]
This error pops up again with `stable-x86_64-unknown-linux-gnu unchanged - rustc 1.61.0 (fe5b13d68 2022-05-18)`

Currently there is no open issue in https://github.com/rust-lang/rust/issues related to `SIGFPE`, shall we create one?

It fails in our toolchain to cross compile exa for synology NAS devices (https://github.com/SynoCommunity/spksrc)
Exa builds for i686, x86_x64, aarch64 and PPC fail. Only builds for ARMv7 (32 bit arm) build successfully.

Build Environment:
```
$ rustc --print cfg
debug_assertions
panic="unwind"
target_arch="x86_64"
target_endian="little"
target_env="gnu"
target_family="unix"
target_feature="fxsr"
target_feature="sse"
target_feature="sse2"
target_has_atomic="16"
target_has_atomic="32"
target_has_atomic="64"
target_has_atomic="8"
target_has_atomic="ptr"
target_os="linux"
target_pointer_width="64"
target_vendor="unknown"
unix
``` 


Build log for x86_64:
```
CARGO_HOME=/spksrc/distrib/cargo PATH=:/spksrc/distrib/cargo/bin/:/spksrc/distrib/cargo/bin:/scripts:/usr/local/bin:/usr/bin:/bin:/usr/games PKG_CONFIG_LIBDIR=/spksrc/diyspk/exa/work-x64-6.1/install//var/packages/exa/target/lib/pkgconfig WORK_DIR=/spksrc/diyspk/exa/work-x64-6.1 INSTALL_PREFIX=/var/packages/exa/target TC=syno-x64-6.1  LD="/spksrc/toolchain/syno-x64-6.1/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-ld" LDSHARED="/spksrc/toolchain/syno-x64-6.1/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-gcc -shared" CPP="/spksrc/toolchain/syno-x64-6.1/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-cpp" NM="/spksrc/toolchain/syno-x64-6.1/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-nm" CC="/spksrc/toolchain/syno-x64-6.1/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-gcc" AS="/spksrc/toolchain/syno-x64-6.1/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-as" RANLIB="/spksrc/toolchain/syno-x64-6.1/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-ranlib" CXX="/spksrc/toolchain/syno-x64-6.1/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-g++" AR="/spksrc/toolchain/syno-x64-6.1/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-ar" STRIP="/spksrc/toolchain/syno-x64-6.1/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-strip" OBJDUMP="/spksrc/toolchain/syno-x64-6.1/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-objdump" READELF="/spksrc/toolchain/syno-x64-6.1/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-readelf" CFLAGS="-I/spksrc/toolchain/syno-x64-6.1/work/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/include -I/spksrc/diyspk/exa/work-x64-6.1/install//var/packages/exa/target/include " CPPFLAGS="-I/spksrc/toolchain/syno-x64-6.1/work/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/include -I/spksrc/diyspk/exa/work-x64-6.1/install//var/packages/exa/target/include " CXXFLAGS="-I/spksrc/toolchain/syno-x64-6.1/work/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/include -I/spksrc/diyspk/exa/work-x64-6.1/install//var/packages/exa/target/include " LDFLAGS="-L/spksrc/toolchain/syno-x64-6.1/work/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/lib -L/spksrc/diyspk/exa/work-x64-6.1/install//var/packages/exa/target/lib -Wl,--rpath-link,/spksrc/diyspk/exa/work-x64-6.1/install//var/packages/exa/target/lib -Wl,--rpath,/var/packages/exa/target/lib " CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=/spksrc/toolchain/syno-x64-6.1/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-gcc cargo install --target=x86_64-unknown-linux-gnu --path /spksrc/diyspk/exa/work-x64-6.1/exa-0.10.1 --root /spksrc/diyspk/exa/work-x64-6.1/install/var/packages/exa/target
  Installing exa v0.10.1 (/spksrc/diyspk/exa/work-x64-6.1/exa-0.10.1)
    Updating crates.io index
   Compiling exa v0.10.1 (/spksrc/diyspk/exa/work-x64-6.1/exa-0.10.1)
error: could not compile `exa`

Caused by:
  process didn't exit successfully: `rustc --crate-name exa --edition=2018 src/main.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type bin --emit=dep-info,link -C opt-level=3 -C lto --cfg 'feature="default"' --cfg 'feature="git"' --cfg 'feature="git2"' -C metadata=d99b4db23d0120a9 -C extra-filename=-d99b4db23d0120a9 --out-dir /spksrc/diyspk/exa/work-x64-6.1/exa-0.10.1/target/x86_64-unknown-linux-gnu/release/deps --target x86_64-unknown-linux-gnu -C linker=/spksrc/toolchain/syno-x64-6.1/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-gcc -L dependency=/spksrc/diyspk/exa/work-x64-6.1/exa-0.10.1/target/x86_64-unknown-linux-gnu/release/deps -L dependency=/spksrc/diyspk/exa/work-x64-6.1/exa-0.10.1/target/release/deps --extern ansi_term=/spksrc/diyspk/exa/work-x64-6.1/exa-0.10.1/target/x86_64-unknown-linux-gnu/release/deps/libansi_term-df870e4d9b9e157e.rlib --extern datetime=/spksrc/diyspk/exa/work-x64-6.1/exa-0.10.1/target/x86_64-unknown-linux-gnu/release/deps/libdatetime-84f41c1993bdca61.rlib --extern git2=/spksrc/diyspk/exa/work-x64-6.1/exa-0.10.1/target/x86_64-unknown-linux-gnu/release/deps/libgit2-a3a34fe09416e79c.rlib --extern glob=/spksrc/diyspk/exa/work-x64-6.1/exa-0.10.1/target/x86_64-unknown-linux-gnu/release/deps/libglob-01042dfcc9d951c0.rlib --extern lazy_static=/spksrc/diyspk/exa/work-x64-6.1/exa-0.10.1/target/x86_64-unknown-linux-gnu/release/deps/liblazy_static-014330bac8bfba68.rlib --extern libc=/spksrc/diyspk/exa/work-x64-6.1/exa-0.10.1/target/x86_64-unknown-linux-gnu/release/deps/liblibc-1ec8277da51729b8.rlib --extern locale=/spksrc/diyspk/exa/work-x64-6.1/exa-0.10.1/target/x86_64-unknown-linux-gnu/release/deps/liblocale-bb520fb040060b3e.rlib --extern log=/spksrc/diyspk/exa/work-x64-6.1/exa-0.10.1/target/x86_64-unknown-linux-gnu/release/deps/liblog-2d39266cf4c3e9d4.rlib --extern natord=/spksrc/diyspk/exa/work-x64-6.1/exa-0.10.1/target/x86_64-unknown-linux-gnu/release/deps/libnatord-397f149577a369eb.rlib --extern num_cpus=/spksrc/diyspk/exa/work-x64-6.1/exa-0.10.1/target/x86_64-unknown-linux-gnu/release/deps/libnum_cpus-271b37a05b5da98d.rlib --extern number_prefix=/spksrc/diyspk/exa/work-x64-6.1/exa-0.10.1/target/x86_64-unknown-linux-gnu/release/deps/libnumber_prefix-e58c477461dcfd28.rlib --extern scoped_threadpool=/spksrc/diyspk/exa/work-x64-6.1/exa-0.10.1/target/x86_64-unknown-linux-gnu/release/deps/libscoped_threadpool-efd8a85896ae34f5.rlib --extern term_grid=/spksrc/diyspk/exa/work-x64-6.1/exa-0.10.1/target/x86_64-unknown-linux-gnu/release/deps/libterm_grid-94aff8e341953ab7.rlib --extern term_size=/spksrc/diyspk/exa/work-x64-6.1/exa-0.10.1/target/x86_64-unknown-linux-gnu/release/deps/libterm_size-5c6cb8b2f4b236cf.rlib --extern unicode_width=/spksrc/diyspk/exa/work-x64-6.1/exa-0.10.1/target/x86_64-unknown-linux-gnu/release/deps/libunicode_width-aa6703706b00a397.rlib --extern users=/spksrc/diyspk/exa/work-x64-6.1/exa-0.10.1/target/x86_64-unknown-linux-gnu/release/deps/libusers-17dca92bbb84decf.rlib --extern zoneinfo_compiled=/spksrc/diyspk/exa/work-x64-6.1/exa-0.10.1/target/x86_64-unknown-linux-gnu/release/deps/libzoneinfo_compiled-0fc43351406bc04a.rlib -L native=/spksrc/diyspk/exa/work-x64-6.1/exa-0.10.1/target/x86_64-unknown-linux-gnu/release/build/libgit2-sys-03da96a70734fc5e/out/build -L native=/spksrc/diyspk/exa/work-x64-6.1/exa-0.10.1/target/x86_64-unknown-linux-gnu/release/build/libz-sys-035ebad90e77b091/out/lib -L native=/spksrc/diyspk/exa/work-x64-6.1/exa-0.10.1/target/x86_64-unknown-linux-gnu/release/build/libz-sys-035ebad90e77b091/out/lib` (signal: 8, SIGFPE: erroneous arithmetic operation)
error: failed to compile `exa v0.10.1 (/spksrc/diyspk/exa/work-x64-6.1/exa-0.10.1)`, intermediate artifacts can be found at `/spksrc/diyspk/exa/work-x64-6.1/exa-0.10.1/target`
make[3]: *** [../../mk/spksrc.cross-rust.mk:120: rust_build_and_install_target] Error 101
```

**Comment by hgy59** [comment]
> This error pops up again with `stable-x86_64-unknown-linux-gnu unchanged - rustc 1.61.0 (fe5b13d68 2022-05-18)`
> 

exa successfully builds with rustc 1.60.0

**Comment by bogdanbpeterson** [comment]
I'm on `rustc 1.61.0 (fe5b13d68 2022-05-18)`. Same build error.

Output of `rustc --print cfg`:
`debug_assertions
panic="unwind"
target_arch="x86_64"
target_endian="little"
target_env="gnu"
target_family="unix"
target_feature="fxsr"
target_feature="sse"
target_feature="sse2"
target_has_atomic="16"
target_has_atomic="32"
target_has_atomic="64"
target_has_atomic="8"
target_has_atomic="ptr"
target_os="linux"
target_pointer_width="64"
target_vendor="unknown"
unix`

**Comment by bogdanbpeterson** [comment]
Confirm: @hgy59 exa successfully builds with `rustc 1.60.0 (7737e0b5c 2022-04-04)`
