### ISSUE TITLE
use better folder icon

### ISSUE THREAD

**Issue by siduck** [ogham/exa#1041]
the current folder icon looks bad imo, kinda outdated too. Ive seen usage of folder icons in many cli apps such as ranger,lf,logo-ls, nvim plugins etc and they mostly use  ⠀ 

exa and logo-ls

![image](https://user-images.githubusercontent.com/59060246/158089701-db1f9f37-80ff-456d-b206-b1658d7d65c9.png)

would it be possible to use this icon? 
![image](https://user-images.githubusercontent.com/59060246/158089788-7648eae2-335f-4d9c-98b1-6e2fe131f053.png) or
![image](https://user-images.githubusercontent.com/59060246/158090035-a41e6ff0-b2ae-472c-a3e5-cdc8f7858583.png)

**Comment by CT-66** [comment]
I agree, the current folder icon doesn't look pleasing. If the default icon isn't changed, it would be nice to have customizable icons like in the lf file manager.

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/158279649-7e88df0b-ee01-4956-957b-9a9e286a9752.png)

**Comment by ariasuni** [comment]
I’m not really sure which one to use between the two, I guess the second one is slightly more legible and distinctive than the second, so I think it’s a good idea.

**Comment by roland-rollo** [comment]
Second looks better.

**Comment by ariasuni** [comment]
Let’s go for the first then!

**Comment by siduck** [comment]
yay

**Comment by rickypang0219** [comment]
I love you idea on changing the folder icon. Could you provide the code on changing the folder icon? I am trying to write a config file for exa but I have no clue on it.

**Comment by siduck** [comment]
@rickypang0219  i used @CT-66 's branch for it but now i no longer use exa.  you can probably try eza and tell its devs to add this feature or just use logo-ls
