### ISSUE TITLE
Environment variable to specify default options?

### ISSUE THREAD

**Issue by johann-petrak** [ogham/exa#1043]
Am I missing something or is there no way to configure things so that some options will ALWAYS be used with exa, e.g. --git or --icons ?
If not, could we have an option `EXA_OPTS` or similar to set to those options?

**Comment by ariasuni** [comment]
This feature has already been requested in the past and won’t be implemented, just use aliases in your shell.

**Comment by eggbean** [comment]
I made [this wrapper script](https://gist.github.com/eggbean/74db77c4f6404dd1f975bd6f048b86f8) so that it shows git status automatically when in a git directory (as well as change the switches to match `ls`). You could make something similar which does what you want.

**Comment by ariasuni** [comment]
A `--git=auto` would be a cool feature, now that I think of it. I created a ticket for that: #1044.
