### ISSUE TITLE
--git-ignore option not working on macos

### ISSUE THREAD

**Issue by js1972** [ogham/exa#1048]
I am using `exa` as my `ls` replacement and love it except for some reason it will not ignore my files in a projects .gitignore file.

If I am in my project root dir which has a .gitignore which includes this:
```
node_modules/
```

Then run:
```
exa --tree --git-ignore
```

It prints all the contents of my `node_modules` folder.

- The version of exa being used (`exa --version`): `v0.10.1 [+git]`
- The command-line arguments you are using: `exa --tree --git-ignore`
- Your operating system and hardware platform: `Macos 12.2.1 (2.3 GHz 8-Core Intel Core i9)`

**Comment by ariasuni** [comment]
Did you have an alias for `exa`? Is the folder a Git repository? Does it only happen with `--tree`?

No code path related to Git is specific to macOS, and is works well here, so I don’t see what could go wrong here.

**Comment by js1972** [comment]
Hi @ariasuni - I am stupid! Thanks for your assistance. I was creating new applications to test this that had .gitignore files but I had not done a `git init` Agh.
