### ISSUE TITLE
Broken icons with kitty/cascadia

### ISSUE THREAD

**Issue by ebenoist** [ogham/exa#1054]
If exa does something unexpected, or its output looks wrong, or it displays an error on the screen, or if it outright crashes, then please include the following information in your report:

- The version of exa being used (`exa --version`)
- The command-line arguments you are using
- Your operating system and hardware platform

If it’s a crash, please include the full text of the crash that gets printed to the screen. If you’re seeing unexpected behaviour, a screenshot of the issue will help a lot.

---

I'm using the kitty terminal emulator, the `cascadia code pf` font, and exa, but I'm getting only broken icons when passing `--icons`.

```
[~/Notes]❥ exa --version
exa - list files on the command-line
v0.10.1 [+git]
https://the.exa.website/
```

<img width="885" alt="image" src="https://user-images.githubusercontent.com/1656713/162523326-84a61c48-5388-4531-af2d-31bbe2b6daf9.png">

What am I doing wrong?

**Comment by ariasuni** [comment]
Yeah you need a [Nerd font](https://www.nerdfonts.com/) to have icons (I know it’s not well documented right now).

**Comment by ebenoist** [comment]
Thanks!
