### ISSUE TITLE
exa doesn't think it's writing to a terminal when calling it from SSH session

### ISSUE THREAD

**Issue by abehr** [ogham/exa#1060]
I'm not 100% sure if that's the correct assessment of what's going on, but:

- exa v0.10.1
- CentOS 7.9 (accessed via OpenSSH 8)

By default, if outputting to terminal, `exa` outputs as grid, and `exa -l` outputs with color. However, in this current context (SSH - although it could be for another reason I'm not considering), exa behaves as if it's not (see attached screenshot):

- `exa` forces `--oneline` even though COLUMNS is nonzero. Forcing `env COLUMNS=80` prints grid.
- `exa -l` prints without color. Forcing `--color always` prints color.

<img width="408" alt="Screen Shot 2022-04-26 at 01 53 30" src="https://user-images.githubusercontent.com/6844407/165262829-bf5efdd7-5418-4286-a77f-6fddd2336f32.png">

**Comment by abehr** [comment]
Update: This happens only when SSH connected under certain conditions and may have to do with the COLUMNS/LINES (or other) env vars not being dynamically linked to terminal window size through SSH. It's not specifically exa's fault.

**Comment by ariasuni** [comment]
Well I’d say, does this happen also with `ls --color=auto`? If yes that’s probably what you’re saying, but if no there may be something we can do on exa’s side.
