### ISSUE TITLE
Icons not shown entirely in vscode integrated terminal

### ISSUE THREAD

**Issue by danielfalbo** [ogham/exa#1066]
Icons are not being shown entirely in vscode's integrated terminal. Not sure if this is an exa bug or a vscode bug.

Version: `v0.10.1 [+git]`
System: macOS Monterey 12.3.1 on 2020 M1 Macbook Air
<img width="463" alt="screenshot" src="https://user-images.githubusercontent.com/39460524/168337114-5c922772-0d6f-4560-834d-622886e56686.png">

Can you recreate?

**Comment by ariasuni** [comment]
Can’t reproduce here because icons don’t show up in VSCode terminal.

Have you tried `EXA_ICON_SPACING=2 exa --icons -1`? see https://github.com/ogham/exa/blob/master/man/exa.1.md#exa_icon_spacing=

**Comment by danielfalbo** [comment]
To make icons show up in VSCode's terminal, try to use your favourite font with icons as first `editor.fontFamily` font in VSCode's settings file.
<img width="825" alt="Screenshot 2022-05-18 at 09 15 12" src="https://user-images.githubusercontent.com/39460524/168980352-8ee6b732-b180-46d9-a834-8c4c89eb050a.png">

I'm using Victor Mono by the way.

I also tried to play a bit with `EXA_ICON_SPACING` but looks like it doesn't have to do with this issue.

<img width="377" alt="Screenshot 2022-05-18 at 09 20 25" src="https://user-images.githubusercontent.com/39460524/168981338-9870bbb9-9c6d-4f0b-8c57-795fa0740c7e.png">

[Here](https://github.com/danielfalbo/dotfiles/blob/main/settings.json) is my complete vscode configuration, though I guess it's not needed to recreate.

Thank you, Mélanie.

**Comment by danielfalbo** [comment]
I have the same issue with `lsd`, so I guess it's a VSCode issue, not an `exa` issue. Closing this. Thank you `:)`

**Comment by danielfalbo** [comment]
https://github.com/microsoft/vscode/issues/148857
