### ISSUE TITLE
Can exa be installed on CentOS?  Specifically CentOS 7.7?  If so, how?

### ISSUE THREAD

**Issue by cpoptic** [ogham/exa#1067]

**Comment by ariasuni** [comment]
https://github.com/ogham/exa#manual-installation-from-github= or https://github.com/ogham/exa#cargo should work like any other Linux distribution. Feel free to re-open this issue if for some reason it doesn’t work.

**Comment by eggbean** [comment]
It's just a single file executable which you can put in your `/usr/local/bin`.

**Comment by kvnmlm** [comment]
`$ exa
exa: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by exa)`

And Centos 7 is GLIBC_2.17 :-(

**Comment by ariasuni** [comment]
Then you should install exa through cargo, wich will build exa from source and use your current glibc.

**Comment by kvnmlm** [comment]
Appreciate the suggestion, won't build, craps out indicating: (signal: 8, SIGFPE: erroneous arithmetic operation)   which points me towards updating cargo/rustc  which apparently is nice with rustup but rustup won't play nice cause rustc/cargo are already here and........ this problem: https://github.com/ogham/exa/issues/1068

**Comment by kvnmlm** [comment]
OK, much thanks @ariasuni ,  I yum removed rustc/cargo, installed rustup, getting latest rustc/cargo.  cargo install exa which forced it to rebuild and install.  Fixed some path problems and exa is happily installed on Centos 7.  Picked up some rust knowledge along the way :-)
