### ISSUE TITLE
fzf Compatible

### ISSUE THREAD

**Issue by niksingh710** [ogham/exa#1072]
piping the output to fzf gives color characters

**Comment by ariasuni** [comment]
What command are you using to pipe in `fzf`? Does other programs manage to do that where exa fails? If yes, can do describe what you want to achieve with more details (you can include a screenshot if that’s easier)?

**Comment by eggbean** [comment]
@niksingh710 Maybe you are using an alias or function that adds `--colour=always`? By default it's `auto` and won't colourise on stdout.

**Comment by niksingh710** [comment]
> What command are you using to pipe in `fzf`? Does other programs manage to do that where exa fails? If yes, can do describe what you want to achieve with more details (you can include a screenshot if that’s easier)?

@ariasuni Sorry for giving less information.

here is the set of aliases I am using with exa.
```
if hash exa 2>/dev/null;then    
  alias l='exa -lahF --color=always --icons --sort=size --group-directories-first'
  alias lss='exa -hF --color=always --icons --sort=size --group-directories-first'
  alias la='exa -ahF --color=always --icons --sort=size --group-directories-first'
  alias ls='exa -lhF --color=always --icons --sort=size --group-directories-first'
  alias lst='exa -lahFT --color=always --icons --sort=size --group-directories-first'
  alias lt='exa -aT --icons --group-directories-first --color=always --sort=size'
fi 
```

There is a program `batcat` that is not exactly equivalent to `exa` but gives a colored output of cat command but removes all decoration when piping to another command.




> @niksingh710 Maybe you are using an alias or function that adds `--colour=always`? By default, it's `auto` and won't colorize on stdout.

@eggbean 
Yes Mate, I am using `--color=always` is there some other value that can remove color while piping to another command.

**Comment by niksingh710** [comment]
![image](https://user-images.githubusercontent.com/60490474/170412328-7247f3f6-aaa5-4195-8412-06f81ac848b8.png)
![image](https://user-images.githubusercontent.com/60490474/170412368-31f8cb3c-57e2-4034-bd48-4f523a721f7f.png)

**Comment by ariasuni** [comment]
Just remove `--color=always`, or use `--color=auto` (which is exa’s default: color when printing to terminal, no color when piping).

**Comment by thealio** [comment]
Hi
@ariasuni 

I'd like to reopen the issue

In this script, fzf is successfully used with colors enabled

 https://github.com/sc0ttj/fzf-filemanager

But, I don't get how it was done . Maybe you can explain this , I really don't understand what options the author has used to make fzf compatible with exa colors.

I hope someone can explain it

**Comment by niksingh710** [comment]
> Hi @ariasuni
> 
> I'd like to reopen the issue
> 
> In this script, fzf is successfully used with colors enabled
> 
> [sc0ttj/fzf-filemanager](https://github.com/sc0ttj/fzf-filemanager)
> 
> But, I don't get how it was done . Maybe you can explain this , I really don't understand what options the author has used to make fzf compatible with exa colors.
> 
> I hope someone can explain it
For exa these are the options i use to be exact.
`exa -ahFT -L=1 --color=auto --icons --sort=size --group-directories-first `

and for previewing in fzf i have my own custom [script](https://github.com/niksingh710/cli/blob/master/bin/bin/preview)
as in example command `fzf --preview='preview --ueberzugpp {$1}; preview --cleanup'`
