### ISSUE TITLE
Add Kotlin, Julia, F# and Assembly icons

### ISSUE THREAD

**Issue by ignamartinoli** [ogham/exa#1080]

**Comment by ignamartinoli** [comment]
I just check the [lsd](https://github.com/Peltoche/lsd/blob/master/src/icon.rs) code you pointed me to. For some reason my terminal (`kitty`) renders the icon when I copy and paste it but if I run the program the icons looks like a generic file.

![screenshot_20220707183730](https://user-images.githubusercontent.com/103866722/177875585-58e6e13a-1b63-4ce6-ae5c-60a22eef967c.png)

I'm really sorry if you thought I was trying to waste your time, but it wasn't my intention, I mean it.

As you can see I'm using the latest version. Do you know if those icons looking like that is an intended behavior?

**Comment by Finii** [comment]
Ok, so I'm diving into this piece of software, not that I know anything about `exa`...

**Latest release is (Apr 12, 2021)**

![image](https://user-images.githubusercontent.com/16012374/177933849-fe488fa6-5e38-4720-8314-7c8efa44d7a3.png)

**And the addition if f-sharp came about (Apr 26, 2021)**

![image](https://user-images.githubusercontent.com/16012374/177934053-4bdf1501-0e03-47f9-ab06-69098f9a3996.png)

Maybe you should request a new release or just build on your own from `head` :-)

**Comment by ignamartinoli** [comment]
Alright, so the change just wasn't released yet.
I didn't thought that about the possibility of un-versioned changes.
I guess I'll wait for a new release.
Thanks for helping me :-)
