### ISSUE TITLE
Flag to take down the number of lines reported

### ISSUE THREAD

**Issue by ksandvik** [ogham/exa#1087]
If I use exa -l -g --icons -r --sort=modified -l | sed 5q then the color syntax is removed by sed (MacOSX BSD sed). 

It would be nice to have an option to define max number entries, as in the example below in a very busy directory I would like to just see the five last modified files.

**Comment by eggbean** [comment]
It's not removed by sed. The colour codes are stripped from exa STDOUT when piping to another program unless you add `--color=always`. Lots of other programs do the same, like grep.

**Comment by ksandvik** [comment]
Oh, verified, yes that works fine.

**Comment by ariasuni** [comment]
Closing this, since I believe that it’s not a common use case and that it can be done by combining commands just fine.
