### ISSUE TITLE
MSYS2 package

### ISSUE THREAD

**Issue by yashpalgoyal1304** [ogham/exa#1090]
The release notes for [exa v0.10.0](https://github.com/ogham/exa/releases/tag/v0.10.0) says that 
> This version _should_ be the last version without Windows support.

How 'bout providing an msys package meanwhile? So that people running msys2 can still enjoy exa?

**Comment by yashpalgoyal1304** [comment]
the instructions are documented at : https://www.msys2.org/wiki/Creating-Packages/

**Comment by Freed-Wu** [comment]
Hey, it waits <https://github.com/ogham/exa/issues/32>.

**Comment by AceofSpades5757** [comment]
I've been running one of those versions for a while, and it looks like other people have too, without any serious issues.

**Comment by FrostKiwi** [comment]
> I've been running one of those versions for a while, and it looks like other people have too, without any serious issues.

Running flawless on my setup. Using exa on all my *nix machines and it translates pretty well to windows as well:
![image](https://user-images.githubusercontent.com/60887273/213969955-c4a8086e-5b04-4fcf-8bdf-60c724b83cf6.png)

**Comment by yashpalgoyal1304** [comment]
hmm, guess i'll have to add another tak in my todo list. I hope to be able to tackle _some_ programming task in the FOSS this coming week. can't say which one it will be.
