### ISSUE TITLE
Add more icons?

### ISSUE THREAD

**Issue by Freed-Wu** [ogham/exa#1096]
How about add icons like <https://github.com/lambdalisue/nerdfont.vim/issues/12>? I think someone maybe wants it.

And can the icon for trash be used for <https://github.com/ogham/exa/blob/master/src/output/icons.rs#L51>:

![Screenshot from 2022-07-31 15-37-02](https://user-images.githubusercontent.com/32936898/182015303-c9fef979-6cc0-47bd-b068-4ce2ee4890d6.png)
?

![Screenshot from 2022-07-31 15-39-29](https://user-images.githubusercontent.com/32936898/182015384-c12c68d0-0d88-4124-a88f-af7c57a71a1e.png)

And why `*.a` don't have the same icon as `*.so`?

![Screenshot from 2022-07-31 16-07-34](https://user-images.githubusercontent.com/32936898/182016246-2db387ae-61e3-4271-b707-19448c2cc6f2.png)

**Comment by ariasuni** [comment]
Closing this, since exa is unmaintained (see https://github.com/ogham/exa/issues/1243), and this has been done in [the active fork eza](https://github.com/eza-community/eza). Thanks anyway!
