### ISSUE TITLE
Any interest about migration to `clap`

### ISSUE THREAD

**Issue by Zaplae** [ogham/exa#1111]
`clap-rs` is a powerful crate.

- very fast
- easy to maintain, quickly iterate the project
- automatically generate completion for almost shell, according to code written
- more power, more features

**Comment by toymil** [comment]
FYI: https://github.com/eza-community/eza/pull/197

**Comment by ariasuni** [comment]
exa is unmaintained (see https://github.com/ogham/exa/issues/1243), please see the mentioned issue above in [the active fork eza](https://github.com/eza-community/eza).
