### ISSUE TITLE
Exa panics if it encounters a file that was created in the future

### ISSUE THREAD

**Issue by Sciencentistguy** [ogham/exa#1113]
Due to time zones, I have managed to get a file on my server which it believes was created in the future. `exa -l` panics when run in that directory:

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: SystemTimeError(2147483648s)', src/fs/file.rs:331:70
stack backtrace:
   0:     0x55c0b42c4777 - <unknown>
   1:     0x55c0b424e4ef - <unknown>
   2:     0x55c0b42be641 - <unknown>
   3:     0x55c0b42da35c - <unknown>
   4:     0x55c0b42c4afa - <unknown>
   5:     0x55c0b42c4ac4 - <unknown>
   6:     0x55c0b42d9c1d - <unknown>
   7:     0x55c0b4250760 - <unknown>
   8:     0x55c0b424b6d2 - <unknown>
   9:     0x55c0b4278ed9 - <unknown>
  10:     0x55c0b427d08d - <unknown>
  11:     0x55c0b42615ac - <unknown>
  12:     0x55c0b42b5088 - <unknown>
  13:     0x55c0b42b5c2d - <unknown>
  14:     0x55c0b42da425 - <unknown>
  15:     0x7f17ea803ea7 - start_thread
  16:     0x7f17eaa5edef - clone
  17:                0x0 - <unknown>
Aborted
```

This server is debian 11 on google cloud; exa version 0.9.0

I would attempt to build a debug build of exa on said server, to get a better stacktrace, however the server has 1 core and 0.5GiB of ram, so that is unfortunately not feasible.

**Comment by owlseye** [comment]
exa 0.9.0 was released in July 2019 - _three years_ ago. Try using a more recent version. 
If no vaild creation time could be obtained by the OS, you will see `-` as a placeholder:https://github.com/ogham/exa/blob/e385cd58da9d2e86425250b108e87e4a69904f5c/src/output/render/times.rs#L25

**Comment by eggbean** [comment]
Time zones are just a number of hours subtracted or added to the UTC time I thought, ai I curious about how that happened.

**Comment by Sciencentistguy** [comment]
Ah, I completely forgot that debian ships outdated-as-hell packages, and hadn't considered that that exa may have been an ancient version.
