### ISSUE TITLE
This parameter does not have

### ISSUE THREAD

**Issue by lijinghuatongxue** [ogham/exa#1114]
<img width="624" alt="图片" src="https://user-images.githubusercontent.com/17118790/188280567-e8d53078-7ba8-4c06-91ab-e7bb14da8528.png">

**Comment by eggbean** [comment]
You need to add an additional argument to show which sort type you want.
eg.

    $ exa -lt modified
    $ exa -lt changed
    $ exa -lt accessed
    $ exa -lt created

**Comment by ariasuni** [comment]
Already reported, see https://github.com/ogham/exa/issues/519.
