### ISSUE TITLE
[Fr] Option to store arguments in environment and/or dot file

### ISSUE THREAD

**Issue by andrewcrook** [ogham/exa#1116]
My alias and command lines for exa become quite long.
I wonder if it could be possible to add arguments into an environment variable.

example 
`>> EXA_OPTS=“--header --long --grid"`

Another option would be to use a dot file 

example `~/.config/exa/config.yml`
```
header: yes
details: long
mode: grid   # tree, grid etc
classify: no
icons: yes
```

**Comment by eggbean** [comment]
You could make a wrapper script like the one I made, or modify it, to do what you want. https://gist.github.com/eggbean/74db77c4f6404dd1f975bd6f048b86f8

**Comment by andrewcrook** [comment]
> You could make a wrapper script like the one I made, or modify it, to do what you want. https://gist.github.com/eggbean/74db77c4f6404dd1f975bd6f048b86f8

@eggbean  Thanks I will take a look.

**Comment by jnordwick** [comment]
what prevents you  from alisasing `exa='exa $EXA_OPTS`'`?
