### ISSUE TITLE
Sort by type

### ISSUE THREAD

**Issue by Lindenk** [ogham/exa#113]
I propose a new sorting parameter: sort by `type`.

This would first sort in the following order based on file type:
- Directory
- File
- Symlink
- Named Pipe
- Socket
- Device

So, for the given output for `exa -l` (rather `ls -l` because of #112):

```
brw-r--r-- 0 root    13 Jun 21:26 a_device
drwxr-xr-x - lindenk 13 Jun 21:33 a_directory
.rw-r--r-- 0 lindenk 13 Jun 21:23 a_file
prw-r--r-- 0 lindenk 13 Jun 21:21 a_named_fifo
srwxr-xr-x 0 lindenk 13 Jun 21:32 a_socket
lrwxrwxrwx 6 lindenk 13 Jun 21:23 a_symlink -> a_file
```

The command `exa -ls type` should produce:

```
drwxr-xr-x - lindenk 13 Jun 21:33 a_directory
.rw-r--r-- 0 lindenk 13 Jun 21:23 a_file
lrwxrwxrwx 6 lindenk 13 Jun 21:23 a_symlink -> a_file
prw-r--r-- 0 lindenk 13 Jun 21:21 a_named_fifo
srwxr-xr-x 0 lindenk 13 Jun 21:32 a_socket
brw-r--r-- 0 root    13 Jun 21:26 a_device
```

**Comment by ogham** [comment]
Yeah, this should be there too.

**Comment by ogham** [comment]
I have a version of this working in a branch:

![screen shot 2017-06-29 at 14 58 45](https://user-images.githubusercontent.com/503760/27691292-7ec984a8-5cdb-11e7-8993-4eb13b094929.png)
