### ISSUE TITLE
List directory contents with permissions r--

### ISSUE THREAD

**Issue by victor-timofei** [ogham/exa#1130]
If a directory has the permissions `r--` for a user, the user should be able to list the names of the contents in that directory even if it cannot get any extra information on those names.

This is possible with GNU ls but not with exa.

Steps to reproduce:
```sh
$ mkdir test
$ touch test/a
$ touch test/b
$ chmod -wx test
$ exa test
[test/b: Permission denied (os error 13)]
[test/a: Permission denied (os error 13)]
$ ls test
a b
```

**Comment by SteveLauC** [comment]
exa tries to read the metadata of a and b, this requires the x permission on its parent directory
