### ISSUE TITLE
exa ignores files beginning with underscore (_)

### ISSUE THREAD

**Issue by garyo** [ogham/exa#1131]
I have exa v0.10.1 for Windows, without git. 
`exa -T` seems to ignore all filenames beginning with underscore, unless I add `-a`.
Same result when run from cmd.exe or an msys shell.

Underscore files are not typically "hidden" so I'm not sure what's going on. Feature or bug?

**Comment by eggbean** [comment]
Dotfiles for vim which are called `.vimrc`, `.gvimrc` and `.viminfo` on Linux are called `_vimrc` `_gvimrc` and `_viminfo` on Windows. I suppose other programs may do this as well, but even if they didn't vim is so popular it could have been just for that. I think it was deliberate.

**Comment by garyo** [comment]
I believe I'm running the build from https://github.com/ogham/exa/pull/820#issuecomment-1098277761

As for ignoring '_' files, that's too bad. I use exa as my ls replacement, and it mystified me where my python `__init__.py` files had gone to! Maybe it could just ignore files starting with only one `_`?

**Comment by garyo** [comment]
I'll close this now -- I've added a comment to the place in #820 where it ignores '_' files. Sorry for the noise.
