### ISSUE TITLE
IMPORTANT: Update exa version

### ISSUE THREAD

**Issue by YogiOnBioinformatics** [ogham/exa#1135]
It would be really useful to create new versions since lots of changes have taken place since the last published version. 

Most importantly, users could then download a binary of the latest changes.

**Comment by jstetten** [comment]
See #1139 for explanation from the current maintainer. The project is in need of contributors.

**Comment by adamency** [comment]
Actually, @ariasuni has merged the big PR adding (initial) windows support, with great joy from the people ! I think it's due time to make a new release :) as a priority (anytime you want to, no worries).

And thanks so much for your work !

**Comment by YogiOnBioinformatics** [comment]
@jstetten Sorry I missed your reply. Thanks for the link -- it helps me understand what happened. 

@adamency Great to know!

**Comment by ariasuni** [comment]
Closing this, since #1139 is already pinned.
