### ISSUE TITLE
Use json to store icons information for different extension/filename/pattern

### ISSUE THREAD

**Issue by Freed-Wu** [ogham/exa#1138]
1. It is easier to edit even for those contributors is not familiar with rust
2. It is easier to compare the difference between this project's icon and other projects which provide icon display, so we can add icons more easily.
3. It is easier to sort json by `jq`

Just my 2c, TIA!

**Comment by Freed-Wu** [comment]
Just like <https://github.com/lambdalisue/nerdfont.vim/blob/master/assets/json/extension.json>

**Comment by jceaser** [comment]
would this change allow for different fonts to be supported, like Fira Code?

**Comment by jnordwick** [comment]
why json and not line delimited?

**Comment by Freed-Wu** [comment]
> why json and not line delimited?

It is also OK. I just think perhaps parse json is easier (with library).

**Comment by Freed-Wu** [comment]
<https://github.com/eza-community/eza/issues/440>
