### ISSUE TITLE
Adding Emacs Dired Support

### ISSUE THREAD

**Issue by gopar** [ogham/exa#1143]
Emacs has a built in tool for viewing files/directories called [Dired](https://www.gnu.org/software/emacs/manual/html_node/emacs/Dired.html) and [GNU Coreutils](https://www.gnu.org/software/coreutils/) has the `--dired` option within `ls` to complement that.

Man page states:
```
-D, --dired
              generate output designed for Emacs' dired mode
```

And from [their comments in source file](https://github.com/coreutils/coreutils/blob/master/src/ls.c#L532) it seems like this option formats the output differently for easier parsing in emacs.

Would be nice to have this baked in into exa as well. 

Github mirror: https://github.com/coreutils/coreutils
ls file: https://github.com/coreutils/coreutils/blob/master/src/ls.c

**Comment by anoduck** [comment]
This added feature would be incredible.

**Comment by ariasuni** [comment]
exa is unmaintained (see https://github.com/ogham/exa/issues/1243), please open an issue for the [the active fork eza](https://github.com/eza-community/eza).

**Comment by anoduck** [comment]
Yeah, I know. Someone should suggest this for the [eza](https://github.com/eza-community/eza) repo.
