### ISSUE TITLE
Please, make "--octal-permissions" shortcut to "-o"

### ISSUE THREAD

**Issue by nerun** [ogham/exa#1157]
Running exa `v0.10.1 [-git]`

Currently `-o` defaults to nothing:
```shell
$ exa -o
exa: Unknown argument -o
```
Would be good if the option `-o` was linked to `--octal-permissions`.

Also, option `--group-directories-first` has no shortcut. Both options `-G` and `-g` defaults to `--grid`. You could let `-G` for `--grid` but change `-g` to `--group-directories-first`. Because in `exa --help`, most FILTERING AND SORTING OPTIONS uses small caps while "big" caps are used in DISPLAY OPTIONS.

**Comment by eggbean** [comment]
I added `-o` for octal permissions to my wrapper script, as that letter wasn't doing anything anyway.

https://gist.github.com/eggbean/74db77c4f6404dd1f975bd6f048b86f8

**Comment by ariasuni** [comment]
Closing this since exa is unmaintained (see https://github.com/ogham/exa/issues/1243), and this has been done in [the active fork eza](https://github.com/eza-community/eza). Thanks!
