### ISSUE TITLE
Add `-h` switch to reverse `-B` switch

### ISSUE THREAD

**Issue by martin-braun** [ogham/exa#1158]
The default `ls -l` will always show sizes in bytes (i.e. like `exa -Bl`), so my alias is `ls="exa --bytes`.

When I then decide to show the file sizes in human readable form using `ls -hl` I will toggle the header instead. 

It would've been nice to preserve the `-h` flag. This is pure muscle memory here. `exa` is not installed everywhere.

Thoughts?

**Comment by eggbean** [comment]
I had that problem with the `-A` switch, as I always type `ls -lA`, so I wrote this wrapper script to have most of the same switches as ls. Just alias to it and you'll be able to use exa like ls.

https://gist.github.com/eggbean/74db77c4f6404dd1f975bd6f048b86f8

**Comment by martin-braun** [comment]
@eggbean Very nice contribution, thank you. :)
