### ISSUE TITLE
Respect $LS_COLORS

### ISSUE THREAD

**Issue by simnalamburt** [ogham/exa#116]
With current implementation, we cannot customize directory color scheme of `exa`. Let's parse `$LS_COLORS` environment variable (or `$LSCOLORS` on BSD) and use it in the output.
###### Reference
- http://geoff.greer.fm/lscolors/

**Comment by nate0001** [comment]
Yes, please. I've been tempted to write my own LS replacement because no one uses LS_COLORS.

**Comment by rpdelaney** [comment]
+1

**Comment by therockmandolinist** [comment]
Is there anything new on this or are there plans for this?

**Comment by SuperCuber** [comment]
+1

**Comment by zyguy** [comment]
+1

**Comment by ogham** [comment]
I still want to get this one done this release cycle, don’t worry!
