### ISSUE TITLE
Option --tree (-T) should not conflict with --list-dirs (-d)

### ISSUE THREAD

**Issue by docwhat** [ogham/exa#1176]
When using `exa -dT` it acts the same as running `exa -T`.

This seems to be because it is ignoring the `-d` flag.

If I run in strict mode I get:

```sh
$ env EXA_STRICT=1 exa -dT
exa: Option --tree (-T) conflicts with option --list-dirs (-d)
```

I expected this to work the same a `tree` does and just show the directories but not the files.

```sh
# example of tree
$ tree -d
.
├── apache2
│   ├── extra
│   ├── original
│   │   └── extra
│   ├── other
│   └── users
├── defaults
├── manpaths.d
├── pam.d
├── paths.d
├── periodic
│   ├── daily
│   ├── monthly
│   └── weekly
├── ssh
│   ├── ssh_config.d
│   └── sshd_config.d
├── ssl
│   └── certs
├── sudoers.d
├── uucp
└── wfs

11 directories
```

Note how it only counts the directories at the top.

- version: `v0.10.1 [+git]`
- Commands:
    - `exa -dT`
    - `env EXA_STRICT=1 exa -dT`
- macOS: 13.3 (22E252)
- Mac Book Pro (M1 Max) 14-inch, 2021
- Confirmed it is the same on Ubuntu 22.04 with version `v0.10.1 [+git]`

**Comment by eggbean** [comment]
The `-d` switch is for it to not show the directory contents when globbing. like in `ls`, so it doesn't make much sense for it to be shown in tree mode? I think the `-D` switch might be what you want.

**Comment by eggbean** [comment]
The `-d` switch is for it to not show the directory contents when globbing. like in `ls`.

e.g. If you want to show all the hidden files in your home directory, the first options would also give you everything inside the hidden directories. With the `-d` switch they don't.

    $ ls -l .*
    $ exa -l .*
    
    $ ls -ld .*
    $ exa -ld .*


So, it doesn't make much sense for it to be shown in tree mode, as the contents of directories aren't being shown.

The `-D` switch is what you want.

**Comment by docwhat** [comment]
I missed the `-D`/`--only-dirs` flag in the manpage.

That is exactly what I wanted.
