### ISSUE TITLE
Question marks instead of Icons

### ISSUE THREAD

**Issue by faxotherapy** [ogham/exa#1179]
When listing files with icons, question marks as icons are showed:
<img width="64" alt="exa-icon-issue" src="https://user-images.githubusercontent.com/6538008/232291663-4ec762b8-4006-4f72-b98d-23ceb6078340.png">

- v0.10.1
- `exa -1a --icons`
- macOS, iTerm, tmux

**Comment by faxotherapy** [comment]
OK, I was using Fantasque Sans Mono font.

**Comment by eggbean** [comment]
If you still want to use that font you can use the patched nerd font version of it:

https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/FantasqueSansMono

You need to use fonts patched as nerd fonts for the glyphs that are used by exa and other command line programs.

https://www.nerdfonts.com/

**Comment by faxotherapy** [comment]
Thanks a lot!
