### ISSUE TITLE
exa crushes in exa -lhg command

### ISSUE THREAD

**Issue by kibernaut** [ogham/exa#1181]
When I run `exa -lhg` (exa v0.9.0) on a specific directory which contains a dir with last_modified attr (01.01.1970) it was "panicked":

> thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: SystemTimeError(10800s)', src/fs/file.rs:331:70
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> Аварийный останов (стек памяти сброшен на диск)

Linux - OpenSUSE 15.4
5.14.21-150400.24.55-default #1 SMP PREEMPT_DYNAMIC Mon Mar 27 15:25:48 UTC 2023 (cc75cf8) x86_64 x86_64 x86_64 GNU/Linux
exa v 0.9.0 from opensuse repository

**Comment by ariasuni** [comment]
This is a very old version of exa, it has been fixed in recent versions (>= 0.10). See https://github.com/ogham/exa/pull/616

Also, exa is unmaintained, please use [the active fork eza](https://github.com/eza-community/eza) instead.
