### ISSUE TITLE
The equivalent of ls -m

### ISSUE THREAD

**Issue by sohilkaushal** [ogham/exa#1186]
Hi Exa Team

I made the switch to exa sometime ago and was trying to replicate the functionality of `-m` flag from `ls`. 
The flag  does the following:
`Stream output format; list files across the page, separated by commas.`
This makes it quite useful to use as a part of deployment/automation scripts.

**Comment by eggbean** [comment]
[You shouldn't use `ls` in scripts for many reasons](https://unix.stackexchange.com/questions/128985/why-not-parse-ls-and-what-to-do-instead), but even if you wanted to, why not just use `ls` instead? Using `exa` would make it way less portable.

**Comment by sohilkaushal** [comment]
Hi @eggbean 

Thanks for the comment, I'll be closing this issue
