### ISSUE TITLE
Few of current used icons not compatable with nerd-fonts v3

### ISSUE THREAD

**Issue by zefr0x** [ogham/exa#1189]
After updating nerd-fonts to v3 few icons are broken.

https://github.com/ryanoasis/nerd-fonts/blob/v3.0.0/changelog.md#v300

```
exa - list files on the command-line
v0.10.1 [+git]
https://the.exa.website/
```

**Comment by yangxyo** [comment]
+1

**Comment by ariasuni** [comment]
Closing this, exa is unmaintained (see https://github.com/ogham/exa/issues/1243), and this has been merged in [the active fork eza](https://github.com/eza-community/eza). Thanks!
