### ISSUE TITLE
links broken on the official website

### ISSUE THREAD

**Issue by acehinnnqru** [ogham/exa#1195]
Page: https://the.exa.website/install/macos
The link about `* completions` in the last paragraph of this page:
<img width="720" alt="image" src="https://github.com/ogham/exa/assets/26767631/5697c4a5-63b0-4da3-a344-6331c6c107a1">

The link is broken.
It shoule be `https://raw.githubusercontent.com/ogham/exa/master/completions/bash/_exa` and `https://raw.githubusercontent.com/ogham/exa/master/completions/zsh/_exa`

**Comment by ariasuni** [comment]
Closed in favor of https://github.com/ogham/exa/issues/757

exa is unmaintained, use [the active fork eza](https://github.com/eza-community/eza) instead (see https://github.com/ogham/exa/issues/1243).
