### ISSUE TITLE
Any other projects similar to `exa`?

### ISSUE THREAD

**Issue by sivabudh** [ogham/exa#120]
Loving `exa` right now. In fact, I just did `alias ls='exa'` in my `.zshrc`. Lol.

Does anyone know if there are other packages like exa? Eg. A modern replacement for `X`.

Thanks!

**Comment by deathtrip** [comment]
grep replacement here:
https://github.com/BurntSushi/ripgrep

**Comment by ogham** [comment]
There's a very comprehensive list of Rust projects of all shapes and sizes: https://github.com/rust-unofficial/awesome-rust
