### ISSUE TITLE
make exa --tree more usable with symlinks

### ISSUE THREAD

**Issue by Janik-Haag** [ogham/exa#1200]
Currently I have `exa --git --tree --icons` as a alias for tree. And that works great with normal folders, but when working with symlinked folders `tree ./result` displays `./result -> /nix/store/rgckxqbb8asdyj0l66i6jrhwzqriahdf-labctl-0.0.15` and when doing `tree ./result/` it displays what I actually want displayed:
```
./result
├──  bin
│  └──  labctl
└──  share
   ├──  bash-completion
   │  └──  completions
   │     └──  labctl.bash
   └──  zsh
      └──  site-functions
         └──  _labctl
```

I think that behavior makes sense when using exa like ls, but fell like there should be a edgecase for the `--tree` flag.

**Comment by ariasuni** [comment]
Closing this in favor of https://github.com/ogham/exa/issues/393
