### ISSUE TITLE
Error on macOS Sierra Beta: malloc_zone_unregister

### ISSUE THREAD

**Issue by eshansingh** [ogham/exa#121]
For any directory with or without any options at all, exa reports this error: 
<br />
<br />`
<br />exa(5617,0x7fff97ab33c0) malloc: *** malloc_zone_unregister() failed for 0x7fff97aa9000
<br />`
<br />
<br />After which it doesn't exit until you press `^C`. I have macOS v `10.12 Beta (16A285a)`, which is the Sierra Public Beta that came out very recently, so it may be related to that (especially because it worked in El Capitan before). I also use the `fish` shell, v `2.3.1`. Any help would be greatly appreciated, and feel free to ask me for any other details. 
<br />
<br />Thanks in advance, and `exa` is awesome!

**Comment by eshansingh** [comment]
Some issues that might help: https://github.com/rust-lang/rust/issues/34674, https://github.com/jemalloc/jemalloc/issues/420

**Comment by eshansingh** [comment]
Rust has fixed this, it appears: https://github.com/rust-lang/rust/pull/34719. I think all that remains is for exa to update to the beta version or something. I'll look into it and attempt a PR (I don't know much about Rust, so this'll be a good opportunity for some basics too)

**Comment by ogham** [comment]
Thanks for being a brave beta-OS-build user! I use El Cap, which made me wonder why I didn't run into this myself until I read your description.

exa has fallen quite behind the latest versions of Rust over the past month or two while I've been away... there are almost certainly a number of fixes that have landed that we aren't using. I hope this is one of them.

**Comment by eshansingh** [comment]
Actually, the only reason that I've been using the beta is because I'm so damn excited about the Siri on the Mac feature. 😝. Anyway, thanks for looking into this!

**Comment by elliottsj** [comment]
I'd just like to add that I'm using the latest Sierra GM (macOS 10.12 (16A320)) and experiencing this issue as well.

**Comment by eshansingh** [comment]
@ogham Is there any news on this issue? Would you accept a PR?

**Comment by landaire** [comment]
The fix was included in rust 1.11.0, so I think all that should be required is to update the rust toolchain and recompile. If you build from source the issue shouldn't occur (I can't verify this at the moment as I'm reinstalling xcode tho)

**Comment by eshansingh** [comment]
@landaire Did you make it work? If so, I would really appreciate if you shared what steps you took to do so, as I've never really used rust. Thanks!

**Comment by landaire** [comment]
@eshansingh install the rust toolchain (https://www.rustup.rs/ would probably be the easiest way -- I don't like installing via curl/shell scripts tho so you could even just use brew with `brew install rust`). You can then do a `make install` from the project root and all should good.

**Comment by ogham** [comment]
I’ve got the remainder of the week away from work and Real Life. Going to knock out as many of these issues as I can, then release a new version. Sorry about the wait.

**Comment by ogham** [comment]
WRONG BUTTON

**Comment by eshansingh** [comment]
@ogham No problem, thanks!

**Comment by eshansingh** [comment]
Oooops

**Comment by ogham** [comment]
See? It’s not even the highlighted button!

**Comment by CSRaghunandan** [comment]
@ogham  even I'm getting the same error on macOS sierra :( I'm really curious to try this out. But alas.

Is there any workaround to get exa up and running in macOS sierra?

**Comment by eshansingh** [comment]
@CSRaghunandan Yes, if you update your Rust version to the latest. It worked for me.

**Comment by atelic** [comment]
I have this same problem on OS X 10.12.  The error from the `brew` version and the downloaded binary:
```
exa(47549,0x7fffd1e293c0) malloc: *** malloc_zone_unregister() failed for 0x7fffd1e1f000
```

I tried to resolve this by compiling from source. The first time I ran make install, it complained about not being able to find -lssl so I compiled with `env LDFLAGS="-I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib" make install` which compiled successfully and installed to `/usr/local/bin/exa`. Unfortunately it still gives the failing malloc error. 

I have `rustc` 1.13.0 installed.

**Comment by pthariensflame** [comment]
Meanwhile, I have `exa` installed with a recent Rust nightly and have had no problems on the current Sierra beta.

**Comment by CSRaghunandan** [comment]
@eshansingh That doesn't seem to be the case. I am on the latest version of `rustc`. I even tried installed by using nightly rustc and no luck with that too, I get the same error.

**Comment by CSRaghunandan** [comment]
@pthariensflame which nightly build are you using??

**Comment by iKevinY** [comment]
I was having troubles installing `exa` on Sierra a couple of weeks ago, but I just tried installing it again using the latest nightly (`ebeee0e27 2016-12-04`) and it seems to have worked fine.

**Comment by pthariensflame** [comment]
@CSRaghunandan

- `rustc --version`: `rustc 1.15.0-nightly (908dba0c9 2016-12-01)`
- `cargo --version`: `cargo 0.16.0-nightly (3568be9 2016-11-26)`
- `exa --version`: `exa 0.4.0`
- Install command: `RUSTFLAGS="-C target-cpu=native" cargo install --git git://github.com/ogham/exa`

**Comment by CSRaghunandan** [comment]
@pthariensflame Thank you so much 👍  
I was able to install it with command you provided

**Comment by eshansingh** [comment]
Hey @ogham this issue has been up here for far too long, it's been solved. For now, I'm closing it.
