### ISSUE TITLE
Missing library libgit2.so.1.6 after Arch update

### ISSUE THREAD

**Issue by empsps** [ogham/exa#1223]
After updating libgit2, exa stops working because it needs a specific version of that library.

Error message:
```
exa: error while loading shared libraries: libgit2.so.1.6: cannot open shared object file: No such file or directory
```
Version: `exa-git 0.10.1.r158.gc697d06-1` compiled from the AUR
OS: Arch Linux

**Comment by lukeemhigh** [comment]
Same Here, I found a workaround by removing the old version and reinstalling the git version:

```bash
cargo install --git https://github.com/ogham/exa.git
```

**Comment by llde** [comment]
You need to recompile to let the loader use the new libgit dynamic library

**Comment by ariasuni** [comment]
Yup, I’m not sure if there’s a way to tell yay or other AUR helpers to rebuild a package when its dependency gets updated…

**Comment by ariasuni** [comment]
exa is unmaintained, and this has been fixed in [the active fork eza](https://github.com/eza-community/eza).

See https://github.com/eza-community/eza/pull/192
