### ISSUE TITLE
`GIT_CEILING_DIRECTORIES` is not respected

### ISSUE THREAD

**Issue by mentalisttraceur** [ogham/exa#1226]
# Problem

When running a command with the `--git` option, it seems that `GIT_CEILING_DIRECTORIES` is not respected.

This can lead to huge delays when `exa` looks past a ceiling directory, finds a `.git` in some larger parent, and checks that entire larger tree for Git changes.

# Reproducible Example

The easiest repro is probably to temporarily make your home directory into a git repo, and see what that does to your execution time, with or without `GIT_CEILING_DIRECTORIES=~` in the environment:

```sh
mkdir ~/test &&
cd ~/test &&
time exa --all --long --git  # should be fast

cd ~ &&
git init &&
git commit --allow-empty -m 'test' &&
cd ~/test &&
time exa --all --long --git  # should be slow

export GIT_CEILING_DIRECTORIES=~ &&
time exa --all --long --git  # should be fast again
```

This is great for a test because your home directory is probably big enough to see the slowdown. (Just don't forget to `rm -rf ~/.git` when done, unless you're into that sort of thing... if you've just discovered you might be, I recommend `git config status.showUntrackedFiles no` and `export GIT_CEILING_DIRECTORIES=~`.)

# Misc.

Output of `exa --version` (but I would guess this happens with any version):

```
exa - list files on the command-line
v0.10.1 [+git]
https://the.exa.website/
```

Observed on the following OS+hardware combinations (but I would guess it this happens on any OS and any hardware):

1. Debian Linux on x86-64 CPU (Librem 14).
2. Debian in WSL2 in Windows 11 on x86-64 CPU (different laptop).
3. Termux in Android on Aarch64 CPU (two different phone models).

**Comment by mentalisttraceur** [comment]
Until this is fixed, here's a workaround.

I have Exa installed at `/use/bin/exa`, and so I have a wrapper script like this at `/use/local/bin/exa`:

```sh
#!/bin/sh -
if ! git rev-parse --git-common-dir 1>/dev/null 2>&1
then
    for argument in "$@"
    do
        shift
        if test "$argument" != '--git'
        then
            set -- "$@" "$argument"
        fi
    done
fi
exec /usr/bin/exa "$@"
```

Basically we first check if we're in a Git repo with the `git` CLI, and if that search fails (due to hitting a ceiling directory or otherwise), we remove any occurrences of the `--git` flag from Exa's arguments.

(The simplest way to remove arguments in portable shell script is to cycle through the arguments, using the argument list like a FIFO queue: at each iteration, we pop each argument from the beginning of the list, and then only push it back to the end if we're keeping it; it's safe to mutate the argument list while looping on arguments because the `for argument in "$@"` is evaluated only once, before the iterations start.)

**Comment by mentalisttraceur** [comment]
# Proposed Solution

I *think* this can be fixed by just changing [line 165 in `git.rs`](https://github.com/ogham/exa/blob/f039202b4f508200739e2114f74a539344d5bd1c/src/fs/feature/git.rs#L165) from

```rust
        let repo = match git2::Repository::discover(&path) {
```

to

```rust
        let flags = git2::RepositoryOpenFlags::FROM_ENV;
        let repo = match git2::Repository::open_from_env(&path, flags, &[] as &[&OsStr]) {
```).

**Comment by mentalisttraceur** [comment]
The solution in my last comment builds fine, passes `cargo test`, worked correctly in all of my manual testing, and I'm now running a build of Exa with this patch on all of my devices.

The way I initially wrote it *does* cause a "trivial cast" warning (due to the cast of `&[]`, since the `open_ext` template can't infer the type of an empty slice literal argument):

```
warning: trivial cast: `&[&OsStr; 0]` as `&[&OsStr]`
   --> src/fs/feature/git.rs:166:67
    |
166 |         let repo = match git2::Repository::open_ext(&path, flags, &[] as &[&OsStr]) {
    |                                                                   ^^^^^^^^^^^^^^^^
    |
    = help: cast can be replaced by coercion; this might require a temporary variable
note: the lint level is defined here
   --> src/main.rs:6:9
    |
6   | #![warn(trivial_casts, trivial_numeric_casts)]
    |         ^^^^^^^^^^^^^
```

Here's the best refactor I could quickly come up with to avoid that lint rule:

```rust
        let flags = git2::RepositoryOpenFlags::FROM_ENV;
        let unused: [&OsStr; 0] = [];
        let repo = match git2::Repository::open_ext(&path, flags, &unused) {
```

One objective advantage of writing it that way is that the code now more explicitly hints that the third parameter of `open_ext` is ignored in this case.

**Comment by cafkafk** [comment]
@ariasuni also this!

**Comment by ariasuni** [comment]
Closing this since exa is unmaintained (see https://github.com/ogham/exa/issues/1243), and this has been done in [the active fork eza](https://github.com/eza-community/eza).
