### ISSUE TITLE
Order of the columns

### ISSUE THREAD

**Issue by julas23** [ogham/exa#1237]
Wonderful job, I really enjoy exa. There is only 1 step for perfection in my opinion.
A resource to define the order of the columns. If I want for example:

User, Group, Octal, Permission, Date Modified, Size, Icon, Name

would be beyond the perfection, it is a lot better than lsd and other already

**Comment by ariasuni** [comment]
Closing in favor of https://github.com/ogham/exa/issues/161

**Comment by julas23** [comment]
Closed, but and my suggestion of both Permission and Octal in the list?
