### ISSUE TITLE
A way to not display the `@` (at sign) for files with extended attributes

### ISSUE THREAD

**Issue by blt-r** [ogham/exa#1240]
Exa displays an at sign after permissions for files which have extended attributes:
```
.rw-------@ 1.8k blt 26 Aug 19:46  .bash_history
.rw-r--r--@   18 blt  6 Feb 04:00  .bash_logout
.rw-r--r--@  141 blt  6 Feb 04:00  .bash_profile
.rw-r--r--@  492 blt  6 Feb 04:00  .bashrc
```
Those are kind of annoying, and on systems with selinux every file has an extended attriblute, so it doesn't make sense to mark them

**Comment by eggbean** [comment]
I don't think there is any way to do this, but as a workaround you could define a colour for the setting for extended attributes to be the same as the background colour of your terminal emulator ASCII theme. Then, it wouldn't be visible.

The extended attribute indicator key in `$EXA_COLORS` is `xa`.

https://github.com/ogham/exa/blob/master/man/exa_colors.5.md

**Comment by blt-r** [comment]
There's actually ANSII escape code for invisible/hidden text, so `EXA_COLORS=xa=8`, hides it.

This is a good workaround, but I think it would still be good to have an option for disabling them. Because this way there is an extra whitespace that doesn't do anything and makes the gaps between columns inconsistant.

More importantly, the `xa` is also responsible for color of the names of extended attributes when using the `--extended`/`-@` option. And setting it to `8` will hide those as well, which is not good.

**Comment by daviessm** [comment]
It looks like #855 would do this if merged.

It's already been merged into `eza`: https://github.com/eza-community/eza/pull/61

**Comment by cafkafk** [comment]
@ariasuni here's one

**Comment by ariasuni** [comment]
I just tested it and the `@` is still displayed when using `eza -l` and `eza -l -@`.

**Comment by cafkafk** [comment]
Ohh I see, sorry about that then!

**Comment by blt-r** [comment]
So, this issue should probably be transferred to eza

**Comment by ariasuni** [comment]
Transferred to eza.

https://github.com/eza-community/eza/issues/443
