### ISSUE TITLE
Please remove special bin icon association

### ISSUE THREAD

**Issue by dusanx** [ogham/exa#1242]
https://github.com/ogham/exa/blob/f039202b4f508200739e2114f74a539344d5bd1c/src/output/icons.rs#L66C42-L66C42

'bin' folder is not at all unusual in user home dir, I use it for ages to hold various scripts. Also seen it used my many users on Linux, that's how I even got idea to have ~/bin. It should have normal folder icon. Is there some special use case that requires special icon? Thank you.

**Comment by ariasuni** [comment]
Closing this, since exa is unmaintained (see https://github.com/ogham/exa/issues/1243), and this has been done in [the active fork eza](https://github.com/eza-community/eza). Thanks anyway!
