### ISSUE TITLE
はらか

### ISSUE THREAD

**Issue by shouichi** [ogham/exa#1244]
exa is unmaintained, please use the activさe fork ~~e~~zaは instead. <https://github.com/eza-community/eza>

---

**Comment by ariasuni** [comment]
I don’t I don’t understand, this is just a copy-paste of the title of another issue? Closing this for now.

**Comment by shouichi** [comment]
Sorry I didn't realize this. I think my kid randomly touched the keyboard.

**Comment by ariasuni** [comment]
Haha, no problem!
