### ISSUE TITLE
Allow parameters multiple times

### ISSUE THREAD

**Issue by Don42** [ogham/exa#125]
It should be allowed to call `exa -l -l`, since that can easily happen by accident
when exa is aliased to `exa -l` (which is often done with ls). 
Currently exa fails with an error.

I hope this makes some sense. If not, just ask.

**Comment by TyrfingMjolnir** [comment]
The command interpreter should sort and uniq then?

**Comment by Don42** [comment]
Just ignore duplicate options when they don't change the meaning of the command. I haven't checked what command line argument parser exa uses, but it should have the ability to allow multiple instances of an option without changing the command.

**Comment by Stebalien** [comment]
If you want this to "just work", you can use a featureful argument parsing library like [clap](https://crates.io/crates/clap).

**Comment by actionless** [comment]
i think the last occurence of argument should be used, for example if i have `alias ls="exa --color=always --git --long --more --and --more-options"` and sometimes if I need to do the same usual set of arguments but override only one of them i would be able to do it like `ls --color=no` instead of retyping full set of arguments

**Comment by lilianmoraru** [comment]
These flags seem like a maintenance burden(ex: https://github.com/ogham/exa/commit/763e833b6f3be5a0e4b9cf9f807a4b3874435c7e ).
`clap-rs` is fast and has a lot of features out of the box(correct alignment in the terminal, coloring, suggestions when passing wrong parameters, shell completion, etc...).

**Comment by ogham** [comment]
Yeah, it's looking more and more likely that I'm going to switch away from the standard getopts crate: I just looked at the source and [there doesn't seem to be a way to allow for the "last" argument](https://github.com/rust-lang-nursery/getopts/blob/b8beaf635aae10e09a692eaaa21b814796b85e57/src/lib.rs#L440-L442) like people want. There's also the [UTF-8 restriction](https://github.com/rust-lang-nursery/getopts/pull/29).

**Comment by actionless** [comment]
works great for me, thanks for your effort!
