### ISSUE TITLE
-l on nfs share

### ISSUE THREAD

**Issue by gimerstedt** [ogham/exa#126]
i'm getting an output containing "<Operation not supported (os error 95)>" when executing

``` sh
exa -l
```

on anything residing on an nfs share.

exa 0.4.0 installed via cargo on debian stretch (rust installed via rustup, rustc 1.12.0 (3191fbae9 2016-09-23)).

``` pre
ake1@jessica:/mnt/helena/storage/160414/bin$ ls -l
total 67232
-rw-r--r-- 1 root ake1 34422272 Oct 12 21:21 somebinary
-rw-r--r-- 1 root ake1 34422272 Mar 29  2016 somebinary2
ake1@jessica:/mnt/helena/storage/160414/bin$ exa -l
.rw-r--r-- 34M root 12 Oct 21:21 somebinary
                                 └── <Operation not supported (os error 95)>
.rw-r--r-- 34M root 29 Mar 21:38 somebinary2
                                 └── <Operation not supported (os error 95)>
```

**Comment by ogham** [comment]
Well this one’s a bit odd. It looks like exa is trying to read extended file attributes from your files, even though they don’t have any. I’ll look into it.

PS: Sorry for the delay

**Comment by satyenr** [comment]
I am getting the same error while using exa 0.7.0 as well as the one I built from `master` branch over NFS.

```shell
shell ~ % exa --version
exa 0.7.0
shell ~ % 
```

**Comment by ogham** [comment]
Yeah, this is the same issue as #178. I'm going to concentrate on that one because that issue has more comments. I know what the problem is; the difficulty is in fixing it, but it still has v0.8.0 (next week) as its target release date.
