### ISSUE TITLE
Consider aborting on panic

### ISSUE THREAD

**Issue by Stebalien** [ogham/exa#128]
As far as I can tell, `exa` doesn't actually catch panics or rely on unwinding in any way. Given that unwinding support generally makes binaries larger and can have a performance impact, please consider disabling it by adding `panic="abort"` to the release build profile (in `Cargo.toml`):

``` rust
[profile.release]
panic = "abort"
```

**Comment by ogham** [comment]
I’ll look into it and will do this if it doesn’t cause any problems.
