### ISSUE TITLE
Color broken links in non `-l` listings.

### ISSUE THREAD

**Issue by Stebalien** [ogham/exa#131]
Currently, when listing files with `exa -l`, missing link *targets* are colored red. However, when listing normally, the filenames (link names) aren't colored in any way.

As a comparison, `ls --color=always` colors the link name and `ls --color=always -l` colors both the link name *and* the link target.

**Comment by ogham** [comment]
Good idea

**Comment by ogham** [comment]
These are now red:

![screen shot 2017-05-07 at 15 36 21](https://cloud.githubusercontent.com/assets/503760/25782074/080ee9c6-333b-11e7-8b03-38e5b9d41855.png)
