### ISSUE TITLE
Publish to crates.io?

### ISSUE THREAD

**Issue by photex** [ogham/exa#132]
It would be great to have this because installation could be `cargo install exa` for those folks who already have cargo.
For non-cargo users and so on, a zipped  release like you have now would be fine still.

**Comment by ogham** [comment]
I haven’t looked into `cargo install`, but if it makes installation easier then that’s great! I’ll see what I can do.

**Comment by ogham** [comment]
I tried doing this for the 0.7.0 release, but it didn't take it because exa has a non-crates.io dependency.

The next release should be up there, promise!

**Comment by photex** [comment]
Looking forward to it! Thanks for the update :)

**Comment by ogham** [comment]
Try now :)
