### ISSUE TITLE
exa --classify option

### ISSUE THREAD

**Issue by grenmester** [ogham/exa#139]
There is an option in `ls` called `--classify` which appends an indicator (`*/=>@|`) to each entry depending on the type of entry (directory, binary, symlink, etc.). For example, a `/` would be appended to each directory.

With standard `ls`, you would get something like this:
```
Cargo.lock  Cargo.toml  LICENCE  Makefile  README.md  Vagrantfile  contrib  screenshots.png  src  xtests
```

Whereas with `ls --classify`, you would get something like this:
```
Cargo.lock  Cargo.toml  LICENCE  Makefile  README.md  Vagrantfile  contrib/  screenshots.png  src/  xtests/
```

I think it would be nice if `exa` had this option too.

**Comment by SShrike** [comment]
Just realised this feature was missing, would be nice if it could be added :)

**Comment by ogham** [comment]
Eventually exa's gonna need this for ls compatibility.

**Comment by ogham** [comment]
This got done with #159.

**Comment by dbeckwith** [comment]
This should be added to the README documentation. I was looking to see if `exa` had this and had to search through the issues to find it.

**Comment by dieggsy** [comment]
@dbeckwith you can also always `exa --help`, though I agree it could be added to the README
