### ISSUE TITLE
Release new version to GitHub?

### ISSUE THREAD

**Issue by elliottsj** [ogham/exa#143]
Is the latest code on `master` suitable for a new [release](https://github.com/ogham/exa/releases)? I'd like to install the latest version through [`brew cask`](https://github.com/caskroom/homebrew-cask/blob/3ec1b906ae4ec3b87bf56df15b6dbefa095b6788/Casks/exa.rb) to avoid the `malloc_zone_unregister` issue (#121). Thanks!

**Comment by elliottsj** [comment]
I'm also wondering whether it would be ideal to move exa from homebrew-cask over to [homebrew-core](https://github.com/Homebrew/homebrew-core). From my understanding, this would allow us to do something like `brew install exa --HEAD` to install the latest version from source.

**Comment by iKevinY** [comment]
Good call! I was the one who originally wrote the formula for `exa`; at that time, there were pretty much no other Rust-build core formulae, so I just wrote it as a `homebrew-cask` formula instead.

I have a core-compatible formula ready to go if you want to push a new release, @ogham!

**Comment by sethvoltz** [comment]
@iKevinY Mind sharing for those of us who want to do it anyway?

**Comment by iKevinY** [comment]
The Homebrew folks don't accept HEAD-only formulae anymore, so I have to wait for a new stable release of `exa` before submitting the formula to Homebrew's core. In the mean time, it's probably easier to just install it via `cargo install --git https://github.com/ogham/exa`.

**Comment by MoritzFago** [comment]
I too have the issue #121 after I installed exa via home-brew cask. How should I proceed. Also for home-brew core vs cask: core allows automatic updates via brew, as cask is afaik only for install and not for updating, it foists this off to the autoupdaters, which usually come with GUI software, for whom cask was made. Just my 2 cents.

**Comment by iKevinY** [comment]
@MoritzFago If you install Rust using either Homebrew or [`rustup`](https://rustup.rs), it should include Cargo, which means you can run the command in my comment above to install `exa` directly from the `master` branch of this repository (which fixes that issue).

**Comment by iKevinY** [comment]
Given the circumstances, I think I'm going to fork `exa` strictly for the purpose of publishing a new release, and then work on updating the Homebrew formula to point to this release. This seems better than simply leaving a broken release up. To clarify, I won't be forking `exa` to maintain further development, but rather simply to get Homebrew installation working again.

For some additional context, I sent an email to @ogham about a month ago regarding pushing a new release, and he hasn't replied; I'd be more than happy to close my fork if development resumes.

**Comment by ogham** [comment]
I created a release (accompanied by a short novella) here: https://github.com/ogham/exa/releases/tag/v0.4.1

**Comment by iKevinY** [comment]
@ogham Glad to see you're doing alright! I totally empathize with your situation — it's only natural for motivation and interests to shift, and sometimes it's best to simply take a break.

Thank you for creating this new release; I'll go and update my Homebrew PRs! 😄

**Comment by elliottsj** [comment]
@ogham Great to hear back from you. I really appreciate your courage writing about your motivation trouble in the release notes. Every developer has to take a break from time to time, [especially in open source](http://jlongster.com/Why-Frequently-Absent-Open-Source). I know I've had trouble motivating myself over the past little while too; so you're not alone ❤️

I'm sure I speak for all exa users when I say that no one thinks poorly of you or thinks you made a mistake by not replying to bug threads. I, for one, am happy that you created exa, no matter how much of your time you decide to dedicate to help maintain the project 😄

I would love to start contributing more to exa as soon as I get the opportunity; learning rust has been something I wanted to do for a while now. I'm setting myself a reminder to look through other issues in this repo to help triage them.

**Comment by vitorgalvao** [comment]
This issue can now be closed. `exa` is now a formula instead of a cask.

**Comment by elliottsj** [comment]
Link for the lazy: https://github.com/Homebrew/homebrew-core/pull/11817
