### ISSUE TITLE
Instructions to install with Homebrew need updating

### ISSUE THREAD

**Issue by vitorgalvao** [ogham/exa#148]
We recently changed the location of `exa` to now be a formula instead of a cask.

What this means is [the installation instructions](https://the.exa.website/#installation) need to change:

- [ ] [Homebrew Cask](http://caskroom.io) → [Homebrew](https://brew.sh/) (note the link also changes).
- [ ] `brew cask install exa` → `brew install exa`.

**Comment by ogham** [comment]
Fixed and fixed! https://the.exa.website/
