### ISSUE TITLE
Does Not Show Git Status in Subdirectories

### ISSUE THREAD

**Issue by shockone** [ogham/exa#15]
If we have a modified file in a subdirectory (related to git root folder), the subdirectory is marked as modified, but the file is not. Please see the screenshot

https://www.dropbox.com/s/n2zmyacreuowb78/Screenshot%202015-02-22%2015.40.41.png?dl=0

**Comment by coyotebush** [comment]
More generally, the Git status information seems to work correctly if and only if `exa`'s cwd is the root of the working tree. I'm trying to figure out the necessary Path manipulations, but it's proving a bit tricky so far.
