### ISSUE TITLE
Feature Request: `ls -F` capability

### ISSUE THREAD

**Issue by gltarsa** [ogham/exa#151]
I love the features and colors in `exa`, but I would also like the `ls -F` ability to have character markings for the files as well, at least as an option. From the `ls` man page:

```
 -F   Display a slash (`/') immediately after each pathname that is a
        directory, an asterisk (`*') after each that is executable, an at
        sign (`@') after each symbolic link, an equals sign (`=') after each
        socket, a percent sign (`%') after each whiteout, and a vertical bar
        (`|') after each that is a FIFO.
```

I have so many things with colors and so many differing color conventions that, while I use them as background queues, I cannot easily remember which color is what specific significance.  Reinforcing them with the characters if very helpful.

**Comment by ogham** [comment]
Personally I’ve never seen the use of these characters... but they seem to be a popular feature request, so they’re going in. I guess I’m just too used to the default colours by now.

This is being tracked in #139, and it’ll likely be called `--classify`.
