### ISSUE TITLE
Contrary to homepage claim, the downloadable binary is not self-contained

### ISSUE THREAD

**Issue by chdiza** [ogham/exa#158]
The homepage says one can just download the precompiled `exa` binary, and that: "The binary is entirely self-contained, so that’s all you need"

This doesn't seem to be true.  If I download said binary and try to run it I get:
```
 ./exa-macos-x86_64
dyld: Library not loaded: /usr/local/opt/libssh2/lib/libssh2.1.dylib
  Referenced from: /Users/chdiza/Downloads/./exa-macos-x86_64
  Reason: image not found
Abort trap: 6
```

**Comment by chdiza** [comment]
I should've added, of course that this is on macOS 10.12.4.

**Comment by ogham** [comment]
You’re so right! I was compiling with `OPENSSL_STATIC=yes`, and I just sort of assumed that would do the trick. I’ll look into this.

**Comment by kballard** [comment]
Why is exa even using OpenSSL? Presumably the dependency is coming in via the `git2` crate, but `exa` doesn't use the network, so it should disable the network-related git features.

**Comment by kballard** [comment]
PR #174 submitted to fix this, though a new release will have to be done before it's truly fixed.

**Comment by ogham** [comment]
> Why is exa even using OpenSSL?

Simple answer: I didn't know that the SSL features of the git2 crate could be turned off! Having to install and configure OpenSSL was a "necessary evil" because I assumed it was the only way exa could link to libgit2. It's a huge relief to know that it's not actually necessary.

The next version is on track to be released next week.

**Comment by lmlsna** [comment]
This has also never been true of any of the linux x86_64 releases, each of which require several dynamically linked libraries:

> exa 0.2.0
> 	linux-vdso.so.1 =>  (0x00007fff0bddc000)
> 	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f4ec2e4d000)
> 	libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f4ec2a09000)
> 	libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007f4ec279f000)
> 	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4ec23d5000)
> 	/lib64/ld-linux-x86-64.so.2 (0x00005585ea319000)
> 	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f4ec20cc000)
> 	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f4ec1eae000)
> 	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f4ec1c98000)
> 	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f4ec1a94000)
> 
> exa 0.3.0
> 	linux-vdso.so.1 =>  (0x00007ffe08d4b000)
> 	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fad8814b000)
> 	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fad87f30000)
> 	libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007fad87cc7000)
> 	libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007fad87883000)
> 	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fad8767e000)
> 	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fad872b4000)
> 	/lib64/ld-linux-x86-64.so.2 (0x0000559a4ddad000)
> 	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fad87097000)
> 	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fad86e80000)
> 
> exa 0.4.0
> 	linux-vdso.so.1 =>  (0x00007ffee5b84000)
> 	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fc60b20f000)
> 	libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007fc60afa5000)
> 	libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007fc60ab61000)
> 	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fc60a95d000)
> 	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fc60a742000)
> 	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fc60a378000)
> 	/lib64/ld-linux-x86-64.so.2 (0x0000556c5be3b000)
> 	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fc60a15b000)
> 	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fc609f44000)
> 
> exa 0.5.0
> 	linux-vdso.so.1 =>  (0x00007ffc64d92000)
> 	libssh2.so.1 => /usr/lib/x86_64-linux-gnu/libssh2.so.1 (0x00007f7e13928000)
> 	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f7e1370e000)
> 	libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007f7e134a4000)
> 	libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f7e13060000)
> 	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f7e12e5c000)
> 	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f7e12c53000)
> 	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f7e12a36000)
> 	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f7e12820000)
> 	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f7e12455000)
> 	/lib64/ld-linux-x86-64.so.2 (0x000056026494f000)
> 	libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007f7e12174000)
> 	libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007f7e11f5f000)
> 
> exa 0.6.0
> 	linux-vdso.so.1 =>  (0x00007fff5addb000)
> 	libhttp_parser.so.2.1 => /usr/lib/x86_64-linux-gnu/libhttp_parser.so.2.1 (0x00007fb169216000)
> 	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fb168ffc000)
> 	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fb168df7000)
> 	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fb168bef000)
> 	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fb1689d2000)
> 	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fb1687bb000)
> 	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb1683f1000)
> 	/lib64/ld-linux-x86-64.so.2 (0x000055f70f195000)
> 
> exa 0.7.0
> 	linux-vdso.so.1 =>  (0x00007ffc05da5000)
> 	libhttp_parser.so.2.1 => /usr/lib/x86_64-linux-gnu/libhttp_parser.so.2.1 (0x00007f545eaec000)
> 	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f545e8d2000)
> 	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f545e6cd000)
> 	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f545e4c5000)
> 	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f545e2a8000)
> 	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f545e091000)
> 	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f545dcc7000)
> 	/lib64/ld-linux-x86-64.so.2 (0x0000560525edb000)
