### ISSUE TITLE
Option to use some parts of the --long features

### ISSUE THREAD

**Issue by simonsolnes** [ogham/exa#182]
As an example: Be able to list files with just sizes, nothing else.

**Comment by simonsolnes** [comment]
My suggestion would be something like this:

`exa -l --show-user=false --show-permissions=false`

**Comment by rivertam** [comment]
This would be great. I personally find the permissions column pretty unsightly and would love a way to remove it.

**Comment by ogham** [comment]
PR #577 added options like `--no-user` and `--no-permissions`.
