### ISSUE TITLE
The flags --git and -T cannot be combined.

### ISSUE THREAD

**Issue by simonsolnes** [ogham/exa#183]

**Comment by philpennock** [comment]
nb: in `exa 0.7.0`, the behavior is `Option --git is useless without option --long.` which makes this issue a dup of #152

**Comment by ogham** [comment]
<img width="409" alt="screen shot 2017-09-02 at 22 38 29" src="https://user-images.githubusercontent.com/503760/29998950-806dda34-902f-11e7-84dc-e8ae1d29c0ac.png">

This is finally working now
