### ISSUE TITLE
Wrong display of relative links

### ISSUE THREAD

**Issue by alexherbo2** [ogham/exa#188]
It happens when listing a particular file from the current directory.

### Example

```
mkdir foo
touch foo/bar
ln --symbolic foo/bar
exa --long bar
```

### Display

```
… … … … bar -> bar
```

### Should be

```
… … … … bar -> foo/bar
```

**Comment by ogham** [comment]
Just tried it out, and it works on my machine (macOS, exa v0.6.0):

![screen shot 2017-07-04 at 16 02 28](https://user-images.githubusercontent.com/503760/27835284-3e5f3c3c-60d2-11e7-9787-21635b4dba9d.png)

What version of exa are you running? `exa --version` will tell you.

**Comment by alexherbo2** [comment]
I can confirm it works on `0.6.0`.

I was using `0.4.0` version.

**Comment by ogham** [comment]
Glad it works!
