### ISSUE TITLE
Start using system timezone data again

### ISSUE THREAD

**Issue by ogham** [ogham/exa#189]
exa has a dependency on zoneinfo-compiled, which is preventing it from being packaged up.

Nix doesn't like it because it's non-deterministic: https://github.com/NixOS/nixpkgs/issues/14125

And crates.io itself is refusing to take it as well (#132): "crates cannot be published to crates.io with dependencies sourced from a repository".

Once this crate gets published, and exa gets updated to use it, it can be published to these two places.

**Comment by Mic92** [comment]
Is it possible that git dependencies are handled differently in newer version of Cargo? https://github.com/jwilm/rust-fontconfig/pull/1#issuecomment-315792775
