### ISSUE TITLE
Exec format error?

### ISSUE THREAD

**Issue by therockmandolinist** [ogham/exa#190]
On `v0.7.0`, I'm getting `exec format error: ./exa-linux-x86-64` when trying to run the executable.

**Comment by ogham** [comment]
Oh dear:

    $ md5sum exa*64
    6db5104d532048691caa61ce388043af  exa-linux-x86-64
    6db5104d532048691caa61ce388043af  exa-macos-x86_64

**Comment by ogham** [comment]
Yeah, I accidentally uploaded the mac version twice! I've uploaded a new one; could you try again please?

**Comment by therockmandolinist** [comment]
Ah, that would do it. Everything seems to be in order now, thanks!

**Comment by ogham** [comment]
Good to know! Thanks for reporting it.
