### ISSUE TITLE
font-awesome icons

### ISSUE THREAD

**Issue by lilianmoraru** [ogham/exa#191]
It seems that people really want [`font-awesome`](https://github.com/FortAwesome/Font-Awesome) icons(comments section): http://www.omgubuntu.co.uk/2017/07/add-bling-ls-bash-command-colorls

I throw this issue in, if you want to consider it...

**Comment by luisdavim** [comment]
I'm currently using [els](https://github.com/AnthonyDiGirolamo/els), I use it with the `--els-icons=fontawesome` option and just learned about exa, exa looks awesome but I do miss the icons

**Comment by elamperti** [comment]
Perhaps using `nerdfonts` would be more appropriate?

**Comment by taohex** [comment]
I need [nerd-fonts](https://github.com/ryanoasis/nerd-fonts), too. I'm currently using [colorls](https://github.com/athityakumar/colorls).

**Comment by keenahn** [comment]
Sorry to necro, but I was going to start an issue just for this :)

**Comment by lilyball** [comment]
Looks like this was done in #368.

**Comment by obax** [comment]
Agreed with @lilyball. It is done.
