### ISSUE TITLE
exa does not list the contents of symbolic links to directories

### ISSUE THREAD

**Issue by lilianmoraru** [ogham/exa#192]
`exa --version`: `exa 0.7.0`

Trying to list symbolic links to directories doesn't work:
`exa [symbolic link to a directory]` won't show the contents of the directory, only the name of the link, the same way it would do for a file for example.

My `Downloads` directory is a symbolic link.
I observed that `exa D*` lists less files than `ls D*` and that's how I ended up discovering that it does not list the contents of symbolic links to directories...

**Comment by ogham** [comment]
(Accidentally hit the Milestone button and there's no Undo!)

exa currently has the behaviour where if you `exa ~/Downloads` it'll list the link, but if you `exa ~/Downloads/`, with the trailing slash, it'll list the link's target's contents. However, I can see why you'd want this to be standard behaviour — it's not exactly discoverable!

GNU ls has the `--dereference-command-line-symlink-to-dir` option, which in addition to being the longest one I've ever seen, means that it does this by default. I'll look into adding something similar for exa.

**Comment by pepa65** [comment]
I have the opposite problem, I have a symlink to a directory that I would like to see the target of, but if I do `exa dirname` (`dirname` is a symlink) it lists the contents, whether I append a slash or not... Is it still possible on `exa v0.10.1`?

**Comment by ariasuni** [comment]
Well, you can use `exa -d`. I encourage you to use [eza](https://github.com/eza-community/eza) instead of exa, though.

**Comment by pepa65** [comment]
So is `exa` more or less unmaintained?

**Comment by ariasuni** [comment]
exa is 100% unmaintained, eza si the continuation (which I sometimes contribute to).
