### ISSUE TITLE
`ls` is two characters, `exa` is three

### ISSUE THREAD

**Issue by ddevault** [ogham/exa#195]
I consider this a bug

**Comment by silverwind** [comment]
So alias it to `l`.

**Comment by SirCmpwn** [comment]
Don't have to move your fingers from the home row to type `ls` either, plus it's symmetric.

**Comment by up0** [comment]
I always alias 'ls' to 'l' since even 2 letter is too long.

**Comment by WoLpH** [comment]
Simple enough to fix: `alias l=exa`

The bigger problem is that the arguments for `exa` are different.

**Comment by kongslund** [comment]
My solution: `alias e='exa -l --git'`

**Comment by AlexNPavel** [comment]
Yeah, I aliased ls to exa, but some arguments are different in exa (stuff like -A and -Z are missing)

**Comment by FSMaxB** [comment]
Instead of using an alias, you can make a shell function that parses and rewrites command line parameters ...

**Comment by ogham** [comment]
Seriously, though, someone on Hacker News suggested `xa` and I'm not sure how I feel about it!

**Comment by SirCmpwn** [comment]
+1 for xa

**Comment by therockmandolinist** [comment]
@SirCmpwn just curious, why are you unsatisfied with an alias?

**Comment by SirCmpwn** [comment]
I could use an alias but that does't make the program any less wrong

**Comment by CoffeeFrame** [comment]
I have xs as my default alias and xa to show hidden files.

**Comment by grantcarthew** [comment]
Rename the whole project to `L` and be done with it....  :)

**Comment by eMBee** [comment]
how about lx?

the l from ls, the x from exa, could mean 'list extra' or 'list expanded' 'list exemplary'

**Comment by WoLpH** [comment]
Perhaps `la`? It's on the "default" keyboard row so you don't need to move your fingers and it could stand for "list advanced"

**Comment by gasinvein** [comment]
Maybe it would be better to make exa's arguments exactly same as ls (with some additions), so it could be used as drop-in replacement for ls?

**Comment by MggMuggins** [comment]
I have both an alternative solution to this problem (fish shell only :P), and a bug that I'm not quite sure whether or not I should open an issue for...
Anyway, I use a fish function (works similarly to an alias)
```fish
function ls
    exa -g1h $argv
end
```
My problem is that `-1` and `-l` conflict. So running `ls -la` doesn't work, because I've included `-1` in my default param list. I've removed `-1` for now, should I open a bug/PR?

**Comment by clarcharr** [comment]
I think that offering `xs`, `xl`, and `xa` aliases via exa would be nice, as most people use the aliases `ls`, `ll`, and `la`.

**Comment by pohart** [comment]
anything that starts with x will be harder to type because it requires pulling the ring finger back on what is normally the non-dominant hand.

lx seems okay, and it should be fine to alias ll and la to exa because they aren't called by scripts anyway.

**Comment by ariasuni** [comment]
Closing this in favor of #676.
