### ISSUE TITLE
Add arguments to make exa a drop-in replacement for ls

### ISSUE THREAD

**Issue by WoLpH** [ogham/exa#198]
First of all, great work, it looks really nice and I believe it could be a great `ls` replacement!

However... if it's not a drop-in replacement I'll never use it because:

1. I can't install it on all the machines I work on
2. The arguments are different, considering which machine I'm on before typing my `ls` commands is a pain

Example `ls` call that I use often: `ls -lahrt`

Would it be possible to support an alternative executable name with different commandline options? By looking at `env::args().nth(0)` it should be possible to detect if the command is called as `ls`

**Comment by carbureted** [comment]
+1 for this, would love to be able to drop in exa for ls, even if there was a performance hit or similar.

**Comment by ogham** [comment]
There's some discussion of this over at #332.
