### ISSUE TITLE
Add ability to show directory size (similar to du)

### ISSUE THREAD

**Issue by up0** [ogham/exa#199]
I would like to request a feature to be able to list directories with size, similar to 'du'.  This would make me use 'exa' over 'ls' permanently.  Thank you.

Example:  

    $ exa -s /   #similar to du --max-depth=1
    bin/ 85M
    dev/ 4K
    etc/ 2.5M
    home/ 358M
    lib/ 90M
    tmp/ 4.2M

**Comment by ogham** [comment]
It's a nice idea — another command-line tool to assimilate! It's being tracked in #91. Unfortunately, I looked at the code recently and it's not set up to handle recursing into a directory twice (once to get the size, and again to get the entries). I'm leaving that issue open, though, so I can get around to it eventually.

**Comment by mlopezcoria** [comment]
It would be useful to have this information
