### ISSUE TITLE
-l Option Errors in Empty Directories

### ISSUE THREAD

**Issue by shockone** [ogham/exa#20]
* Open an empty directory
* exa -l

`thread '<main>' panicked at 'called `Option::unwrap()` on a `None` value', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/option.rs:362`

**Comment by shockone** [comment]
Actually, I was wrong, It's not an empty directory. It's a directory containing a symbolic link to the parent directory. 
https://www.dropbox.com/s/31teyc4j7u4dhrx/Screenshot%202015-02-22%2023.03.17.png?dl=0

**Comment by ogham** [comment]
I'm able to reproduce this; working on a fix.

**Comment by ogham** [comment]
Yeah, this seems to be working much better:

![screen shot 2015-02-23 at 11 21 47](https://cloud.githubusercontent.com/assets/503760/6326885/42601b7a-bb4e-11e4-9bac-ee27b6ef5f2f.png)

**Comment by shockone** [comment]
Thank you very much. I'm impressed with your response times! 

Actually, I have a little project of rewriting `ls` too, but it's in Haskell, and my goal is to just repeat the GNU implementation.
