### ISSUE TITLE
Document what the color actually means

### ISSUE THREAD

**Issue by Drup** [ogham/exa#200]
exa prides itself for providing useful information through colors .... but doesn't actually list what they mean anywhere!

For example, I have literally no idea what underlined yellow is supposed to mean.

**Comment by manaskarekar** [comment]
I agree that it should be documented, but here's a quick reference.

https://github.com/ogham/exa/blob/master/src/output/colours.rs

**Comment by Drup** [comment]
That's a list, not a reference nor a documentation. I still have no idea what "immediate" files are. :)

**Comment by ogham** [comment]
I agree, it's not clear.

**Comment by nijikokun** [comment]
@Drup for now perhaps [these lines](https://github.com/ogham/exa/blob/f54bc417928b4b35ded68ff9ac840a7c5ba98767/src/info/filetype.rs#L15-L17) will help!

**Comment by Drup** [comment]
This is ... oddly specific, given the rest of the tool (and ls) only outlines concrete status of elements in the filesystem.

**Comment by laughedelic** [comment]
Also it's unclear how `README` (only in caps, `readme.md` doesn't match) fits this definition:

> An “immediate” file is something that **can be run or activated somehow
in order to kick off the build of a project**. It’s usually only present
in directories full of source code.

I agree with @Drup that this is too specific and I think it's hard to define well and implement. So that it will lead more to inconsistencies and users confusion: 

> "why is my readme in one project is bold yellow and in another it's not? ah, this coloring means that it's an "immediate" file! wait, but then why `build.sbt` in my Scala project is not highlighted, but the readme is?!"

**Comment by majutsushi** [comment]
Defining file types like these would be much better done by respecting `$LS_COLORS` (see #116) than by having a hardcoded list in exa itself.

**Comment by thedarkfalcon** [comment]
I wondered what the yellow underlining meant, couldn't figure it out so ran _exa --help_ no information there, went to the exa main website.. no information there, so I looked in the release notes.. no information there.. looked on the github project page... no information there.. Thankfully someone made a github issue to ask 😂

**Comment by ogham** [comment]
Oh, this was #261 too.

I've now [added some documentation to the man page](https://github.com/ogham/exa/commit/d4bbfb39f037daf123cd6139f5ffaac01e039758) that says what the colours mean, how to customise them, and how to turn them off.

**Comment by vii33** [comment]
Had the same issue, found this thread. I took @ogham 's notes and put them into a proper markdown format: https://github.com/ogham/exa/blob/c1c88dbbf30da4fbf7b3c98fe8cd545961edda60/man/exa-colors-explanation.md

Hopefully this helps others as well.

Great peace of software by the way 👍
