### ISSUE TITLE
Download of zip file is not self-contained

### ISSUE THREAD

**Issue by jdeisenberg** [ogham/exa#203]
The web page `https://the.exa.website/#installation` says:

> The binary is entirely self-contained, so that’s all you need.

When I unzipped the `exa-linux-x86_64-0.7.0.zip` file to my `~/bin` directory, changed the name to `exa`, and tried to run it, I got these results:

```
david@linux:~> exa webstuff
exa: error while loading shared libraries: libhttp_parser.so.2.1: cannot open shared object file: No such file or directory
```

**Comment by ogham** [comment]
Yeah, this is happening because exa accidentally includes libgit2's networking features, even though it doesn't use any of them. It's in #194.

Are you able to download that library from your package manager?

**Comment by jdeisenberg** [comment]
I already had it, but not under the correct name. This fixed it:

````
cd /usr/lib64/
ln --symbolic libhttp_parser.so.suse0 libhttp_parser.so.2.1
````

**Comment by juleskers** [comment]
I'd very much appreciate if this was fixed.
I'm loving `exa` to browse the 5 petabytes of work-data I have access to, but for security reasons, we are not allowed admin access to our machines.

I can run `exa` from `~/bin`, but the current download is broken, and without admin access, I cannot fix these linking problems (the installed packages provide a `libhttp_parser.so.2`, but not a `2.1`)

**Comment by eliasp** [comment]
@juleskers as a workaround you could simply set `LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:~/lib/` and place a copy of `libhttp_parser.so.2.1` in `~/lib`, so `exa` should find it and you won't need administrative privileges to run it.

**Comment by ogham** [comment]
As another workaround you could use [v0.8.0](https://github.com/ogham/exa/releases/tag/v0.8.0) which fixes this issue.

**Comment by juleskers** [comment]
Hurray! Thanks!
