### ISSUE TITLE
Website release notes don't list v0.7.0

### ISSUE THREAD

**Issue by kballard** [ogham/exa#208]
https://the.exa.website/release_notes.html lists v0.6.0 as the latest version.

**Comment by wezm** [comment]
Now missing 0.8. I'd be happy to update but looks like the website isn't on GitHub.

**Comment by ogham** [comment]
The website's a bit of a pain to update at the moment (I lost the original source files). Thought I could get the new one out this weekend, but didn't quite make it, so I just edited the minified HTML so I'm not *two* versions behind for any longer.
