### ISSUE TITLE
Non-case-sensitive sorting is documented wrong in README

### ISSUE THREAD

**Issue by lorenzos** [ogham/exa#209]
Regarding sorting options, the README says:

> Fields starting with a capital letter are case-sensitive.

But in my experience this is the exact-opposite. By the way, any reason why the default sorting is case-sensitive? I find it strange and confusing.

    $ exa -l -s name
    .rw-rw-r-- 1,5k lorenzo 15 giu  2:00 LICENSE
    .rw-rw-r-- 2,0k lorenzo 15 giu  2:00 PATENTS
    .rw-rw-r--  849 lorenzo 15 giu  2:00 README.md
    drwxrwxr-x    - lorenzo  1 ago 17:22 dist
    drwxrwxr-x    - lorenzo  1 ago 17:22 lib
    .rw-rw-r-- 3,1k lorenzo  1 ago 17:22 package.json
    .rw-rw-r--   56 lorenzo 15 giu  2:00 react.js

    $ exa -l -s Name
    drwxrwxr-x    - lorenzo  1 ago 17:22 dist
    drwxrwxr-x    - lorenzo  1 ago 17:22 lib
    .rw-rw-r-- 1,5k lorenzo 15 giu  2:00 LICENSE
    .rw-rw-r-- 3,1k lorenzo  1 ago 17:22 package.json
    .rw-rw-r-- 2,0k lorenzo 15 giu  2:00 PATENTS
    .rw-rw-r--   56 lorenzo 15 giu  2:00 react.js
    .rw-rw-r--  849 lorenzo 15 giu  2:00 README.md

**Comment by laughedelic** [comment]
I just want to add that for me the documented way makes more sense: to use fields with _changing_ case (i.e. with a capital letter) for case-_sensitive_ search. Then the default ones should be case-insensitive.

**Comment by ogham** [comment]
Hey, you're right. I got it wrong when I wrote the docs.

**Comment by ogham** [comment]
57c647fee52f96f0a2338a23d70abe5fa0aca0d0 actually fixed it (the docs now match the implementation) and I forgot to close the issue!
