### ISSUE TITLE
Should escape or quote file and directory names that can't be passed as is to the command line (like ls)

### ISSUE THREAD

**Issue by FSMaxB** [ogham/exa#211]
When you have a file or directory called `;` or `~` for example, you can't just delete them or do anything else with them without quoting. The same for some special characters. So what `ls` from coreutils does is to escape these characters or put the file names in quotes in the directory listing (so you could just copy paste the name and paste it into the command line if you want to do something with the file).

I think it would be useful to have that in exa as well.

**Comment by jdanford** [comment]
GNU `ls` does a decent job of quoting such names, and it looks like the [go-shellquote](https://github.com/kballard/go-shellquote) package approximates its behavior.

**Comment by Don42** [comment]
I couldn't find a way to get `ls` to quote special characters, but that might be because I'm using an old version.
I tried to build another escape function, although I'm not sure what the two styles are used for. So it might not work for all or even most usecases in exa.
[0] 510e2fde9aba40bc1c1b55d708de7c6b6e8d5764

**Comment by HaleTom** [comment]
Here is an example of `ls` vs `exa`:

```
% /bin/ls -l --quoting-style=shell-escape
total 0
-rw-r--r-- 1 ravi ravi 0 Jul  5 16:56 ''$'\026'
drwxr-xr-x 1 ravi ravi 0 Jul  3 15:36  a
-rw-r--r-- 1 ravi ravi 0 Jul  3 11:10 'a b'
-rw-r--r-- 1 ravi ravi 0 Jul  3 11:12  bar
-rw-r--r-- 1 ravi ravi 0 Aug 11 18:14 'b c  '
-rw-r--r-- 1 ravi ravi 0 Jul  3 11:12  foo
-rw-r--r-- 1 ravi ravi 0 Jul  3 11:10 'x'$'\b''x'
% exa -l
.rw-r--r-- 0 ravi  5 Jul 16:56 \u{16}
drwxr-xr-x - ravi  3 Jul 15:36 a
.rw-r--r-- 0 ravi  3 Jul 11:10 a b
.rw-r--r-- 0 ravi  3 Jul 11:12 bar
.rw-r--r-- 0 ravi 11 Aug 18:14 b c
.rw-r--r-- 0 ravi  3 Jul 11:12 foo
.rw-r--r-- 0 ravi  3 Jul 11:10 x\u{8}x
```

**Comment by flying-sheep** [comment]
I think modern shells also accept `$'x\bx'`, which would be a bit prettier than `'x'$'\b''x'`

**Comment by ariasuni** [comment]
Closing this in favor of #216.
