### ISSUE TITLE
'iso' date, using MM-DD HH:MM for previous year

### ISSUE THREAD

**Issue by uazu** [ogham/exa#213]
Using `--time-style=iso`, the current year is displayed as YYYY-MM-DD, and previous year as MM-DD HH:MM. Surely it should be the other way around?

**Comment by ogham** [comment]
Yes, it should! I think this is pretty clearly a programming mistake.

**Comment by ogham** [comment]
Fixed by #250 and tested by 4cb28593fdd13a0c6269cb6e98332bd9e9ce815a.
