### ISSUE TITLE
Human sorting mode for numbers within filenames

### ISSUE THREAD

**Issue by uazu** [ogham/exa#214]
Sometimes it would be useful to have "9" sorted before "10", and "99" before "100", etc. (Wishlist item)

**Comment by ogham** [comment]
It should be doing this already, thanks to the [natord](https://github.com/lifthrasiir/rust-natord) Rust crate! Give it a go (and let me know if it's not working)

**Comment by uazu** [comment]
Sorry, you're right -- it does work.
