### ISSUE TITLE
Improve building and distributing exa

### ISSUE THREAD

**Issue by dAnjou** [ogham/exa#217]
In order to make it easier for (some) people to build and/or install exa, I propose to make use of Docker for a build container.

Advantages are that people don't have to install yet another build system and builds are reproducible. And you yourself would have a description of the build environment in the repository. Maybe testing could also be done in such a container rather than in a VM. It would be much faster I guess.

Have a look at this [Dockerfile](https://github.com/dAnjou/goup/blob/master/Dockerfile), and this [Makefile](https://github.com/dAnjou/goup/blob/master/Makefile) for how to use the Dockerfile.

**Comment by ogham** [comment]
I have actually had to learn Docker for work in the time since this issue was raised!

But for now I'm going to stick with the Vagrant dev environment.
