### ISSUE TITLE
Provide more packages

### ISSUE THREAD

**Issue by dAnjou** [ogham/exa#218]
[fpm](https://github.com/jordansissel/fpm) provides a rather simple way of creating various kinds of packages.

Have a look at this [Dockerfile](https://github.com/dAnjou/goup/blob/master/Dockerfile) where I make use of it to create a DEB and RPM package.

**Comment by ogham** [comment]
In the (long) time between this issue being raised, Rust has become a more mainstream programming language with other big projects using it, so I'm comfortable letting the exa repo just contain its code, leaving the packaging to the package repositories.
