### ISSUE TITLE
exa is now an official Arch Linux package

### ISSUE THREAD

**Issue by xyproto** [ogham/exa#220]
You may wish to update the instructions on the webpage from:

    yaourt -S exa-git

to:

    pacman -S exa

**Comment by hoodie** [comment]
🎉

**Comment by agauniyal** [comment]
Hi, slightly off-topic but what is the process of adding certain program to archlinux community repo @xyproto ?

**Comment by xyproto** [comment]
@agauniyal There is no process. All it takes is an official Arch Linux person that is willing to move and maintain a package. However, there are implied minimum requirements when it comes to quality, licensing, popularity (AUR votes are taken into account) and good judgement.

**Comment by ariasuni** [comment]
Hi @ogham, do you think you can do this little change on your website?

**Comment by FranklinYu** [comment]
This seems done?

**Comment by sanxiyn** [comment]
Yes, this is done. The website got updated.
