### ISSUE TITLE
Error - Failed to parse number: invalid digit found in string

### ISSUE THREAD

**Issue by aberkow** [ogham/exa#221]
Perhaps it's just Friday morning, but when I try `exa -L=2 -T` I get the error `Failed to parse number: invalid digit found in string`. I also tried the number in combinations with and without quotes and parentheses (just in case). 

However, the following commands work as expected
`
exa --long --tree --level=2
exa --tree --level=2
exa -T --level=2
`

This is on OSX 10.11.6 using both zsh and bash

**Comment by laughedelic** [comment]
I think this is expected behavior: if you use short option name, specify its argument without `=` (with or without space), use `=` only for long option names.

These variants work:

```shell
exa -T -L 2
exa -T -L2
exa -T --level 2
exa -T --level=2
```

**Comment by aberkow** [comment]
That makes sense. Thanks for the clarification. I'll close this and chalk it up to user error!

**Comment by ogham** [comment]
This is now a valid format since exa uses its own option parser. [There's even a test for this very case!](https://github.com/ogham/exa/blob/6759a5f97e9c007cd9bf6f24284fa017f4e65cc4/src/options/dir_action.rs#L95)
