### ISSUE TITLE
suggestion, miller-columns view?

### ISSUE THREAD

**Issue by dobkeratops** [ogham/exa#222]
would there be any sense in an optional [miller-columns](https://en.wikipedia.org/wiki/Miller_columns) style view of multiple directory levels .. it probably doesn't map to CLI so well , but what if you could show the current directory on the right and previous levels in columns working leftward.  
 
 ... or (more clearly) when saying ```ls some/path```, you could show columns of   ```.```, ```./some```, ```./some/path```

**Comment by jdanford** [comment]
I think it makes sense for a CLI program, primarily an interactive one – have you looked at [ranger](https://github.com/ranger/ranger)?

**Comment by dobkeratops** [comment]
yeah ranger is a better use of the concept. maybe we should 'rewrite it in rust' instead .. ( I note 'conrod' has a columns-view filebrowser example aswell..)

**Comment by jdanford** [comment]
Rewrite everything in Rust 🤠

**Comment by notramo** [comment]
One problem with the miller columns view is that *the content of the currently focused directory is displayed on the right side.* In a filebrowser like `ranger` it is ok, but what would be the *currently focused file* in `exa`?

**Comment by ogham** [comment]
Having thought about it a while, this isn’t something I’m going to add at this time.
