### ISSUE TITLE
Hide user with --long

### ISSUE THREAD

**Issue by theduke** [ogham/exa#226]
I'd like to hide the `user` column with `--long` enabled, but there does not seem to be a way to do that?

**Comment by excalibur1234** [comment]
maybe #229 can solve this problem?

**Comment by theduke** [comment]
No, I'd like to hide both the user and the group, but show all the other information as a table.

**Comment by 0rvar** [comment]
I would also like the ability to hide columns. I have no interest at all in Permissions and User
