### ISSUE TITLE
 bin/exa-linux-x86_64: error while loading shared libraries: libhttp_parser.so.2.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by citizinf** [ogham/exa#230]
I mean, it was advertised on the website as self-contained.

**Comment by citizinf** [comment]
I mean,

**Comment by coder543** [comment]
There's already an issue open for this (https://github.com/ogham/exa/issues/203). It's a bug, since obviously it is _meant_ to be self-contained. The author is aware, and working on a fix.

**Comment by citizinf** [comment]
Thanks.

**Comment by jhriv** [comment]
Still true, master branch, 2019-04-11
