### ISSUE TITLE
exa -? doesn't wok in zsh

### ISSUE THREAD

**Issue by Jeshwanth** [ogham/exa#231]
zsh: no matches found: -?

**Comment by coder543** [comment]
> zsh: no matches found: -?

That's your shell complaining. It's not even running `exa`. On Linux/Unix, `-?` isn't a thing, that's a Microsoftism.

whenever `exa` comes to Windows, it will need to support `-?` and `/?` probably.

**Comment by ogham** [comment]
Yeah, `--help` is the Unix way to do help, and `-?` is the Windows way. There's no reason to not include them on both, so they're both *there*, but there is always an easy way to get help.
