### ISSUE TITLE
name collision with x11 component

### ISSUE THREAD

**Issue by citizinf** [ogham/exa#232]
EXA(4)                                                                  EXA(4)

NAME
       exa - new 2D acceleration architecture for X.Org

DESCRIPTION
       EXA  provides a simple API for video drivers to implement for 2D accel-
       eration.  It is a module loaded by drivers, and is not intended  to  be
       loaded  on  its  own.   See your driver’s manual page for how to enable
       EXA.

       The EXA architecture is designed to make accelerating the Render exten-
       sion simple and efficient, and results in various performance tradeoffs
       compared to XAA.  Some xorg.conf options are  available  for  debugging
       performance issues or driver rendering problems.  They are not intended
       for general use.

       Option "EXANoComposite" "boolean"
              Disables acceleration of the Composite operation,  which  is  at
              the heart of the Render extension.  Not related to the Composite
              extension.  Default: No.

       Option "EXANoUploadToScreen" "boolean"
              Disables acceleration of uploading pixmap  data  to  the  frame-
              buffer. Default: No.

       Option "EXANoDownloadFromScreen" "boolean"
              Disables  acceleration  of  downloading  of pixmap data from the
              framebuffer.  NOTE: Not usable with drivers which rely on  Down-
              loadFromScreen succeeding.  Default: No.

       Option "MigrationHeuristic" "anystr"
              Chooses  an  alternate pixmap migration heuristic, for debugging
              purposes.  The default is intended to be the best performing one
              for general use, though others may help with specific use cases.
              Available  options  include  "always",  "greedy",  and  "smart".
              Default: always.

SEE ALSO
       Xorg(1), xorg.conf(5).

AUTHORS
       Authors  include:  Keith  Packard,  Eric Anholt, Zack Rusin, and Michel
       Dänzer

X Version 11                  xorg-server 1.15.0                        EXA(4)

**Comment by citizinf** [comment]
Kind of a dumb issue, you can decide how much you care.

**Comment by ogham** [comment]
This isn't actually the first time this has come up! See #124.

The man page collision shouldn't matter because we're in different groups: exa the file lister is in group 1 (programs), and exa the acceleration architecture is in group 4 (files and file formats).
