### ISSUE TITLE
Read time-style from env $TIME_STYLE

### ISSUE THREAD

**Issue by livelazily** [ogham/exa#236]
I want to set the `long-iso` as default time style, but I don't want to set it every time in the command line. 

Could it read the setting from env or someting config file?

**Comment by ogham** [comment]
I'm currently [in the middle of redoing exa's options module](https://github.com/ogham/exa/tree/option-pars-ng) so I could add this in.

Do you know of any other programs that use the TIME_STYLE env variable?

**Comment by livelazily** [comment]
The gun `ls` using this `$TIME_STYLE` env variable

**Comment by devsnek** [comment]
any word on this? I would open a pr myself but i'm not very good with rust

**Comment by aenda** [comment]
Could there simply be a runtime check that adds the value of $TIME_STYLE, gotten in vars.rs, to MatchedFlags (or whatever the correct spot is) in the parser? Or is this more complicated? Would look into it further but I have little rust experience.
