### ISSUE TITLE
"make install" overwrites permissions on system directories

### ISSUE THREAD

**Issue by erlkonig** [ogham/exa#238]
The installation command should not modify ownership or permissions on system directories (unless it creates them) - only what it puts in them.

Symptom:  make install executes `install -dm755 -- "/usr/local/bin/" "/usr/local/share/man/man1/"` - on our site, the ability to write new files into directories in /usr/local is controlled by group membership, so installing exa broke our ability to install anything else under our normal user accounts.

Side note: The quotes in the install command aren't adequate for certain pathological cases (should be using apostrophes).

Noticed in exa 0.7.0 on Ubuntu 16.04, Rust 1.19.0.

**Comment by ogham** [comment]
Three years later, the Makefile is no longer present in the repository. Because Rust is now a more mainstream programming language, I'd like exa's codebase to only contain the code, leaving the packaging to the package managers.
