### ISSUE TITLE
RFE: Two Important GNU ls Options

### ISSUE THREAD

**Issue by vermaden** [ogham/exa#240]
As replacement it lacks two important options from GNU **ls**:

```
--group-directories-first
--time-style=long-iso

```

Regards,
vermaden

**Comment by therockmandolinist** [comment]
Both of these are available.

`exa -l --time-style=long-iso --group-directories-first` works just fine for me.

**Comment by ogham** [comment]
Yeah, these should both be there — check `exa --help`. Time style was added relatively recently so make sure you're using the latest version.

**Comment by vermaden** [comment]
Not in 0.6 version ...

```
# exa -l --group-directories-first --time-style=long-iso
Unrecognized option: 'time-style'.

# pkg info | grep exa
exa-0.6.0                      Modern replacement for ls
```

... and not in man page for 0.6 ...

```
# man exa | grep group
       whether you are the owner, or in the owning group.  It also has extra
              list each file's group

```

**Comment by ogham** [comment]
`time-style` was added in 0.7 (commit 3251378e91a52616bbbd17958ce19ce9e257db71).

I'm not sure why `grep` doesn't show that item in the man page, but it [*is* there](https://github.com/ogham/exa/blob/master/contrib/man/exa.1#L89,L90)!
