### ISSUE TITLE
Show (via color?) status of child directories that are git repositories

### ISSUE THREAD

**Issue by mqudsi** [ogham/exa#242]
This is probably best illustrated by a concrete usecase example.

I have a directory ~/git/ which is a non-git directory containing all of my git repos. Sometimes I need to make sure that everything has been committed (and pushed) so basically the shell script cds into each subdirectory and does some string parsing to get the status.

Can `exa --git` show some indicator of *repository* status (vs individual file within repository status) to indicate dirty/staged/committed/sync'd?

**Comment by ogham** [comment]
Oh, this actually landed! #24 says it was closed 11 days ago.

You can now use the `--git` option to get the Git status of multiple directories. In this screenshot, I'm querying two repositories, unimaginatively name `git` and `git2`. The first command lists both with `--list-dirs` so it doesn't descend into them, and the second command shows you the contents so you can see where it's getting the `NN` from.

<img width="503" alt="screen shot 2017-09-13 at 22 17 00" src="https://user-images.githubusercontent.com/503760/30401205-4dc252cc-98d1-11e7-92be-90c9c91ff8d5.png">
