### ISSUE TITLE
Fix month name widths once and for all

### ISSUE THREAD

**Issue by ogham** [ogham/exa#244]
#177 fixes the month names for December, which was the longest in Japanese. #239 fixes them for July, which was the longest in French.

To avoid this sort of bug in general, exa should find out the month with the longest name among *all* months, and use the width of that.

**Comment by whuji** [comment]
I did not see the issue in japonese. I have modified the patch to implement the loop over the month names.

**Comment by ogham** [comment]
Closed by #247
