### ISSUE TITLE
Folders first

### ISSUE THREAD

**Issue by JanJastrow** [ogham/exa#245]
Hi there, just stumbled upon exa and tried it, very nice work.
Since I could not find the feature, I would like an option to sort folders as first items in lists.

Similar to gls' option "--group-directories-first"

**Comment by therockmandolinist** [comment]
@JanJastrow see https://github.com/ogham/exa/issues/240

**Comment by JanJastrow** [comment]
Damnit. Thanks for pointing me to that 👍
