### ISSUE TITLE
Native Debian packages

### ISSUE THREAD

**Issue by mhalano** [ogham/exa#246]
I think would be nice have native Debian packages. Would be nicer to have this packages on official repositories. Whenever I don't think a PPA or exclusive repository could be nice because exa is so small and I disagree repositories just for simple applications.

**Comment by nikeee** [comment]
Maybe it would be easier with this:
https://salsa.debian.org/rust-team/debcargo

Found here:
https://wiki.debian.org/Teams/RustPackaging

Also, there is #218. Can we leverage that?

**Comment by FranklinYu** [comment]
Debian has it in [Buster](https://packages.debian.org/buster/exa) and Sid. @ogham Maybe mention it on https://the.exa.website/install/linux?

Ubuntu has it in [Disco Dingo](https://packages.ubuntu.com/disco/exa), but they removed it in Eoan Ermine. I haven't found out why they did this.

**Comment by mhalano** [comment]
Ubuntu will have again on groovy: https://packages.ubuntu.com/groovy/exa

**Comment by mhalano** [comment]
I will close this bug because Groovy's release is quite eminent.
