### ISSUE TITLE
Permission denied (os error 13)

### ISSUE THREAD

**Issue by steven-tan** [ogham/exa#257]
This may be something unique to my mac, as I'm surprised to not see it here already...  (though I tend to keep my mac installs pretty vanilla).

I put exa on my mac (just dropped int into /usr/bin) and if I do an exa -l, on certain hdden files (for example .Trashes) I see:

<Permission denied (os error 13)>

For a partial listing, example:

d-wx-wx-wt    - root 14 Dec  2016 .Trashes
                                  └── <Permission denied (os error 13)>
srwxrwxrwx    0 root  7 Aug  9:27 .dbfseventsd
.---------    0 root 25 Feb  2016 .file
                                  └── <Permission denied (os error 13)>
drwx------    - root  7 Aug 11:55 .fseventsd
                                  └── <Permission denied (os error 13)>
drwxr-xr-x@   - root  1 Aug  2015 .vol
drwxrwxr-x    - root 24 Jul 12:37 Applications
drwxr-xr-x    - root 11 Jan  9:43 Library
drwxr-xr-x@   - root 21 Jul 14:00 Network
drwxr-xr-x    - root 26 Apr 15:03 System

**Comment by ogham** [comment]
Hi, I think this is the same bug as #178. I'm not sure what OS error 13 is, but the .Trashes folder on a Mac is inaccessible with ls too:

  $ ls /.Trashes/
  ls: : Permission denied

The reason you're seeing this in `--long` mode is that it's trying to query the extended attribute status of the directory, which is something it does for every file. This is going to be changed in the next release so the error doesn't appear when you don't specifically ask for the attributes.

**Comment by steven-tan** [comment]
Thank you @ogham
