### ISSUE TITLE
Overflow on UID > 2^31

### ISSUE THREAD

**Issue by bdejean** [ogham/exa#26]
Hello,

When file UID is > 2^31, the displayed UID wraps around and is displayed as negative. This issue probably also happens with big BIG.

    #Mon Feb 23 11:26:44 $ ls -la a b c
    -rw-r--r-- 1 2147483647 xxx 0 Feb 23 11:26 a
    -rw-r--r-- 1 2147483648 xxx 0 Feb 23 11:26 b
    -rw-r--r-- 1 2147483649 xxx 0 Feb 23 11:26 c

    #Mon Feb 23 11:26:48 $ exa -la a b c
    .rw-r--r-- 0 2147483647  23 Feb 10:26 a
    .rw-r--r-- 0 -2147483648 23 Feb 10:26 b
    .rw-r--r-- 0 -2147483647 23 Feb 10:26 c

**Comment by ogham** [comment]
Sorry, what do you mean by "big BIG"?

**Comment by bdejean** [comment]
Oops, I meant GID.

**Comment by bdejean** [comment]
I don't know Rust but I can see this:

    self.stat.unstable.uid as i32;
    [...]
    let gid = self.stat.unstable.gid as u32;

Isn't the whole issue about uid/gid being narrowed to a signed-type ?

**Comment by ogham** [comment]
There doesn't seem to be any guarantee about the size of `uid_t` and `gid_t` across different systems. Rust's libc crate makes them 32 bits long, and Rust forces you to convert the type of the number (with `as`). I changed it so the number that gets displayed doesn't get converted to 32-bit, as it was before.
