### ISSUE TITLE
Documentation of output colors and styles

### ISSUE THREAD

**Issue by alekratz** [ogham/exa#261]
I love exa! One new feature I noticed is that, in project directories, `Cargo.toml` and `README`/`README.md` are being highlighted yellow with an underline. I'm not entirely sure what this means; it would be awesome if the manpage could be updated with an explanation of what all of the colors and text styles indicate.

**Comment by stumpylog** [comment]
I agree that this information would be helpful to have documented.  I think from reading the source in https://github.com/ogham/exa/blob/master/src/output/colours.rs, this documentation could be derived.  Except I'm not sure a) where documentation should go and b) what some of the file types are.

For example, the `Cargo.toml` seems likely to map to the `immediate:   Yellow.bold().underline()` style, but what is that file type?

**Comment by hoodie** [comment]
perhaps exa could even print a color chart of some sort, that should be relatively easy to do. Something like `exa --help-colors` that just prints each color and what it means. That also allows you to see the colors in context, since some terminals temper with the colors.

**Comment by ogham** [comment]
I've [added some documentation to the man page](https://github.com/ogham/exa/commit/d4bbfb39f037daf123cd6139f5ffaac01e039758) that says what the colours mean, how to customise them, and how to turn them off.

**Comment by vii33** [comment]
I took @ogham 's notes and put them into a proper markdown format: https://github.com/ogham/exa/blob/c1c88dbbf30da4fbf7b3c98fe8cd545961edda60/man/exa-colors-explanation.md

Hopefully this helps.

Great peace of software by the way 👍
