### ISSUE TITLE
--tree overrides --git

### ISSUE THREAD

**Issue by nyarly** [ogham/exa#262]
`exa --git` triggers the misfire code ("useless without --long") but `exa --git --tree` runs, but doesn't provide git information.

I'd love to see a git column in tree view, but at least a misfire case for git+tree would be nice.

**Comment by sam-untapt** [comment]
Agreed - some way of seeing git status in the tree would be awesome.

**Comment by ogham** [comment]
This landed at the start of the month and I forgot to update this issue! See #24, which includes screenshots at the bottom.

**Comment by nyarly** [comment]
Awesome! Is there going to be a release soon with this included? (Most recent appears to be 0.7.0)
