### ISSUE TITLE
Not on crates.io? Why?

### ISSUE THREAD

**Issue by vi** [ogham/exa#263]
```
$ cargo install exa
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: could not find `exa` in `registry https://github.com/rust-lang/crates.io-index`
```

**Comment by hoodie** [comment]
patience young padawan 
#132

**Comment by ogham** [comment]
The author of the rust-datetime library is a real slacker.

**Comment by vi** [comment]
Just fork & publish (under another name like `exa-datetime`). When original `rust-datetime` gets published, switch to it.
