### ISSUE TITLE
`exa -l --git` very slow

### ISSUE THREAD

**Issue by vi** [ogham/exa#265]
Hot cache:

```
$ time git status > /dev/null

real	0m0.010s
user	0m0.000s
sys	0m0.000s

$ time exa --git -l > /dev/null

real	0m1.403s
user	0m2.150s
sys	0m0.710s

$ strace -c exa --git -l  > /dev/null
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 48.29    0.003549           0     41853           getdents
 19.82    0.001457           0     81348     20935 stat
 14.46    0.001063           0     60690           lstat
  5.21    0.000383           0     20935     20926 access
  5.05    0.000371           0     20992           close
  4.78    0.000351           0     21005        13 open
  2.39    0.000176           0     20965           fstat
  0.00    0.000000           0        43           read
...
```

Feels like a quadratic complexity somewhere - something should be cached.

**Comment by drew-gross** [comment]
I also had to remove `--git` from my alias. This is partly because I work in a remotely mounted repo sometimes, and all git operations are slow. Is is possible to make a timeout for git operations so that I can continue getting the benefits from `--git` flag while in local git repos without having to change the way I work in remote mounted repos?

**Comment by I60R** [comment]
```
cd ~
git init
exa -l --git # <— runs forever
```

**Comment by ariasuni** [comment]
@drew-gross I think that’s really too complex for too little gain. You can write a script to run exa with `--git` only when you’re on a remote repository. (I know it’s probably not relevant anymore, but I’m triaging old issues)

@I60R Is it really running «forever»? Please open a new issue if that’s the case with latest version.

Closing this in favor of #28.
