### ISSUE TITLE
Help message about sorting is unhelpful.

### ISSUE THREAD

**Issue by vi** [ogham/exa#266]
In usual `ls` it is `-S`.

**Comment by vi** [comment]
Found: `exa -ssize`. But help looks broken:

```
$ exa --help
...
  -r, --reverse              reverse the sort order
  -s, --sort SORT_FIELD      which field to sort by:
  --group-directories-first  list directories before other files
...
```

**Comment by jdanford** [comment]
Are you using the newest version of `exa`? `exa -s` returns `Argument to option 's' missing.` for me. Anyway, it's documented in the main help, but for some reason it's not immediately after the `-s` flag:
```
FILTERING AND SORTING OPTIONS
  -a, --all                  show hidden and 'dot' files
  -d, --list-dirs            list directories like regular files
  -r, --reverse              reverse the sort order
  -s, --sort SORT_FIELD      which field to sort by:
  --group-directories-first  list directories before other files
  -I, --ignore-glob GLOBS    glob patterns (pipe-separated) of files to ignore
  Valid sort fields:         name, Name, extension, Extension, size, type,
                             modified, accessed, created, inode, none
```

**Comment by vi** [comment]
> `which field to sort by:`

And what's after the colon?

**Comment by jdanford** [comment]
You're looking at it – two other options, and then the sort fields.
```
  --group-directories-first  list directories before other files
  -I, --ignore-glob GLOBS    glob patterns (pipe-separated) of files to ignore
  Valid sort fields:         name, Name, extension, Extension, size, type,
                             modified, accessed, created, inode, none
```

**Comment by vi** [comment]
Only now I see.

Those fields should be directly after `by:`. Or text should be `which field to sort by (see below)`.

**Comment by ogham** [comment]
You’re right, there is an extra colon there. I never noticed!

It’s there because originally the sort fields were listed right by the option in the help. But there soon got too many fields to list, so [I moved them to the end](https://github.com/ogham/exa/commit/e2f73927c7c8169ef279501e4636e1671d7820fd#diff-2f92e5c123d1651ba451507cc8ab6a56R21) where I hoped they would be close enough that people would see them. The colon got left behind.

**Comment by ogham** [comment]
Colon is now gone. Do you think I need to put something like “(see below)” in there as well?

**Comment by vi** [comment]
Maybe. I've noticed the `Valid sort fields:` only after being explicitly pointed to.

**Comment by dieggsy** [comment]
Another option would be to leave the colon and indent the fields? This would be the clearest IMO

**Comment by vi** [comment]
Don't understand about indenting the fields. There should be no unrelated content between the colon (a list opener) and sort fields (list items), otherwise the colon should not be used.

**Comment by dieggsy** [comment]
I mean to put the list of fields directly below the line with the colon, indented to indicate that it pertains to the above line.
