### ISSUE TITLE
Feature idea: colorize timestamp based on recency.

### ISSUE THREAD

**Issue by vi** [ogham/exa#267]
Should be some heuristic algorithm.

Now all timestamps are displayed in blue. The colour should give idea of freshly updated file.

Example of a colour scheme:

* Blue - main block of timestamps.
* Red - changed or created in recent hour.
* Green - changed or created in recent year.

There may be option to disable such additional colouring, but implementing a flexible adjustment is probably an overkill.

**Comment by jdanford** [comment]
The color range isn't as large, but take a look at #253.

**Comment by novoid** [comment]
Hi!

I do have a similar approach: https://github.com/novoid/vkl/blob/master/README.org

It'd be great if exa could visualize the files by logarithmic date as shown in my screenshot/tool.

Additionally (or instead), those different time slots could be visualized (in the date-column only?) using different contrast of colors: older files tend to get lower contrast foreground/background combinations.

This would be awesome!

**Comment by lilyball** [comment]
This looks like a dupe of #233.

**Comment by ogham** [comment]
I will track this in #233
