### ISSUE TITLE
Idea for better file mode colouring.

### ISSUE THREAD

**Issue by vi** [ogham/exa#268]
* Owner-writable is bold red, unlike group- and others-writable. Should be the reverse.
* Suid-bit should be bold red, not faint violet. Username (groupname) may also be shown as bold red when suid or sgid bit is set.
* Maybe usual boring uninteresting `rw-r--r--` bits should be dull gray, but `-`s of their omissions should be more visible.
* All file type indicators except of `.` regular file, `d` directory and `l` symlink may be bold.
* `.` of a regular file may be bolder or coloured if it is known that nlinks > 1. Or filesize can be shown blue instead of green in this case.

**Comment by ogham** [comment]
I think it's too late to change how exa looks in general, as the pattern of the colours is seared into my memory at this point (and I'm pretty sure this is the case for others, too).

I do understand the logic behind these choices, though. If you're looking for "unusual" file setups, highlighting the choices you don't see very often and using red to mean "danger" is a good choice. However, I want to refrain from having exa... for lack of a better word, "moralise" the data on the filesystem. I want it to be a file lister and metadata viewer, not a "something wrong" viewer; I don't want it to make judgement calls on what's on disk. There are times where I've broken this rule (like multi-hard-link files) but in general I want to keep to it.

Hopefully in the future, theming support will expand to allow a lot of these possibilities.
