### ISSUE TITLE
Value-dependent colouring of file size.

### ISSUE THREAD

**Issue by vi** [ogham/exa#269]
In additional to the appropriate suffixes, colour may indicate order of file size.

* < 1000 => pale gray
* kilobytes => green
* megabytes => blue (or maybe also green)
* gigabytes => bold black
* terabytes and more => bold red

**Comment by ogham** [comment]
There’s an option for this: `--color-scale` or `--colour-scale` (either work). Unfortunately you can’t get those *exact* colours yet. They’re pre-defined until customisable colours lands, which is being tracked in #160.
