### ISSUE TITLE
Idea: compressed "ago" dates

### ISSUE THREAD

**Issue by vi** [ogham/exa#270]
Dates like `16 Jun  2016` occupy reasonable screen space and requires mental parcing to determine how long ago it was.

In compressed dates mode it should be short and relative to current datetime:

* Within 30 seconds of now => <tt> NOW </tt> (in red)
* less than 60 minutes => `XXmin`
* less than 24 hours => `XXhrs`
* less than 32 days => `XXday`
* less than 12 months => `XXmon` (maybe other colour starts here)
* ... => `Xyear`
* more than 9 years => <tt> OLD </tt> (bold?)
* zero UNIX time => <tt> --- </tt> (pale gray)

**Comment by jdanford** [comment]
I love [timeago](https://github.com/rmm5t/jquery-timeago], so I would appreciate this feature. Do you know of an existing fuzzy timestamp library for Rust? I can't seem to find anything on Google.

**Comment by vi** [comment]
Existing fuzzy timestamp will unlikely be short and fixed width.

We can develop such a library (only displaying, no parsing), it shouldn't be too hard.

**Comment by jdanford** [comment]
Good point! Are you interested in implementing this yourself, or do you want to leave that to someone else? I'd be happy to, assuming @ogham is okay with the general idea.

**Comment by vi** [comment]
Quickly hacked up a crate: [timeago](https://crates.io/crates/timeago)

**Comment by timofonic** [comment]
@vi @jdanford Thanks! This looks very nice!

@ogham What do you think about this?

**Comment by vlnx** [comment]
https://gist.github.com/vlnx/6cb393d73eda0294076a3af8ca2443ee

**Comment by vi** [comment]
@vlnx , Is my `timeago` create not fit for this job? Should something from that patch be factored into it?

**Comment by vlnx** [comment]
I'm just new to rust and wanted to modify it more than pulling in a new package.

**Comment by notramo** [comment]
Cool idea, but I think, if something is older than 9 year, it should display the date itself instead of `OLD`.

**Comment by alivefromupstairs** [comment]
+1 
![image](https://user-images.githubusercontent.com/46059092/69165746-5acd7880-0af2-11ea-84ed-bbd1a85ba8a3.png)

**Comment by planet36** [comment]
[lsd](https://github.com/Peltoche/lsd) uses [chrono_humanize](https://lib.rs/crates/chrono-humanize).

**Comment by im-n1** [comment]
This is the one and only thing that keeps me to stick with `lsd`.

**Comment by sherifabdlnaby** [comment]
This is the one and only thing that makes me use `lsd` too !

**Comment by syphar** [comment]
I created a first PR for this feature: https://github.com/ogham/exa/pull/1061

**Comment by ariasuni** [comment]
Closing this, since exa is unmaintained (see https://github.com/ogham/exa/issues/1243), and this has been done in [the active fork eza](https://github.com/eza-community/eza). Thanks!
