### ISSUE TITLE
Git + Recurse -> no git info in subfolders

### ISSUE THREAD

**Issue by whuji** [ogham/exa#275]
If --git with -R, the git column does not exist for subfolders :

`
#exa --group-directories-first -l -h -g --git -R
Permissions Size User Group Date Modified  Git Name
drwxr-xr-x     - huji huji  31 août  13:27  -- bin
drwxr-xr-x     - huji huji  30 août  11:59  -- pack
drwxr-xr-x     - huji huji  30 août  11:59  -M python
drwxr-xr-x     - huji huji  31 août  15:09  -- tmp
.rw-r--r--   540 huji huji  30 août  18:33  -- CHANGELOG
.rw-r--r--  1,4k huji huji  30 août  18:33  -- CMakeLists.txt
.rw-r--r--    99 huji huji  30 août  11:59  -- INSTALL
.rw-r--r--   213 huji huji  30 août  17:10  -- ecScripts.cfg
.rwxr-xr-x  1,1k huji huji  31 août  14:34  -M ecTest.py
.rwxr-xr-x   205 huji huji  30 août  12:02  -- git_log_to_changeLog.sh
.rwxr-xr-x  4,1k huji huji  30 août  11:56  -- test.py

[...]

./python:
Permissions Size User Group Date Modified  Name
drwxr-xr-x     - huji huji  31 août  15:14 ec

./python/ec:
Permissions Size User Group Date Modified  Name
drwxr-xr-x     - huji huji  31 août  15:14 __pycache__
.rw-r--r--    64 huji huji  30 août  11:59 __init__.py
.rw-r--r--  2,4k huji huji  30 août  23:31 api.py
.rw-r--r--  1,7k huji huji  31 août   1:23 api_vapp.py
.rw-r--r--  7,0k huji huji  31 août  12:28 api_vdc.py
.rw-r--r--  6,3k huji huji  31 août  15:14 api_vm.py
.rw-r--r--   902 huji huji  30 août  12:26 errors.py
.rw-r--r--  3,4k huji huji  31 août  15:13 helpers.py
[...]
`

**Comment by ogham** [comment]
This is one of the oldest issues — #24.

Fortunately, it's almost there!
