### ISSUE TITLE
exa freezes with no internet connection

### ISSUE THREAD

**Issue by sgtnasty** [ogham/exa#276]
Lost wifi on macOS, ran exa in iTerm2 and it just halts until the wifi came back on.

`Darwin diemos.fios-router.home 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64`

**Comment by hoodie** [comment]
thank you, can you reproduce this with a `--no-default-features` build?

**Comment by ogham** [comment]
Thanks for the bug report — this is very weird. I have no internet connection 90% of the time (on macOS) so this definitely shouldn't be happening.

Do you still have the exact command that you ran? Or did it halt for any command?

**Comment by sgtnasty** [comment]
Wish they notified me of these questions! I had no idea you guys responded. Will try the `--no-default-features` sometime today, must get work done first.

**Comment by sgtnasty** [comment]
I was not able to reproduce this issue. I rebooted my MacBook, turned off wireless and exa worked as expected. No idea what the issue was at the time, however it may have had nothing to do with exa.
