### ISSUE TITLE
race condition in make install

### ISSUE THREAD

**Issue by deep-42-thought** [ogham/exa#277]
There is a race condition in `make install`:

-  target `intall-man` creates directory `/usr/bin`
-  `install-exa` will fail if `/usr/bin` is not created yet
-  `install` lists `install-exa install-man` - e.g. it only succeeds if -j2 or lager is given and `target/release/exa`, a dependency of `install-exa` takes some time

I propose to add `-D` and `-t` to the `install` instruction in target `install-exa`:

```
--- Makefile	2017-08-20 21:04:59.000000000 +0200
+++ Makefile	2017-09-01 15:13:46.485601615 +0200
@@ -23,7 +23,7 @@
 install: install-exa install-man
 
 install-exa: target/release/exa
-	install -m755 -- target/release/exa "$(DESTDIR)$(PREFIX)/bin/"
+	install -Dm755 -t "$(DESTDIR)$(PREFIX)/bin" -- target/release/exa
 
 install-man:
 	install -dm755 -- "$(DESTDIR)$(PREFIX)/bin/" "$(DESTDIR)$(PREFIX)/share/man/man1/"
```

**Comment by ogham** [comment]
Thanks for this; I forgot that Make could run in parallel.

The `-D` flag looked familiar and in a past commit (9eac99cfd85c368ba88306f8f9af89e6ac6c605e) it was removed in favour of a more portable version. Do you know if there's a more portable way to achieve this?

**Comment by deep-42-thought** [comment]
I pretty much only know linux, but there is also `-d` to solely create the directory, which seems to be portable:
https://trac.kodi.tv/ticket/10351

**Comment by ogham** [comment]
Three years later, the Makefile is no more, so I'm closing this. Now that Rust is a more mainstream language, I don't want exa to have to include installation instructions for itself that could apply to _every_ platform.
