### ISSUE TITLE
directories are `Blue.normal()`

### ISSUE THREAD

**Issue by hoodie** [ogham/exa#278]
on the current master, directories aren't `Blue.bold()` but `.normal`. I tried to reduce the problem, setting `FileKinds::directory` to `Red.bold()` didn't turn them red, so I assume  the matching to `directory` is wrong. Or could this mapping be overridden somewhere else?

**Comment by ogham** [comment]
Do you have `LS_COLORS` set?

**Comment by hoodie** [comment]
ah, yes it is, and when I unset it suddenly exa looks like expected
thank you
