### ISSUE TITLE
Binary is not self contained?

### ISSUE THREAD

**Issue by gdetrez** [ogham/exa#285]
According to the download section of the site, the binary doesn't have dependency but here's what happens when I tried to execute it on Fedora 25:
```
❯❯❯ ./exa-linux-x86_64
./exa-linux-x86_64: error while loading shared libraries: libhttp_parser.so.2.1: cannot open shared object file: No such file or directory
```
It looks like exa need the http-parser library version 2.1 to be installed, is that correct?
(I tried installing the `http-parser` package from the distribution but the available version is 2.7.1)

**Comment by mqudsi** [comment]
Under Ubuntu this does not seem to be the case when compiling from git:

```
mqudsi@Blitzkrieg /m/d/GIT> ldd (which exa)
        linux-vdso.so.1 =>  (0x00007ffff55ff000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f5d54f20000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f5d54d10000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f5d54b00000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f5d548e0000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f5d546c0000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5d542e0000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f5d55600000)
```

What's your ldd output?

**Comment by ogham** [comment]
See #194. Lots of people hit this issue :(

Basically a dependency snuck in via libgit2, and even though that library's network functionality isn't being used, the OS still complains. I've already hacked the build script to not link this in, so the next release's binaries won't have this problem.
