### ISSUE TITLE
Unable to install backtrace-sys if using exa.

### ISSUE THREAD

**Issue by Deedasmi** [ogham/exa#286]
I replaced `ls` with `exa` on my fedora 26 laptop, and am trying to compile Redox. While installing xargo as a dependency, I ran into an issue where the build fails on this error: https://github.com/alexcrichton/backtrace-rs/blob/2f4fd762d973a53634933672e2e3a0f80a54d99c/backtrace-sys/src/libbacktrace/aclocal.m4#L493

Because of the changes to the options, exa doesn't pass this check and the build fails.

Also making an issue over there, just trying to open communication between you two.

**Comment by ogham** [comment]
Did you replace the ls binary with an exa binary called ls? If so, this won't work! exa is deliberately backwards-incompatible in a few places, and while that build script uses `-L` to mean `--dereference`, exa understands `-L` to mean `--level`.

Hopefully one day, exa will be able to tell if it's been invoked with `ls` as the binary name, and switch to a different set of options. But even then I wouldn't recommend replacing the binary until it's been thoroughly tested: there are enough versions of ls with different featuresets floating around that there are going to be edge cases here and there too. In the meantime, I recommend putting `ls` back, and using your shell to alias it instead.
