### ISSUE TITLE
Terminal themes used in screenshots?

### ISSUE THREAD

**Issue by mqudsi** [ogham/exa#291]
@ogham just a question: what themes are you using in the exa screenshots?

**Comment by dieggsy** [comment]
Ooh, and font

**Comment by ogham** [comment]
The font is either PragmataPro (commercial) or Iosevka (free), can't remember which.

The themes began as Tomorrow Dark and Solarized Light. I've slowly modified them over the years so they're not *exactly* the same, but they're both good themes!

**Comment by dieggsy** [comment]
@ogham Never really thought to look at the zeros but now that I have, that definitely seems like PragmataPro. Thanks! 

I love Iosevka and have made it my go-to monospace font recently anyway, and they are sorta similar.
