### ISSUE TITLE
the.exa.website https cert expired

### ISSUE THREAD

**Issue by michaeljwilliams** [ogham/exa#299]
The site is inaccessible.

**Comment by jdanford** [comment]
See [this comment](https://github.com/ogham/exa/commit/877265bf4e8f4c42afcab231e89ee4a83fe1409b#commitcomment-24685934) for an explanation.

**Comment by ogham** [comment]
It's up again now. I found my keys!

Also, today is the day I find out that [Pingdom doesn't do SSL expiration tracking](https://help.pingdom.com/hc/en-us/community/posts/207215955-Create-an-alert-function-for-SSL-expiration-tracking) :(
