### ISSUE TITLE
Question: `cargo install --git URL` vs `cargo install exa`

### ISSUE THREAD

**Issue by infokiller** [ogham/exa#303]
Hey, I'm not too familiar with ruse/cargo so apologies in advance for a stupid question.

What is the difference when installing it directly with `cargo install --git https://github.com/ogham/exa` (as suggested in the readme), vs just using `cargo install exa`?

If I understand correctly, the latter will install it from [crates.io](https://crates.io/crates/exa) which looks to have the latest version.

What is the best way to install this package going forward? direct git url or using the crate name?

Thanks!

**Comment by hoodie** [comment]
`cargo install --git https://github.com/ogham/exa` installs the latest master, `cargo install exa` installs the latest version published to crates.io. For an everyday user you should go with the latest stable release, therefore via crates.io

**Comment by infokiller** [comment]
Thanks! so should the instructions in the README change to suggest using the crates.io version?

**Comment by ogham** [comment]
The readme is updated now! #302.
