### ISSUE TITLE
Error when trying to build using --target x86_64-unknown-linux-musl

### ISSUE THREAD

**Issue by kaushalmodi** [ogham/exa#305]
Hello,

I was trying to build a static binary of `exa` using the same recipe I use for other rust projects `ripgrep` and `tokei`.

```
rustup target add x86_64-unknown-linux-musl
RUSTFLAGS="-C target-cpu=native" rustup run stable cargo build --target x86_64-unknown-linux-musl --release
```

But when running the same commands for building `exa` (latest from the `master` branch), I get this error:

```
error: failed to run custom build command for `libz-sys v1.0.16`
process didn't exit successfully: `/home/kmodi/downloads/git/exa/target/release/build/libz-sys-357d9442626160c6/build-script-build` (exit code: 1)
--- stdout
OPT_LEVEL = Some("3")
TARGET = Some("x86_64-unknown-linux-musl")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-musl")
TARGET = Some("x86_64-unknown-linux-musl")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-musl = None
CC_x86_64_unknown_linux_musl = None
TARGET_CC = None
CC = None
HOST = Some("x86_64-unknown-linux-gnu")
CROSS_COMPILE = None
TARGET = Some("x86_64-unknown-linux-musl")
HOST = Some("x86_64-unknown-linux-gnu")
CFLAGS_x86_64-unknown-linux-musl = None
CFLAGS_x86_64_unknown_linux_musl = None
TARGET_CFLAGS = None
CFLAGS = None
DEBUG = Some("false")
running: "./configure" "--prefix=/home/kmodi/downloads/git/exa/target/x86_64-unknown-linux-musl/release/build/libz-sys-cb6406bfa3ab86da/out"
Compiler error reporting is too harsh for ./configure (perhaps remove -Werror).
** ./configure aborting.


command did not execute successfully, got: exit code: 1
```

Does that error help you figure out the problem?

## Version info

> rustup --version                                                                                                                                                                         
> rustup 1.6.0 (a11c01e8c 2017-08-30)

> rustc --version                                                                                                                                                                          
> rustc 1.20.0 (f3d6973f4 2017-08-27)

**Comment by ogham** [comment]
I'm afraid I'm not sure what this was, but musl builds are now available for download.
