### ISSUE TITLE
Add emacs dired support

### ISSUE THREAD

**Issue by amosbird** [ogham/exa#306]
This would be a wonderful feature.

**Comment by gopar** [comment]
When was this completed? Reference git commit?

**Comment by ariasuni** [comment]
I don’t think it has been implemented, but to reopen this issue, it would need to have a better title because «emacs dired support» doesn’t make a lot of sense to me, especially since I don’t know anything about Emacs.

**Comment by gopar** [comment]
Yea, the title alone doesn't give much background

I opened a new ticket w/ more info: https://github.com/ogham/exa/issues/1143

**Comment by jnordwick** [comment]
> I don’t think it has been implemented, but to reopen this issue, it would need to have a better title because «emacs dired support» doesn’t make a lot of sense to me, especially since I don’t know anything about Emacs.

wow. thats quite an atitude inatead of looking it up or just closing as not enough info and saying you dont know in the remarks. damn. the way you did it was like a giant middle finger to the requester.

**Comment by jnordwick** [comment]
then you can say we don't have time. blah blah blah. just going I don't
know what it is kill it is so horrible. this isn't about them not choosing
not to support it it's about the response that's given and the reasons why
they won't support .

**Comment by daviessm** [comment]
> just going I don't know what it is kill it is so horrible. this isn't about them not choosing not to support it it's about the response that's given and the reasons why they won't support .

The issue was closed by the person who originally raised the request five years before the comment you're complaining about. Saying you can't reopen a request because you don't know what it means is entirely reasonable. As you can see, a new request which explained the request much better had already been opened before you commented.
