### ISSUE TITLE
Support dircolors

### ISSUE THREAD

**Issue by pickfire** [ogham/exa#308]
https://github.com/trapd00r/LS_COLORS/issues/80

**Comment by maximbaz** [comment]
It seems to be working for me without any issues:

![image](https://user-images.githubusercontent.com/1177900/35255097-9ed4c4e6-ffed-11e7-91da-088b73b3acdf.png)

**Comment by pickfire** [comment]
@maximbaz Well, exa can have more colors than which dircolors provides.

**Comment by maximbaz** [comment]
The issue has no description whatsoever, I thought it means that you cannot get trapd00r/LS_COLORS to work with exa, so I shared that it works for me :)

Since that's not the issue, I suggest to add at least some description to explain what the problem is then.

**Comment by dieggsy** [comment]
If exa has more colors than dircolors provides, I'm not sure I see what there is to do on exa's side?

**Comment by pickfire** [comment]
@dieggsy But @rpdelaney call for exa to support  LS_COLORS. https://github.com/trapd00r/LS_COLORS/issues/80#issuecomment-338007702

**Comment by dieggsy** [comment]
@pickfire you're not explaining yourself very well, I still don't understand what exactly the problem is. What is the current behavior/interaction between LS_COLORS and exa and what is the desired behavior?

**Comment by pickfire** [comment]
@dieggsy Currently there is no interaction between LS_COLORS and exa.

It is desireable to be able to use more colors set with LS_COLORS.

**Comment by maximbaz** [comment]
But that's not true, the screenshot above shows exa interacting with trapd00r/LS_COLORS.

**Comment by pickfire** [comment]
@maximbaz But doesn't exa support colors like the one for git.

**Comment by maximbaz** [comment]
Can you show an example with pictures? Like, a comparison between `ls` and `exa`, so we can see what is expected result and what is actual behavior.

**Comment by pickfire** [comment]
@maximbaz I don't have example for one yet. But the man page shows a part where LS_COLORS and EXA_COLORS differs where exa can color the execution bits, users and almost everything.

Maybe this issue is invalid since LS_COLORS is meant for LS_COLORS and not EXA_COLORS?

**Comment by dieggsy** [comment]
> But doesn't exa support colors like the one for git.

@pickfire what was your point here? @maximbaz says LS_COLORS works for exa. If your point is that exa supports _more_ colors/filetypes than LS_COLORS supports, I don't see the issue. If the point is that LS_COLORS supports filetypes/colors that don't show using exa, then I can start to understand.

**Comment by pickfire** [comment]
I guess my point is that exa supports *more* colors/filetypes than LS_COLORS supports.

**Comment by maximbaz** [comment]
I believe I'm getting something, let's get things straight - trapd00r/LS_COLORS is a project aimed to colorize file types via LS_COLORS, it is not meant to modify EXA_COLORS in any way. 

If I understood correctly, you want a "custom theme" that is using EXA_COLORS to colorize other parts of exa _besides file types_ - this is definitely something out of scope for trapd00r/LS_COLORS.

**Comment by pickfire** [comment]
Yeah, that's what I thought but I just feel like it's out of the topic for both exa and LS_COLORS.
