### ISSUE TITLE
Feature request: show file permissions numerically

### ISSUE THREAD

**Issue by flip111** [ogham/exa#316]
Adding the chmod number to the detailed info list would be nice. Same as `stat --format '%a' <file>` can output

**Comment by ogham** [comment]
Good idea! I'm thinking `--octal-permissions` for an argument to switch it on.

**Comment by TonioGela** [comment]
Any update?

**Comment by TonioGela** [comment]
Still no updates on that?

**Comment by flip111** [comment]
@ogham where in the code should this be added ?

**Comment by derEisele** [comment]
Any update?

**Comment by mckenziewagner** [comment]
yeet!

**Comment by comfortablynick** [comment]
I would love this feature! I have a little shell function for this that I picked up somewhere, but it would be great to have integrated with exa.

```awk
ls -l "$@" | awk '{k=0;for(i=0;i<=8;i++)k+=((substr($1,i+2,1)~/[rwx]/)*2^(8-i));if(k)printf(" %0o ",k);print}';
```

**Comment by TonioGela** [comment]
So we will receive it in a new release?
