### ISSUE TITLE
`watch --color` still loses colors.

### ISSUE THREAD

**Issue by nick-laird** [ogham/exa#321]
I cannot seem to make exa work with colors when using watch. I've tried a few different permutations of switches both for exa and watch. `watch --color "exa -lh --color=always"` doesn't work for example. 

`watch from procps-ng 3.3.12`
`exa v0.8.0`

**Comment by ogham** [comment]
I downloaded `watch` onto the Ubuntu VM and annoyingly it worked for me. Using `watch from procps-ng 3.3.10`, the colours appeared when `--color=always` was provided.

Shot in the dark: what's your `$TERM`?

**Comment by nick-laird** [comment]
TERM="xterm-256color"

**Comment by Don42** [comment]
Just for reference. I tested the colors on Debian with urxvt and zsh.
TERM="rxvt-unicode-256"
`watch --color exa --color always` prints colors for both version 0.8.0 and version 0.9.0-pre (0eb7966) on rust 1.23.0.
Maybe this helps isolating the issue.

**Comment by filalex77** [comment]
Tested on Gentoo.
`exa v0.8.0`
`watch from procps-ng 3.3.15`
`TERM=xterm-kitty`

Works as expected.
