### ISSUE TITLE
Incorrect display of unknown utf-8 string `\u{xx}`, should be ''$'\xx'

### ISSUE THREAD

**Issue by cathay4t** [ogham/exa#341]
If a file contains invalid utf-8 character, `exa` will show it a `\u{xx}`. That's not the format `rm` is using.

```bash
[fge@Gris-Laptop test]$ touch `printf '\x1b'`
[fge@Gris-Laptop test]$ exa
\u{1b}
[fge@Gris-Laptop test]$ rm \u{1b}
rm: cannot remove 'u{1b}': No such file or directory
[fge@Gris-Laptop test]$ /usr/bin/ls 
''$'\033'
[fge@Gris-Laptop test]$ rm ''$'\033'
```
In above example, the `\033` is octonary。

**Comment by darkwater** [comment]
That's not the format `rm` is using either, it just receives a `\x1b` byte as argument. It's bash that interprets the `$'\033'` and sends the byte to `rm`. `ls` just outputs in the same format since recently. (Not really commenting on whether exa should change this, just wanted to clear things up)

**Comment by ogham** [comment]
Yeah, I don’t think there’s a standard to follow here. Your `rm` certainly escapes characters better than mine:

<img width="162" alt="screenshot 2018-12-07 at 09 46 35" src="https://user-images.githubusercontent.com/503760/49640293-20fc8280-fa05-11e8-9223-2b65bbf816d9.png">
