### ISSUE TITLE
Can you also highlight lowercased `readme.md` files?

### ISSUE THREAD

**Issue by nikitavoloboev** [ogham/exa#346]
`exa` highlights in yellow files like `README.md`. But it doesn't highlight `readme.md` file (when it is lowercased).

Is it possible to add support for it too?

**Comment by joshleeb** [comment]
I think this would be nice. I often see projects with lowercase `readme.*` files.
I'll put up a quick PR for this.

**Comment by ogham** [comment]
(Looks like this didn’t auto-close)
