### ISSUE TITLE
exa support for directory indicators

### ISSUE THREAD

**Issue by JoshuaRLi** [ogham/exa#348]
Is there functionality for a directory indicator similar to what `ls` has? In `ls(1)`:

```
-p, --indicator-style=slash
    append / indicator to directories
```

I wasn't able to find anything in exa's man page. If this really isn't implemented, I might submit a PR for it but it looks like nothing has been merged since Oct 2017. Let me know if there is interest @ogham.

**Comment by dieggsy** [comment]
@JoshuaRLi  does `exa -F` do what you want?

**Comment by JoshuaRLi** [comment]
Aha! Yes, it does. Thank you so much. Apparently #159 never added the switch into the man page, it only updated `--help`. That's why I couldn't find it.

**Comment by JoshuaRLi** [comment]
Closing. See #349 for new issue.
