### ISSUE TITLE
Arch PKGBUILD is outdated and should be removed permanently.

### ISSUE THREAD

**Issue by JoshuaRLi** [ogham/exa#350]
[`contrib/PKGBUILD`](https://github.com/ogham/exa/blob/master/contrib/PKGBUILD) is outdated (see [current](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/exa)) and should be removed from `contrib/` altogether. The official `PKGBUILD` will change with the version, and I feel like it will be forgotten (if we copy the up-to-date file to `contrib/`) when a version bump happens. `PKGBUILD`s are supposed to live on the Arch official repos or the AUR, not in the source repositories.

**Comment by ogham** [comment]
It's been removed now. (Just sweeping up the issues backlog.)

**Comment by JoshuaRLi** [comment]
Thanks @ogham!
