### ISSUE TITLE
Accept zero-padded ANSI formatting codes

### ISSUE THREAD

**Issue by krigstask** [ogham/exa#352]
Quite often ANSI codes are left-padded with zeroes.  For example, they are in [default coreutils DIR_COLORS](https://github.com/coreutils/coreutils/blob/master/src/dircolors.hin#L49).  `exa` seems to skip such entries:
![tmp](https://user-images.githubusercontent.com/419654/35880780-df39f454-0b8f-11e8-8fae-f58b5de505d4.png)
I am not sure if such zero-lpadded codes are standard or not, but this is annoying =)

Gentoo GNU/Linux amd64:
```
 % exa --version 
exa v0.8.0
 % rustc --version
rustc 1.23.0-dev
```

**Comment by ogham** [comment]
I looked and couldn't find if they're a standard either... but in any case they're certainly being used! Valid bug.

**Comment by Nadrieril** [comment]
I believe this is now fixed in commit https://github.com/ogham/exa/commit/afc9657434c5e9334548b56a76dc58f27ac00c17 .
