### ISSUE TITLE
Icons option for exa

### ISSUE THREAD

**Issue by sambadevi** [ogham/exa#357]
Maybe add an option `--icons` to show file icons like [colorls](https://github.com/athityakumar/colorls#color-ls) does

**Comment by phaazon** [comment]
I second this so much!

**Comment by phaazon** [comment]
Go for it!

**Comment by dan-santana** [comment]
Seems to be a duplicate of https://github.com/ogham/exa/issues/191

**Comment by windware** [comment]
Any progress? Sounds like a great addition.

**Comment by kutsan** [comment]
@windware https://github.com/ogham/exa/issues/357 works perfect, compile from there.

**Comment by windware** [comment]
Thanks. It works great. Hope to see it merged.

**Comment by phaazon** [comment]
Looks like a charm here. Oh please merge that!

**Comment by lilyball** [comment]
#368 was merged, this can now be closed.

**Comment by sambadevi** [comment]
Thanks @lilyball !
