### ISSUE TITLE
Feature request: Colour different size units in different colours

### ISSUE THREAD

**Issue by mbirth** [ogham/exa#359]
Currently, the sizes are shown with the number in bright green and the unit in dark green. This takes the focus away from the unit and makes it harder to e.g. find large files in the current directory.

It would be better if Exa would colourise the units differently for k/M/G/T - or maybe add an option to colourise the whole number+unit according to the unit.

**Comment by ariasuni** [comment]
You can, since https://github.com/ogham/exa/pull/607 (not yet released), configure that with `EXA_COLORS`.
