### ISSUE TITLE
Build problem on Fedora Linux: crate name cannot start with a hyphen: -

### ISSUE THREAD

**Issue by gaveen** [ogham/exa#36]
Trying to build git head on Fedora 20 x86_64. I have installed dependencies (as mentioned at: http://bsago.me/exa/) with:
```
# yum install -y libgit2 libgit2-devel cmake
```

Running either ``` cargo build --verbose``` or ```cargo build --no-default-features --verbose```gives me:
```
Process didn't exit successfully: `rustc - --crate-name - --crate-type dylib --crate-type bin --print=file-names` (status=101)
--- stderr
error: crate name cannot start with a hyphen: -
error: aborting due to previous error
```

It seems running ```make``` just invokes ```cargo build --release``` too. I'm not that familiar with ```cargo```. Any pointers?

**Comment by ogham** [comment]
Could you post your `cargo --version`, please?

**Comment by gaveen** [comment]
```cargo 0.0.1-pre-nightly (43755c0 2015-02-19) (built 2015-02-21)```

Guess this has to do with broken cargo nightly. Just noticed: https://github.com/rust-lang/cargo/issues/1342

**Comment by wires** [comment]
Running into same problem on OSX (have no clue on rust/cargo :-)

```
 ~/o/exa (master:1) » cargo build                                         09:37
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading libz-sys v0.1.1
 Downloading libssh2-sys v0.1.9
 Downloading pkg-config v0.3.0
 Downloading git2 v0.1.21
An unknown error occurred

To learn more, run the command again with --verbose.
 ~/o/exa (master:1) » cargo -V
cargo 0.0.1-pre-nightly (43755c0 2015-02-19) (built 2015-02-21)

Usage:
    cargo <command> [<args>...]
    cargo [options]
 ~/o/exa (master:1) » cargo build --verbose
Process didn't exit successfully: `rustc - --crate-name - --crate-type dylib --crate-type bin --print=file-names` (status=101)
--- stderr
error: crate name cannot start with a hyphen: -
error: aborting due to previous error
```

**Comment by gaveen** [comment]
@wires it's a bug in cargo nightly. Should be fixed within a couple of days in nightlies. Please see my above comment.
