### ISSUE TITLE
exa -F flag

### ISSUE THREAD

**Issue by jackkinsey** [ogham/exa#362]
I was disappointed to see that exa has no listed flag that emulates the behavior of the `-F` flag in ls...only to be even more surprised when I idly tested it to discover that the functionality existed, just without documentation. Any reason for this, or am I somehow missing something?

**Comment by ogham** [comment]
Nope, I just forgot to add it to the documentation! Fixed in 9c77a953a31fd4198d3a96e2f73cc9dd57afe0e1 and will be part of the next release.
