### ISSUE TITLE
Crash using -l in /prod/PID

### ISSUE THREAD

**Issue by bdejean** [ogham/exa#37]
Hello,

exa -l crashes when listing /proc/PID entries. I'm not sure if it's a rust issue or a exa bug.

    $ exa  /proc/1333/
    attr       cgroup      comm             cwd      fd      limits    mem        mountstats  numa_maps  oom_score_adj  root       sessionid  stat    syscall
    autogroup  clear_refs  coredump_filter  environ  fdinfo  loginuid  mountinfo  net         oom_adj    pagemap        sched      smaps      statm   task
    auxv       cmdline     cpuset           exe      io      maps      mounts     ns          oom_score  personality    schedstat  stack      status  wchan
    
    $ exa -l /proc/1333/
    thread '<main>' panicked at 'called `Option::unwrap()` on a `None` value', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/option.rs:362

**Comment by ogham** [comment]
Are you getting this bug with an up-to-date exa? I fixed #20 the other day which crashed when viewing a directory containing a symlink to itself, which might be the same problem.

**Comment by bdejean** [comment]
Indeed, it's already fixed.
