### ISSUE TITLE
doesn't use quotes for file names containing spaces

### ISSUE THREAD

**Issue by GitRASQ** [ogham/exa#372]
Unlike ls, exa doesn't use quotes around file names containing spaces. This can make it look like the parts before/after the spaces are different files.

**Comment by ogham** [comment]
This is #211. I don’t think I’ll be quoting files with spaces by default, but I want to at least have the option.

**Comment by ddnexus** [comment]
exa -l
```
lrwxrwxrwx 10 dd 29 Oct 11:59 foo -> bar -> baz -> foo -> bar
```
which is the link and which is the target?

ls -l
```
lrwxrwxrwx 1 dd dd 10 Oct 29 11:59 'foo -> bar -> baz' -> 'foo -> bar'
```
That looks quite fundamental to me.
