### ISSUE TITLE
Numeric permissions

### ISSUE THREAD

**Issue by Medtrack** [ogham/exa#376]
This is a feature I have allways missed in ls: access permissions numerically.
I remember 755, 644 and 777, but any other combination I allways need to check out. Having an option like this would be amazing!
```
me@host$ exa -l  --numeric
777    1,6k     me     11 abr 12:09     chess
444           - me     29 nov  2017     pron
333           - me     5 abr 15:06      cooking_recipes
```

By the way, I have already aliased _ls_. Thanks a lot for your great work!!!!

**Comment by ogham** [comment]
This is #316. I sometimes can’t remember what the numbers mean either.

It’s great to hear that other people are aliasing it!
