### ISSUE TITLE
unsorted mode?

### ISSUE THREAD

**Issue by AlJohri** [ogham/exa#377]
`ls` has an unsorted mode `ls -U` useful for very large directories. I'm using some directories right now that have 100k+ documents and was wondering if `exa` might be able to help. I usually just need to get a couple sample documents out of the 100k but piping to head is still very slow. any ideas?

thanks!

**Comment by KangarooCreativeTeam** [comment]
I think what you're after is already implemented: 

`exa --sort none`

O_O

**Comment by ogham** [comment]
Yeah, that’s the way. I think this functionality so rare, I don’t want to use up a whole single-letter flag for it; those are precious!
