### ISSUE TITLE
Add option to easily show dirs/files/symlinks(/other?)

### ISSUE THREAD

**Issue by AllanLRH** [ogham/exa#381]
Would be nice if `exa` were able to easily filter what to show, like `tree`, or even better IMHO, the `find` replacement [`fd`](https://github.com/sharkdp/fd). The following is from `fd --help`:
```
    -t, --type <filetype>...
            Filter the search by type (multiple allowable filetypes can be specified):
              'f' or 'file':         regular files
              'd' or 'directory':    directories
              'l' or 'symlink':      symbolic links
```
The syntax is so easy to remember!
I don't know if there's any other file-like types on unix-systems which should be considered, such as sockets?

**Comment by ogham** [comment]
This is #187. I can’t copy the exact `-t` flag, but I can do something similar.
