### ISSUE TITLE
Add --time-style=hide

### ISSUE THREAD

**Issue by thibran** [ogham/exa#383]
`ls` allows to hide the date and time columns with `ls -l --time-style=+""`. It would be nice if `exa` could accomplish the same.

```
~> ls -l --time-style=+""
total 36
drwxr-xr-x  6 tux users  4096  Desktop/
drwxr-xr-x 15 tux users  4096  Documents/
drwxr-xr-x  7 tux users  4096  Downloads/
drwxr-xr-x  9 tux users  4096  Music/
drwxr-xr-x  6 tux users   164  Pictures/
drwxr-xr-x 17 tux users   195  src/
drwxr-xr-x  5 tux users    97  Videos/
```

Suggested solutions:

* Add `--time-style` `hide`
* Or add a new flag `--no-date-and-time` (might be more accessible) to hide time information

**Patch**
I wrote a [patch](https://github.com/thibran/exa/tree/time_style_hide) which adds the `hide` variant to `--time-style`, would you like to get a pull request to merge it upstream?

**Comment by dallbee** [comment]
+1

**Comment by ogham** [comment]
I never thought about using `--time-style` to hide the column! The eventual goal is to make every column hideable and reorderable in #161.
