### ISSUE TITLE
shell prompt in screenshot

### ISSUE THREAD

**Issue by rumbletumjum** [ogham/exa#388]
Is that fish or zsh in the screenshot in the readme, and what them is being used? it's pretty sweet and exactly the sort of thing I've been looking for

**Comment by Giancarlos** [comment]
Look at the screenshot, it says it is fish on the title bar.

![Screenshot](https://raw.githubusercontent.com/ogham/exa/master/screenshots.png)

**Comment by rumbletumjum** [comment]
Ah, thanks. Missed that.
