### ISSUE TITLE
Cut new release?

### ISSUE THREAD

**Issue by jbergstroem** [ogham/exa#389]
Looks like the last release was ~6mo ago. Perhaps cut a release (or rc) with recent development for broader user testing?

**Comment by infinity0** [comment]
It would be useful to have this for Debian as well. We have most of the dependencies packaged already.

**Comment by wldcordeiro** [comment]
@ogham would this be possible? Looks like some good stuff landed and more waiting. If you need more contributors I'd love to help, and I'm sure others would be interested.

**Comment by equal-l2** [comment]
+1

**Comment by ogham** [comment]
v0.9.0 is now under Releases, and it feels like a huge relief!
