### ISSUE TITLE
Split off grid formatting?

### ISSUE THREAD

**Issue by marcusklaas** [ogham/exa#39]
Hi! Exa is great. Thanks for sharing it with us.

Have you considered splitting off your grid formatting logic into a library? It seems to work really well and could be of use to other projects!

**Comment by ogham** [comment]
Thank you!

That's a pretty good idea. I'll leave this issue open to remind me to actually do it.

**Comment by ogham** [comment]
Here it is: https://github.com/ogham/rust-term-grid

**Comment by marcusklaas** [comment]
:+1:

**Comment by ogham** [comment]
👊
