### ISSUE TITLE
directory size?

### ISSUE THREAD

**Issue by piahoo** [ogham/exa#391]
is there a way to show summarized size of a directory (sum of all files inside it?) I know it would not be very fast, but I am just curious

Cheers

**Comment by ogham** [comment]
This is #91. The speed is the main reason why it hasn’t been done yet -- exa really wants to only recurse through directories once, and this would make it have to loop twice. As you say, having it be a bit slower isn’t the end of the world, but it’s still something I’d like to attempt first.
