### ISSUE TITLE
Tree + Sort

### ISSUE THREAD

**Issue by KangarooCreativeTeam** [ogham/exa#392]
`--tree` mode is very useful, esp. with `--long`, however it could be made MOAR awesome by adding support to `--sort` _at each level_.

Maybe a targeted improvement for v1.0 release?

O_O

**Comment by ogham** [comment]
Do you mean having *different* sort modes for each level? Like, the first level would be sorted by name, but the second level onwards would be sorted by size, and the third by name again... something like that?
