### ISSUE TITLE
can't compile when there is no git repository

### ISSUE THREAD

**Issue by olegmedoed** [ogham/exa#399]
![image](https://user-images.githubusercontent.com/4011317/41668071-318ebf1a-74b7-11e8-818b-f0f4045a9b09.png)

I just run `cargo install exa` but cannot install it because the error.

**Comment by olegmedoed** [comment]
Btw, the error was happened on Ubuntu, but on Debian I can compile, both OSs have libgit2-dev installed, actually I was able to compili it on Debian even without libgit2-dev be installed.

**Comment by Don42** [comment]
This seems to be the same issue as #402 
The solution there was missing cmake.
You might want to try after installing that.

**Comment by olegmedoed** [comment]
@Don42 , yes, installing of `cmake` fix the problem, thanks
