### ISSUE TITLE
Provide releases?

### ISSUE THREAD

**Issue by dead10ck** [ogham/exa#40]
I realize that cross-compilation is difficult at this stage of the game, but it would be nice if compiled binaries were provided for whatever platforms are feasible for the author/contributors. Since there are 24 crate dependencies (when transitives are counted), it is likely that one or more crates will not compile at any given point in time. (In particular, at the time of this writing, `libssh2-sys` is not compiling.)

**Comment by ogham** [comment]
Yeah, libgit2 and its myriad dependencies are the main reason I wanted to make that feature optional. There's an unfortunate amount of breakage.

I plan to release v0.2 very soon, and when I do, I'll release OS X and Debian releases, which are the only ones I know how to make... if anyone could point tutorials for other Linuxes my way, I'd be grateful.

**Comment by tuftedocelot** [comment]
Tagging onto this, at what point do rust nightlies become necessary? The nightlies have been failing to build exa for several days now while the most recent alpha (dated 2015-02-20) builds exa just fine

**Comment by larrym** [comment]
Ubuntu 14.04:

       Compiling datetime v0.1.4
         Running `rustc /root/.cargo/registry/src/github.com-1ecc6299db9ec823/datetime-0.1.4/src/lib.rs --crate-name datetime --crate-type lib -g -C metadata=80c23b140cc45fcd -C extra-filename=-80c23b140cc45fcd --out-dir /usr/src/exa/target/deps --emit=dep-info,link -L dependency=/usr/src/exa/target/deps -L dependency=/usr/src/exa/target/deps --extern pad=/usr/src/exa/target/deps/libpad-ae5c19011118d32e.rlib --extern locale=/usr/src/exa/target/deps/liblocale-6f3edc672b7d8674.rlib --extern regex_macros=/usr/src/exa/target/deps/libregex_macros-bdbdbfedad0748ac.so --extern regex=/usr/src/exa/target/deps/libregex-2796c106c9344244.rlib -Awarnings`
    Build failed, waiting for other jobs to finish...
    Could not compile `libgit2-sys`.
    
    Caused by:
      Process didn't exit successfully: `rustc /root/.cargo/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.1.14/build.rs --crate-name build-script-build --crate-type bin -C prefer-dynamic -g --out-dir /usr/src/exa/target/build/libgit2-sys-b41aa7925d0805ee --emit=dep-info,link -L dependency=/usr/src/exa/target/deps -L dependency=/usr/src/exa/target/deps --extern pkg-config=/usr/src/exa/target/deps/libpkg-config-a410dee8d42bdfcb.rlib -Awarnings` (exit code: 101)
    root@uberp:/usr/src/exa#

**Comment by ogham** [comment]
Hey look! https://github.com/ogham/exa/releases/tag/v0.2.0

I have no idea if they work or not, though... I am a bad releaser.

**Comment by ctgreybeard** [comment]
Cursory tests work for me on OS X 10.10

**Comment by ogham** [comment]
:+1:
