### ISSUE TITLE
Flag for only showing directories in results

### ISSUE THREAD

**Issue by justanotherdot** [ogham/exa#401]
Hi! Seems like `exa` has a bunch of flags similar to `tree`, but one feature I found myself wanting recently is `tree`s `-d` flag for only showing directories. It looks like `exa` has `-d` for `--list-dirs`. Would it be useful to others to have a similar, but obviously differently named, flag to only show directories in the results? Perhaps there is already a way to do this already with `exa?

Thanks!

**Comment by samson-jerome** [comment]
Bumping this issue as it is something I'd like to see happen as well !

**Comment by Don42** [comment]
Filtering out the files in the tree is a single line patch. I'm going to try and figure out how add the command line option in the next few days.

**Comment by Don42** [comment]
Any idea on what letter to use for the short option?

**Comment by justanotherdot** [comment]
It would seem `exa` isn't using capital `D` (release v0.8.0), maybe that's an option as it still mnemonically implies 'directory'?

**Comment by Don42** [comment]
`-D` seems to also be unused on *master*. 
If #202 gets implemented the long option `--list-dirs` might even be free.

I'll add the short option tomorrow and open a pull request.
