### ISSUE TITLE
Unable to install using cargo

### ISSUE THREAD

**Issue by sanaptejas** [ogham/exa#402]
sudo cargo install exa
[sudo] password for user: 
    Updating registry `https://github.com/rust-lang/crates.io-index`
  Installing exa v0.8.0                                                         
   Compiling winapi-build v0.1.1
   Compiling pkg-config v0.3.11
   Compiling num-traits v0.2.5
   Compiling cc v1.0.17
   Compiling winapi v0.2.8
   Compiling libc v0.2.42
   Compiling matches v0.1.6
   Compiling nom v1.2.4
   Compiling unicode-width v0.1.5
   Compiling cfg-if v0.1.4
   Compiling unicode-normalization v0.1.7
   Compiling utf8-ranges v0.1.3
   Compiling regex-syntax v0.3.9
   Compiling percent-encoding v1.0.1
   Compiling byteorder v0.4.2
   Compiling bitflags v0.9.1
   Compiling glob v0.2.11
   Compiling ansi_term v0.8.0
   Compiling natord v1.0.9
   Compiling getopts v0.2.17
   Compiling lazy_static v0.2.11
   Compiling scoped_threadpool v0.1.9
   Compiling unicode-bidi v0.3.4
   Compiling pad v0.1.5
   Compiling term_grid v0.1.7
   Compiling kernel32-sys v0.2.2
   Compiling log v0.4.3
   Compiling iso8601 v0.1.1
   Compiling memchr v0.1.11
   Compiling locale v0.2.2
   Compiling term_size v0.3.1
   Compiling users v0.5.3
   Compiling num_cpus v1.8.0
   Compiling libz-sys v1.0.18
   Compiling cmake v0.1.31
   Compiling log v0.3.9
   Compiling aho-corasick v0.5.3
   Compiling thread-id v2.0.0
   Compiling thread_local v0.2.7
   Compiling libgit2-sys v0.6.19
   Compiling regex v0.1.80
   Compiling num-traits v0.1.43
   Compiling number_prefix v0.2.8
   Compiling datetime v0.4.7
error: failed to run custom build command for `libgit2-sys v0.6.19`
process didn't exit successfully: `/tmp/cargo-installjbSNSY/release/build/libgit2-sys-2585e55afc7edb42/build-script-build` (exit code: 101)
--- stdout
running: "cmake" "/root/.cargo/registry/src/github.com-1ecc6299db9ec823/libgit2-sys-0.6.19/libgit2" "-DUSE_SSH=OFF" "-DUSE_OPENSSL=OFF" "-DCURL=OFF" "-DBUILD_SHARED_LIBS=OFF" "-DBUILD_CLAR=OFF" "-DCMAKE_INSTALL_PREFIX=/tmp/cargo-installjbSNSY/release/build/libgit2-sys-44d1788c24e1936a/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=c++" "-DCMAKE_BUILD_TYPE=Release"

--- stderr
fatal: Not a git repository (or any of the parent directories): .git
thread 'main' panicked at '
failed to execute command: No such file or directory (os error 2)
is `cmake` not installed?

build script failed, must exit now', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.31/src/lib.rs:643:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: failed to compile `exa v0.8.0`, intermediate artifacts can be found at `/tmp/cargo-installjbSNSY`

Caused by`:
`  build failed

**Comment by zhengweidi** [comment]
same problem

**Comment by sanaptejas** [comment]
Cool. It didn't occur to me that, that could be the problem.

**Comment by zhengweidi** [comment]
take a look at your error message:
```
--- stderr
fatal: Not a git repository (or any of the parent directories): .git
thread 'main' panicked at '
failed to execute command: No such file or directory (os error 2)
is cmake not installed?
```
It already tells you the problem.

**Comment by Don42** [comment]
@sanaptejas Has this fixed your issue?
In an unrelated note, why are you running the command as sudo? By default the installed files
are written to your home dir and should not require elevated rights.

**Comment by sanaptejas** [comment]
yes installing `cmake` solved my problem

**Comment by dsego** [comment]
IMO, this should be documented in the installation instructions.
