### ISSUE TITLE
--sort and --reverse doesn't seem to do anything if files are given as argument explicitely

### ISSUE THREAD

**Issue by yory8** [ogham/exa#404]
exa 0.8.0

test case:

```
> touch a b c
> exa -r
c  b  a
> exa -r *
a  b  c
```

**Comment by epitron** [comment]
This is a strange bug. It seems to behave differently in combination with different options:
✔ `exa -lr *` works
✗ `exa -1r *` fails
✗ `exa -dr *` fails
✗ `exa -r *` fails
