### ISSUE TITLE
displays symbolic link destination in long mode but not in grid

### ISSUE THREAD

**Issue by RatanRSur** [ogham/exa#406]

**Comment by talal** [comment]
I, too, would love this feature. It is really useful to get a quick overview of where the link points to, refer to the screenshot (colorls) below:

![screen shot 2018-08-26 at 00 36 33](https://user-images.githubusercontent.com/3526562/44623154-29063b80-a8c8-11e8-997c-a5ad2369977e.png)

**Comment by ogham** [comment]
Wouldn’t this just make each individual grid cell extremely wide, which kind of defeats the point of using grid?

Is it possible for you to show me an example of how you’d use this? I might be missing something.

**Comment by RatanRSur** [comment]
In my preferred usage, it only grids it when there's no information lost by doing so. I'd rather have a long list with all the info than a grid without some of it.

**Comment by hyiltiz** [comment]
But I'd rather lose some visual noise to get a clean interface...

**Comment by ogham** [comment]
I'm going to stick with the way exa currently works.

**Comment by fpuga** [comment]
Thanks for a wonderful tool.

I know this issue is closed but imho the actual behaviour is not correct. When `--long` and `--grid` are used at the same time i expect to use more than one column if no info is lost. For example icons are still showed, but destination links are not:

```shell
$ cd /tmp

$ ln -s /tmp/no_existent_path foo_link

$ exa --long foo_link 
lrwxrwxrwx 21 fpuga 23 Jul 19:45 foo_link -> /tmp/no_existent_path

$ exa --long --grid foo_link 
lrwxrwxrwx 21 fpuga 23 Jul 19:45 foo_link
```
