### ISSUE TITLE
colors / iterm2 / ohmyzsh

### ISSUE THREAD

**Issue by johndpope** [ogham/exa#412]
is there a simple way to change the yellow / green from the color scheme? 

<img width="643" alt="screen shot 2018-08-30 at 3 04 03 pm" src="https://user-images.githubusercontent.com/289994/44873344-f52f6b00-ac65-11e8-88e8-af7911e85ddd.png">

**Comment by ikornaselur** [comment]
While it's not changing the colours in exa, you can go into `iTerm2` -> `Preferences...` -> `Profiles` -> `Colors` and play around with the `ANSI Colors` there, which will change the colours globally in your terminal, if you want to tweak the actual colours themselves.

If you're looking to actually replace what colour exa uses, it doesn't seem possible, based on the `colours.rs` file in the project:

https://github.com/ogham/exa/blob/a3b2f2b3f43a874b50fda12a5a77fa63842c30de/src/style/colours.rs#L111-L194

Though I guess you could change that and compile the project locally.

**Comment by johndpope** [comment]
🙏

**Comment by johndpope** [comment]
<img width="639" alt="screen shot 2018-09-04 at 9 50 21 am" src="https://user-images.githubusercontent.com/289994/45035444-f7a81100-b027-11e8-9f3d-3705b68720c5.png">
