### ISSUE TITLE
Support ls -p

### ISSUE THREAD

**Issue by bendem** [ogham/exa#423]
`-p` adds a trailing slash to directories in the listing:

```
➜  aouhruatha gls -l
total 0
-rw-r--r-- 1 benjamin wheel  0 Oct  6 13:51 a
-rw-r--r-- 1 benjamin wheel  0 Oct  6 13:51 b
drwxr-xr-x 2 benjamin wheel 68 Oct  6 13:51 bleh
-rw-r--r-- 1 benjamin wheel  0 Oct  6 13:51 c
-rw-r--r-- 1 benjamin wheel  0 Oct  6 13:51 d
➜  aouhruatha gls -lp
total 0
-rw-r--r-- 1 benjamin wheel  0 Oct  6 13:51 a
-rw-r--r-- 1 benjamin wheel  0 Oct  6 13:51 b
drwxr-xr-x 2 benjamin wheel 68 Oct  6 13:51 bleh/
-rw-r--r-- 1 benjamin wheel  0 Oct  6 13:51 c
-rw-r--r-- 1 benjamin wheel  0 Oct  6 13:51 d
➜  aouhruatha gls
a  b  bleh  c  d
➜  aouhruatha gls -p
a  b  bleh/  c	d
```

**Comment by bendem** [comment]
can `-p` be an alias for `-F` then? That would make `exa` closer to a drop-in replacement for `ls`.

**Comment by palindrom615** [comment]
@bendem maybe, but `ls -p` and `ls -F` shows different. p option only adds slash after directory's name and F option also adds * after executable and @ after symlink and so on. So just aliasing both could be confusing IMO...

```bash
palindrom615@instance-2:~/tmp$ ls -p
A  A.symlink  B  a1  a10  a2  b10a1  b9a1  b9a2  dir/  executable
palindrom615@instance-2:~/tmp$ ls -F
A  A.symlink@  B  a1  a10  a2  b10a1  b9a1  b9a2  dir/  executable*
```

you could check [https://unix.stackexchange.com/questions/146802/the-f-option-for-ls](https://unix.stackexchange.com/questions/146802/the-f-option-for-ls).

**Comment by bendem** [comment]
I'll be using `-F` now that I now about it, I'll leave it up to @ogham to close this if `-p` is not required.

**Comment by ogham** [comment]
I’m hesitant to add flag aliases at this stage, lest another feature comes along that needs `-p`. `-F` was stolen from BSD ls!
