### ISSUE TITLE
'exa -a' behaves like 'ls -A' and there's no '-A' option in exa

### ISSUE THREAD

**Issue by luisdavim** [ogham/exa#427]
can we have `-a` and `-A` flags in `exa` behaving the same way as in `ls`?

example:
```
17:39:38 $ gls -a
.   .git        README.md   backup.sh  files       linux.sh  ppa-cleanup.sh   restore-repos.sh
..  .gitignore  android.sh  config.sh  install.sh  osx.sh    restore-ppas.sh  rsync-homedir-excludes.txt
17:39:48 $ gls -A
.git        README.md   backup.sh  files       linux.sh  ppa-cleanup.sh   restore-repos.sh
.gitignore  android.sh  config.sh  install.sh  osx.sh    restore-ppas.sh  rsync-homedir-excludes.txt
17:39:53 $ exa -a
.git        android.sh  config.sh  install.sh  osx.sh          README.md        restore-repos.sh
.gitignore  backup.sh   files      linux.sh    ppa-cleanup.sh  restore-ppas.sh  rsync-homedir-excludes.txt
17:39:57 $ exa -A
Unknown argument -A
```

**Comment by ogham** [comment]
You can get the `-a` behaviour in exa with `-a -a`. It’ll show `.` and `..` files.

It’s done like this on purpose because those files aren’t relevant most of the time. See the docs: https://the.exa.website/features/filtering#dotfiles

**Comment by schnatterer** [comment]
Digging out this issue only to add one argument:
[A lot of people](https://stackoverflow.com/a/17902999/1845976) seem to see `ls -A` as a portable way of checking for an empty dir in a bash script.
Not portable for me, as I use `alias ls=exa`. :grimacing: 
Other than that, I love exa! Thanks very much for it.

**Comment by ariasuni** [comment]
Aliases aren’t used in scripts, so using `alias ls=exa` shouldn’t change anything for you.
