### ISSUE TITLE
No man entry for -F option

### ISSUE THREAD

**Issue by fbruetting** [ogham/exa#429]
This option is usable like in `ls`, but this isn’t documented. ;)

**Comment by pconcepcion** [comment]
I think it's [briefly documented](https://github.com/ogham/exa/blob/57e4c08411f59e7db91fa7d8127fbd412667ea32/contrib/man/exa.1#L50)

**Comment by fbruetting** [comment]
Strange, this is not there in my man page. I have `v0.8.0-10` of Fedora 29.

![bildschirmfoto von 2018-10-21 17-38-38](https://user-images.githubusercontent.com/10520767/47269003-35b9af80-d558-11e8-9ddf-3eab3e54bcb1.png)

**Comment by ogham** [comment]
You’re both right: I missed it out, and it was added after the v0.8.0 release. When v0.9.0 is out (Soon!), it’ll be there.
