### ISSUE TITLE
-A (--almost-all) option missing

### ISSUE THREAD

**Issue by ctgreybeard** [ogham/exa#43]
The -A option (which doesn't list `.` or `..`) is missing.

**Comment by ogham** [comment]
The `-a` option doesn't list `.` or `..` either :) I didn't include them because I think they just take up space.

**Comment by ctgreybeard** [comment]
Yes, but the problem is that some packages (`zsh-templates` for example) provide macros which use the `-A` option. This causes an error in exa and it fails. Since `-A` is a valid `ls` option can you please at least accept it in exa?

**Comment by ExeTwezz** [comment]
@ctgreybeard You could do it yourself.

**Comment by ogham** [comment]
After a few months of deliberation I decided to close this as wontfix, sorry. As we don't have those directory entries, the only thing the `-A` flag could do would be the *opposite* of that, which I feel would be too confusing compared to `ls`.
