### ISSUE TITLE
0.9.0 release

### ISSUE THREAD

**Issue by ignatenkobrain** [ogham/exa#441]
There was no release for last year and I'm wondering when will new release come?

Thanks!

**Comment by bemeurer** [comment]
Please make a new release!

**Comment by ogham** [comment]
Soon™

**Comment by ariasuni** [comment]
Duplicate of #389

**Comment by ignatenkobrain** [comment]
I would appreciate if it would contain #469 and #461

**Comment by ToonSpin** [comment]
Hi @ogham, any update on the progress toward a new release? Your comment saying "soon(tm)" is three months old at this point. Is there a place where we can see what's blocking a new release?

**Comment by okias** [comment]
ping @ogham

**Comment by lilyball** [comment]
There's 4 open issues in the [v0.9.0 milestone](https://github.com/ogham/exa/milestone/7) which I'd assume is what's holding up the release.

**Comment by PhilsLab** [comment]
ping @ogham has this project died?

**Comment by kpcyrd** [comment]
+1, we currently need to apply a large number of patches to build exa because the crates we have in debian are too new.

**Comment by MaxMilton** [comment]
Would be great to see a release so the recent fixes (e.g., https://github.com/ogham/exa/issues/517) can trickle down into distro package managers. The remaining issues in the [v0.9.0](https://github.com/ogham/exa/milestone/7) have been there for years and surely shouldn't hold up a release.

**Comment by ogham** [comment]
I'm sorry this took so long, everyone. But v0.9.0 is now under Releases.
