### ISSUE TITLE
Add spaces in permissions

### ISSUE THREAD

**Issue by lydell** [ogham/exa#448]
Thanks for this great tool!

I would find it very helpful if the groups of permissions were separated by spaces. I always find myself counting when I need to find the set I'm looking for.

Like this:

```
/usr/share/X11 $ exa -lh
Permissions   Size User Date Modified Name
d rwx r-x r-x    - root  2 sep 11:57  locale
l rwx rwx rwx   16 root 21 jun 12:48  rgb.txt -> /etc/X11/rgb.txt
. rw- r-- r--  42k root 29 aug 20:18  XErrorDB
d rwx r-x r-x    - root  5 jan 21:35  xkb
. rw- r-- r-- 8,3k root 31 maj  2016  xman.help
d rwx r-x r-x    - root 28 okt 23:12  xorg.conf.d
```

What do you think?

**Comment by ogham** [comment]
I can see the appeal, but I want to keep exa's format as it is.
