### ISSUE TITLE
alpine port?

### ISSUE THREAD

**Issue by jesse23** [ogham/exa#460]
Is it possible that provide a alpine build based on `musl-libc`? like `ripgrep` and `fd`.

**Comment by 5paceToast** [comment]
Just as an FYI - an alpine aport exists in my user-aports (see [here](https://github.com/5paceToast/user-aports/blob/master/toast/exa/APKBUILD)).
It's not in the official repos yet, but that should be happening at some point (very likely before the end of March).

**Comment by ogham** [comment]
Looks like we are in Alpine now!
