### ISSUE TITLE
Feature Request: Directory hyperlinks

### ISSUE THREAD

**Issue by jcklpe** [ogham/exa#465]
Hi, first I want to say, fantastic job on exa! It's extremely well designed and a joy to use :) 

I wanted to put in a feature request. I would love for the ability to click on, or highlight directories and press a key to cd into them. 

This request is somewhat inspired by [[xiki]](https://www.youtube.com/watch?v=bUR_eUVcABg) or [[midnight commander]](https://www.youtube.com/watch?v=lWu2R9cn_b8) or [[ranger]](https://ranger.github.io/). 

The ability to navigate the filesystem by clicking or selecting output from exa would be a really great addition to it that would also be much more lightweight than these above options. 

Options for this hyperlink function could be limited to just clicking directories, but the ability to click files and have the default application (such as nano or vim) open it up would be super useful.

**Comment by ogham** [comment]
Thanks! There’s a terminal feature for hyperlinks that’s being tracked in #396. I plan on implementing it at some point, so eventually this will land. What it does will depend on which terminal you’re using, but it’ll probably open files in the default application.

**Comment by VanDerLars** [comment]
Hej, 
how's that growing?

**Comment by ariasuni** [comment]
This was closed as duplicate, any discussion should happen on #396.

Nobody is working on this feature as far as I know.

**Comment by igor-petrik-invitae** [comment]
> Nobody is working on this feature as far as I know.

Seems like `exa` is officially unmaintained now, and development has moved to [`eza`](https://github.com/eza-community/eza); `eza` has implemented this feature.
