### ISSUE TITLE
Can't list files from Google Drive File Stream

### ISSUE THREAD

**Issue by tomyun** [ogham/exa#466]
![screen shot 2019-01-11 at 10 32 16 am](https://user-images.githubusercontent.com/906626/51052758-83105080-158c-11e9-88e3-6635031d974d.png)

When trying to list files from [Google Drive File Stream](https://www.google.com/drive/download/) volume, there's time when `exa` fails to give a result. It may work fine for some other directories in the same volume, but there are clearly cases that it doesn't. For example, the root directory of the volume `~/Google Drive File Stream` or `/Volumes/GoogleDrive` always show nothing. Guess something not going well with FUSE internally used by GDFS? I'm on macOS 10.14.2.

**Comment by kmox83** [comment]
This issue is only related to macos systems, it is due the use of getdirentries64 from the Rust standard library std::fs and issues with fuse filesystems

**Comment by ariasuni** [comment]
@tomyun is this still happening with exa 0.10.0?

@kmox83 I can’t find what you’re talking about. Do you have a link?

**Comment by tomyun** [comment]
Just tested exa 0.10 with Google Drive (formerly Google Drive File Stream) 46.0.3 on macOS 11 and it seems working fine. Thanks!

**Comment by ariasuni** [comment]
OK, I’ll close this then. Thanks for the feedback!
