### ISSUE TITLE
[Feature Request] Put symlinks to directories first when using `--group-directories-first`

### ISSUE THREAD

**Issue by VichoReyes** [ogham/exa#471]
Currently, when using `--group-directories-first` directories and symlinks to directories are not put together, which would be useful considering they're treated mostly the same way (they're both for cd'ing into and organizing files).

**Comment by ogham** [comment]
Good idea

**Comment by miyalys** [comment]
It's closed as _fixed_ but I'm running Exa 0.9.0 and it seems to not group symlinks to dirs with actual dirs, with the _--group-directories-first_ flag? Does it work for you?

**Comment by VichoReyes** [comment]
@miyalys It's just that there hasn't been a release since it was merged. 0.9.0 if from July 2019 and the merge was in 2020.

**Comment by miyalys** [comment]
Ah makes sense, thanks!

**Comment by autoferrit** [comment]
If I may ask, i was about to make an issue for this same feature. how often do you push releases?
