### ISSUE TITLE
Feature Request: Make -T and -R not recurse into dot directories when -a is not set

### ISSUE THREAD

**Issue by Mendelt** [ogham/exa#474]
_current behavior_
The commands `exa -T` and `exa -R` now ignore the -a flag and will show contents of dot-directories like .git even when the -a flag is not set. This makes listing trees of git repositories for example very noisy as there is loads of stuff in there that I'm not really that interested in most of the time.

_requested behavior_
If possible I would like `exa -T` to also use the -a flag to ignore or include dot directories. But if this is not possible it might be useful to have another flag to make the tree-mode skip dot directories.

**Comment by Don42** [comment]
Hi thank you for reporting this issue.
Unfortunately I was unable to reproduce it with both 0.8.0 and the current master.
It would be helpful if you could give use more information on your system and what version
of *exa* you are using.
Are you using *exa* directly or via an alias? Are there any other parameters that might have an 
effect?

**Comment by Mendelt** [comment]
Hmmm. I don't seem to be able to reproduce it either.
I'm very sorry for wasting your time. I'll close the issue.
