### ISSUE TITLE
Ignore --across (-x) given option --long (-l)

### ISSUE THREAD

**Issue by tiojoca** [ogham/exa#476]
Currently, exa returns an error given both the options the flags `--across` (`-x`) and `--long` (`-l`):
```
Option --across (-x) is useless given option --long (-l)
```

This behavior is similar to what was happening before where you couldn't use some options without the `--long`/`-l` option (#44, #152, #256), except the other way around.

Changing this behavior would not only make it more consistent with ls and the fixes for these issues but also allow extending aliases that use `--across`/`-x` with the long format — for example, this at the moment wouldn't work:
```
alias lx='exa --group-directories-first -aFx'
lx -l # ~> currently returns an error
```

**Comment by Don42** [comment]
The solution might be related to #125, unfortunately the commit to close this ticket was quite large. But it might still be a good starting point to find a solution.

**Comment by ogham** [comment]
Yeah, this should only be happening in strict mode, but for some reason it's not.

**Comment by ogham** [comment]
Will be fixed in next release
