### ISSUE TITLE
exa-linux-install

### ISSUE THREAD

**Issue by ASHERH4X** [ogham/exa#477]
This isn't an "issue" but I couldn't find any contact method for the creator.

I created a simple repo with scripts to install or uninstall exa.  The install script grabs the latest release from GitHub and sets it up.

[https://github.com/ASHERH4X/exa-linux-install](https://github.com/ASHERH4X/exa-linux-install)

Hopefully this makes life a little easier for some!  :-D

**Comment by evitalis** [comment]
@ASHERH4X What distro do you use? I have found actual packages for exa in many of the repos already so this would not be necessary.

**Comment by ASHERH4X** [comment]
Debian stretch.

**Comment by evitalis** [comment]
@ASHERH4X I have used [cargo-deb](https://crates.io/crates/cargo-deb) successfully to make basic DEB packages for Rust applications. It doesn't include external dependencies but in many cases this is fine. Is this something that could help get you started? Do you know if there is an open request with the Debian team for an official package?

**Comment by ASHERH4X** [comment]
Great, thanks for that!

**Comment by sanxiyn** [comment]
exa is already packaged in Debian, see https://packages.debian.org/sid/exa, but it is not in Debian Stretch, a stable release released in 2017.

**Comment by ASHERH4X** [comment]
Thanks for that.  If you could guide me toward a guide of adding it to a Debian Stretch repo I'd be happy to contribute.  I'm a sys/net/admin and a bit webdev, but not well-versed in the Linux world of repo contribution.  Thanks!

**Comment by ASHERH4X** [comment]
FYI, I updated the readme to explain more my purpose of why i wanted to make an alternative installer.  It's totally in favor of the creator, but it takes a mere 5 minutes to install using my script, whereas it can take 20-30 minutes in some cases for some who are not as familiar with *nix.

**Comment by ogham** [comment]
I'm closing as exa is getting pre-packaged more and more.
