### ISSUE TITLE
Exa for iOS

### ISSUE THREAD

**Issue by alessaba** [ogham/exa#482]
Hi, 
Would it be possible to add a variant of exa which is supported by iOS (jail broken)? I will try to compile it from source myself and I will also try to make it a tweak, if you allow me. I think it’d be really cool

**Comment by abbychau** [comment]
if you are using the linux shell of iOS, then it should be already runnable.

if you want it to be linked,
Exa depends on `glob`, which is using `std::path`. So the core function should be supported by iOS.
It is needed to write Externs and CString mappings to the library.

**Comment by ogham** [comment]
I have _no_ idea how to build anything for iOS, but you’re welcome to try!
