### ISSUE TITLE
`--git-ignore` doesn't hide Git ignored files

### ISSUE THREAD

**Issue by kosciak9** [ogham/exa#485]
Arch Linux with `Linux 5.0.4-zen1-1-zen #1 ZEN SMP PREEMPT Sat Mar 23 20:59:30 UTC 2019 x86_64 GNU/Linux`

`exa-git v.1142-1` and `exa v0.8.0-3` - neither works

expected result: `--git-ignore` hides files from repository
currently: it doesn't :(

**Comment by alexilyaev** [comment]
Please add more information on your folder structure and contents of `.gitignore`.  
For me `--git-ignore` does work but has some inconsistencies between how git interprets it and how exa does.

**Comment by kosciak9** [comment]
Hey, I believe that was the most basic one, ignoring `node_modules` but I will check today.

**Comment by phanimahesh** [comment]
Example: An entry `foo` in `.gitignore` is interpreted as the file or folder `foo` at top level _or in any subfolder_, but `exa` only ignores the top level dir.

**Comment by ospalh** [comment]
I hav a rather long ~/.gitignore_global, that i use via `~/.gitconig`
```
[core]
  excludesfile = /home/NN/.gitignore_global
```
That is used by git and possibly not by exa.

**Comment by ariasuni** [comment]
This was fixed in #653 (I just tested your setup), there just hasn’t been a new release made since then.

**Comment by ChristophP** [comment]
@ariasuni Thx , the fix is great. I compiled from source for now. Hopefully there'll be a release soon
