### ISSUE TITLE
Feature Request: GitHub-style Folder Jumping

### ISSUE THREAD

**Issue by jzelinskie** [ogham/exa#487]
Here's the blog post introducing folder jump on GitHub: https://github.blog/2014-08-19-folder-jumping/

Here's a strawman UX:

```sh
$ exa -T test
test
└── test
   └── test
      └── README.md
$ exa -j test # -j for jump
test/test/README.md
```

**Comment by ogham** [comment]
I would like to have a command-line tool like this, but I don't think exa is the best place to include the functionality, sorry.

**Comment by jzelinskie** [comment]
>I would like to have a command-line tool like this, but I don't think exa is the best place to include the functionality, sorry.

Is it the behavior of actively jumping to the directory that you think precludes this behavior?
Adding a flag that would recurse and to show empty directories like this seems to only make sense to me in something that you'd use in place of `ls`.

```sh
$ exa --nonemptydepth 1
bin dev etc home/jzelinskie opt sbin usr var
```
