### ISSUE TITLE
Command line parsing compatibility

### ISSUE THREAD

**Issue by crlf0710** [ogham/exa#498]
Current command line parsing code is based on `OsStr`, and cut if off into smaller `OsStr` slices. These operations are not possible on windows platform. 

I'm doing some personal porting experiment, but it stopped at this point. Since quite a lot of lines code will be affected. What do you think is the best way to move forward?

**Comment by ogham** [comment]
Sorry for not answering this at the time. The `OsStr` code was necessary to allow non-UTF-8 filename arguments. There's some Windows support changes in #820 and it seems like the changes deal with the `OsStr` issue.
