### ISSUE TITLE
Exa Website Typo

### ISSUE THREAD

**Issue by Macavirus** [ogham/exa#499]
Not finding a repo for the exa website to submit a fix.

https://the.exa.website/docs

Contains a reference to a deprecated short command:

> Finally, it’s possible for exa to recurse into a directory and list the contents of every subdirectory beneath it. There are the -r or --recurse command-line options for this.

should be:

> Finally, it’s possible for exa to recurse into a directory and list the contents of every subdirectory beneath it. There are the **-R** or --recurse command-line options for this.

**Comment by Macavirus** [comment]
Any update on this? I can PR if there is a public exa website repo

**Comment by ogham** [comment]
Thanks for pointing this out — I've updated my local version of the site, and it'll be updated when I push it live.
