### ISSUE TITLE
panic when piping to echo

### ISSUE THREAD

**Issue by kevinburke** [ogham/exa#50]
type `exa | echo` and you get:

```
thread '<main>' panicked at 'failed printing to stdout: IoError { kind: BrokenPipe, desc: "broken pipe", detail: Some("Broken pipe") }', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libstd/old_io/stdio.rs:355
```

**Comment by ogham** [comment]
Hmmmmmm. I can see why it's erroring here, but what *should* happen when `stdout` isn't open?

**Comment by ogham** [comment]
I've decided to close this because it should actually be a panic: http://roscidus.com/blog/blog/2013/06/09/choosing-a-python-replacement-for-0install/#safety
