### ISSUE TITLE
exa shows no color when run as an alias

### ISSUE THREAD

**Issue by MohamedElm1678** [ogham/exa#501]
So I have a file full of aliases and wanted to add this to replace ls. I use oh-my-zsh. When it was added, the command ran but no color showed ever.

**Comment by sesar54** [comment]
I cant replicate the issue. I added "alias ls='exa'" in my dot-alias file but color still works fine. I run bash. 

Can it be that your aliasfile or script calling it removes color? 
Do you have any other alias that does work with color?

**Comment by estoycon** [comment]
I ran into the same problem, however in my case I had to provide the full path to exa in the alias for coloring to work correctly. 
alias ls='/usr/local/bin/exa'

**Comment by ogham** [comment]
Gotta be honest, I have no idea what would cause something like this to happen.

@MohamedElm1678, is this still happening? What happens when you run `which exa`?

**Comment by GodGMN** [comment]
Hello, I'm having this issue too. I'm trying to understand the reason without much success.

Writing `exa -1` shows color. Writing `alias ls="exa -1"` and then `ls` does show color too.

However, when using zsh, modifying the .zshrc file to add `alias ls="exa -1"`, logging out and then logging in back so changes apply and then using `ls` shows no colors.

That said, some flags do work properly. `alias ls="exa -1 --long" _does_ show color for example.

I tried using the full path without success. In my case, when using `which exa` it says `/usr/bin/exa`.

I'm on Debian, ARM (Raspberry Pi 4)

**Comment by JiiXu** [comment]
I'll just chime in and say I have this bug too, so people aren't imagining things.
![image](https://user-images.githubusercontent.com/67114086/190261921-cdd8ff4e-9f59-4656-af2b-2eb4c8d8a58d.png)
![image](https://user-images.githubusercontent.com/67114086/190261974-a19ea807-ca03-466e-a0fb-b39add23fe2f.png)

**Comment by JiiXu** [comment]
Putting the lines
```
alias ls=exa
alias lsa='exa -lah'
```
*after* `source $ZSH/oh-my-zsh.sh` in my `.zshrc` fixed this issue for me, so I guess oh-my-zsh has something to do with it.

**Comment by ariasuni** [comment]
I never had the problem, even though I use several aliases for exa, so I’m guessing that it has something to do with your shell. What does the `alias` command gives you for `ls` and `lsa` when you put the alias before `source $ZSH/oh-my-zsh.sh`?

**Comment by antonkesy** [comment]
Agreeing/confirming with/for @ariasuni @KroqueJa 

I've encountered the same issue with zsh, and I was able to fix it.

I put the alias definition at the end of the `.zshrc` file due to conflicts with the default definitions made by Oh My Zsh.

Before (aliases still at top):
```
where l
l: aliased to ls -la
```

After (aliases last in `.zshrc)
```
where l
l: aliased to exa -lah
```
