### ISSUE TITLE
Feature Request: Print something more with standalone '--git' option

### ISSUE THREAD

**Issue by nilscript** [ogham/exa#502]
Running "exa --git" provides the same output as "exa". At first I thought "--git" was broken but running it together with "--long" shows that it's working.

Maybe color the output of files tracked by git or update the man page and mention that "--git" must be run together with other options.

**Comment by ariasuni** [comment]
In the man page, the `--git` option is listed under the “LONG VIEW OPTIONS” section stating: “These options are available when running with --long (-l)”. I guess the fact that not-applicable combinations of flags makes this confusing, though, but it’s made to be easy to override options from aliases.

**Comment by ogham** [comment]
ariasuni is correct here — I appreciate that it can be confusing when you first encounter it, but it allows aliases, and lets exa work the same way as other command-line tools, including other versions of `ls`.
