### ISSUE TITLE
Print output despite error message

### ISSUE THREAD

**Issue by chronaeon** [ogham/exa#503]
I was thinking about this message: `Option --across (-x) is useless given option --long (-l)` -- instead of having to re-enter the same command minus the "-x", exa could output the request as normal, then if it seems good to keep this error message to help the user out, perhaps append it to the beginning or end of the otherwise normally outputted `exa` data.

**Comment by ogham** [comment]
This was also #476, which I just fixed in the code and will go out with the next release. That message should only have been printed if strict mode enabled, but it wasn't being checked in this particular case.
