### ISSUE TITLE
Times headed by zero (such as 00:11) are incorrectly printed (they show up as 0:11)

### ISSUE THREAD

**Issue by jorgedfbranco** [ogham/exa#506]
Hi,

When running `exa --tree --long` I get:

![image](https://user-images.githubusercontent.com/677887/58994187-f17dd580-87ef-11e9-8872-19a19f2942e0.png)

while `ls -l` will show 00:11.

Thanks,
Jorge

**Comment by ogham** [comment]
A fix has been merged and will go out with the next release.
