### ISSUE TITLE
Color `__pycache__` folders like compiled files

### ISSUE THREAD

**Issue by mxmerz** [ogham/exa#520]
`__pycache__` folders [hold compiled Python code](https://stackoverflow.com/questions/16869024/what-is-pycache) - I would like to see them colored like `*.pyc` and `*.pyo` files, i.e. as compiled files. I tried to implement this by adding a corresponding `else if`-statement to `fn is_compiled` in `src/info/filetype.rs`, but this doesn't seem to work.

So I have two questions:
1. Is this a feature exa would want to have?
2. If yes, I would like to help realize this by providing a PR. How would I go about implementing it?

**Comment by ogham** [comment]
This is a tricky one — even though `__pycache__` is a well-known directory name that's a compilation artefact, it would be an edge case of being the only _directory_ that does this. As such, I'd rather exa highlight all directories the same by default, so there's no way they can be confused with files.

In the future there will be the option to customise directory name colours using the `EXA_COLORS` mechanism, so you will be able to do this for yourself if you want. This is being tracked in #729.
