### ISSUE TITLE
Why --modified .. doesn't actually work?

### ISSUE THREAD

**Issue by psprint** [ogham/exa#521]
Hello,
I'm enterring `exa -lh --modified` and seeing the files beautifully sorted ... **by name**! What's going on?

**Comment by ogham** [comment]
Hi,

The `--modified` flag tells exa to display the Date Modified column in long view. If you want to sort them by date, you can use `--sort modified`, or one of its aliases, `date`, `time`, and `newest`.

**Comment by psprint** [comment]
Thanks and sorry for my ignorance ;)
