### ISSUE TITLE
Why does -l effect dissapear when piping?

### ISSUE THREAD

**Issue by psprint** [ogham/exa#522]
Hello,
when I do `exa -lh -G | head` then the listing isn't long anymore. **Why??**

**Comment by ogham** [comment]
If you pipe exa's output to another command, exa will be unable to determine the size of the terminal it's running in; without the size, it has no idea how many columns to draw! Many terminal programs will behave differently when piped, usually by disabling colours or having less formatting.

See the FAQ on this page: https://the.exa.website/features/grid-view

**Comment by psprint** [comment]
Yes, but the output is actually long normally with those options, not grid. So shouldn't exa keep this property when piped?

**Comment by ogham** [comment]
Oh, I see what you mean! `exa -lh -G | cat` uses the lines view and `exa -lh | cat` uses the long view when they should both use the long view.
