### ISSUE TITLE
Are people supposed to use exa as a library

### ISSUE THREAD

**Issue by ignatenkobrain** [ogham/exa#523]
Since exa could be used asa `use exa::*`, is it expected or not?

**Comment by ogham** [comment]
It's possible, but it's not really expected. exa is written as a binary that's just a thin wrapper around a library, because I think the code is better written that way.

**Comment by ignatenkobrain** [comment]
@ogham I'm just curious if should package -devel (basically source code) parts for exa or not in Fedora.

**Comment by ogham** [comment]
Oh, I see! I would not create a separate -devel package. The library only has one use case and that's to build the exa binary.

**Comment by ignatenkobrain** [comment]
@ogham would it be possible to somehow restructure code so that cargo does not think you can use it as a library? For example, riprep and other tools don't have this problem.
