### ISSUE TITLE
core dump on option --long

### ISSUE THREAD

**Issue by jerome-diver** [ogham/exa#524]
archlinux OS, exa version 0.8.0
![exa core dump](https://user-images.githubusercontent.com/11176132/61214744-ebeea600-a732-11e9-916a-30d4acc1dbb6.png)

**Comment by ogham** [comment]
This should be fixed with v0.9.0 (which was released earlier today).

Can you confirm you're on v0.8.0?

**Comment by ogham** [comment]
This is #517. The fix for this was released in v0.9.0 earlier today.
