### ISSUE TITLE
manpage missing --icons

### ISSUE THREAD

**Issue by lilyball** [ogham/exa#527]
#368 added a new `--icons` flag but this isn't reflected in the manpage.

**Comment by lilyball** [comment]
The shell completions are missing it too.

**Comment by devurandom** [comment]
`❯ exa --help | grep icons` also has empty output...

**Comment by SuperSandro2000** [comment]
This should really be added because it makes discovering that option really hard.

**Comment by ariasuni** [comment]
As you can see, it’s in the man page now:
https://github.com/ogham/exa/blob/master/man/exa.1.md

Only thing is that documentation needs to be improved because it doesn’t tell you need to use Nerd fonts.
https://github.com/ogham/exa/issues/568#issuecomment-753356833
