### ISSUE TITLE
--icons should color the icon too

### ISSUE THREAD

**Issue by lilyball** [ogham/exa#528]
The new `--icons` flag (added in #368) adds icons, but they're not colored. They should pick up the same color as the filename.

**Comment by lilyball** [comment]
I just ran across a single file where it was colored. A `.pdf` file, which apparently has custom exa coloring, also colored the icon. It seems colors specified with file globbing in general apply to the icon, but colors from filetype (e.g. directories) don't.

**Comment by pirate** [comment]
A minor issue that's not worth a new ticket for, it would be nice if it added a space between the icons and the names, it's too cramped right now imo:
```diff
- .rw-r--r--  48 squash staff 2019-07-24 20:52 -- 📃 pytest.ini
+ .rw-r--r--  48 squash staff 2019-07-24 20:52 -- 📃  pytest.ini
```

**Comment by Azumgi** [comment]
@pirate There's actually an opened issue just for that (#541)

**Comment by ddelange** [comment]
Re @lilyball : I'm also puzzled as to the coloring of icons. First `md` gets colored, second doesnt:

![image](https://user-images.githubusercontent.com/14880945/81545208-d3faa980-9378-11ea-9785-651ed8dcc023.png)

**Comment by lilyball** [comment]
@ddelange README.md is special-cased (well actually it looks like [any file whose name starts with "readme"](https://github.com/ogham/exa/blob/df0d30e966657461a72cde122de417760d1e518c/src/info/filetype.rs#L23)) as an "immediate file". This category is apparently for "something that can be run or activated somehow in order to kick off the build of a project". I suppose README is included because it typically has the instructions for how to build.

I don't see LICENSE special-cased anywhere. Or COPYING. They're certainly common files, but I guess they don't match any of exa's preexisting categories.

**Comment by AndydeCleyre** [comment]
I just want to add my opinion that, in coloring the icons as the item text, any other style elements (or at least bold-ness) should *not* be applied to the icon, as bold symbolic icons are often drastically less legible.

**Comment by ogham** [comment]
I just made these changes:

- Icons now take the foreground colour of the file name, no matter what
- They no longer take attributes like bold or italic

And I think it looks much better:

![Screenshot 2020-10-24 at 18 17 14](https://user-images.githubusercontent.com/503760/97087874-26790b00-1625-11eb-8890-264837b9036b.png)
