### ISSUE TITLE
Crash with -l *

### ISSUE THREAD

**Issue by cecton** [ogham/exa#532]
I have the issue in 0.9, I have not tested the others:

```
[0] [11:39:59] /tmp > mkdir a
[0] [11:40:01] /tmp > cd a
[0] [11:40:03] /t/a > touch 1
[0] [11:40:04] /t/a > exa -l 1
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /checkout/src/liballoc/vec.rs:1555:10
note: Run with `RUST_BACKTRACE=1` for a backtrace.
fish: “exa -l 1” terminated by signal SIGABRT (Abort)
[134] [11:40:08] /t/a > exa 1
1
```

**Comment by printfinn** [comment]
same here


with newly installed Archlinux yesterday

``> exa -l``

``thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /build/rust/src/rustc-1.33.0-src/src/libcore/slice/mod.rs:2455:10
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
fish: “exa -l” terminated by signal SIGABRT (Abort)``

**Comment by ogham** [comment]
@printfinn: if you're using exa v0.8.0 I recommend you download the latest version — it fixes that exact error message.

@cecton: the fact that you're getting that error in v0.9.0 worries me! Could you set `RUST_BACKTRACE=1`, run it again, and paste me the error trace? thanks.

**Comment by cecton** [comment]
Will do! ty!

**Comment by cecton** [comment]
Errhh... I messed up with my PATH and I had 2 versions of exa installed. Sorry for the noise!

**Comment by ogham** [comment]
That is the best possible outcome

**Comment by printfinn** [comment]
> @printfinn: if you're using exa v0.8.0 I recommend you download the latest version — it fixes that exact error message.
> 
> @cecton: the fact that you're getting that error in v0.9.0 worries me! Could you set `RUST_BACKTRACE=1`, run it again, and paste me the error trace? thanks.

Thanks! The ArchLinux community has upgraded exa package (maintained by volunteer) to v0.9.0 today, everything works fine now!
