### ISSUE TITLE
Panic when use with "-l"

### ISSUE THREAD

**Issue by PierreLeidbring** [ogham/exa#538]
When invoking exa with the command `exa -l` it panics and gives the following error message:
```
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /build/rust/src/rustc-1.33.0-src/src/libcore/slice/mod.rs:2455:10
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
Aborted (core dumped)
```

Run on Manjaro-i3.
Kernel: `4.19.45-1-MANJARO`
Terminal: Alacritty

If more information is needed please tell me and I'll provide it.

**Comment by ogham** [comment]
I'm willing to bet you're using exa v0.8.0, because v0.9.0 was released to fix this exact problem (#517). Could you try upgrading and seeing if the problem goes away?

**Comment by PierreLeidbring** [comment]
Ah! I missed the release of v0.9.0 since pacman only lists v0.8.3
I'll try upgrading manually.

**Comment by codeitlikemiley** [comment]
please update arch repo to latest version so we dont have to manually download the release

**Comment by ogham** [comment]
The Arch package has been flagged as out-of-date on the 15th — they're working on it.

**Comment by printfinn** [comment]
@PierreLeidbring @codeitlikemiley 
It works on ArchLinux now! Community maintainers have updated exa to v0.9.0, `pacman -Syu` now!

**Comment by maximbaz** [comment]
@ogham I can still reproduce this issue with v0.9.0 on Arch Linux, but only if I provide `exa --git -l` (on their own `exa --git` or `exa -l` work fine), and only in some git repos.

```
❯ export RUST_BACKTRACE=1

❯ exa --git -l
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:997:5
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: start_thread
  16: __clone
[1]    27879 abort (core dumped)  exa --git -l
```

Any ideas what might be wrong?
