### ISSUE TITLE
Panic using option --long when built without default features

### ISSUE THREAD

**Issue by mgee** [ogham/exa#55]
When building exa with `--no-default-features` and running exa with `--long` it panics.
`rustc 1.0.0-nightly (123a754cb 2015-03-24) (built 2015-03-25)`

```
$ exa --long
thread '<main>' panicked at 'No option 'git' defined', <somepath>/getopts-0.2.5/src/lib.rs:700
```

**Comment by ogham** [comment]
Sorry, I've been super busy in real life. I'll fix this next week.
