### ISSUE TITLE
brew install takes ages..

### ISSUE THREAD

**Issue by cmpscabral** [ogham/exa#551]
HI,
Trying to install exa with "brew install exa" and it's stuck on building rust.

For what I've read, it's building rust from source (which, understandably takes hours on my 2015 MBP).

Can you configure this dependency as "download rust binary" instead of building from source? It seems to be possible -> https://github.com/rust-lang/rust/issues/39576

**Comment by bknowles** [comment]
@cmpscabral -- I'm curious, can you define what length of time "ages" corresponds to in your case?  Running the same command on my machine takes just 12.0 seconds, even with having to re-download the bottle from https://homebrew.bintray.com/bottles/exa-0.9.0.mojave.bottle.tar.gz

This is even with an additional automatic `cleanup` run at the end:
```
$ /usr/bin/time brew install exa
==> Downloading https://homebrew.bintray.com/bottles/exa-0.9.0.mojave.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/bc/bc80009ad845d914c08e6de1c39c97e0f4f180ef4f077b3ef1957cab519d6743?__gda__=exp=1564
######################################################################## 100.0%
==> Pouring exa-0.9.0.mojave.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/exa/0.9.0: 9 files, 1.4MB
==> `brew cleanup` has not been run in 30 days, running now...
       10.93 real         5.16 user         5.88 sys
```

**Comment by bknowles** [comment]
Note that my system did not have `rust` pre-installed, and installing `exa` did not attempt to install `rust` in order to build it.  I'm pretty sure it just downloaded a binary that was pre-built and installed that.

Now, if you have a machine where a pre-built binary is not available, then I can understand why brew might need to install `rust` first in order to build `exa`, but I don't think that's a problem that the `exa` developers can help you with.

**Comment by bknowles** [comment]
Even if we include downloading and installing `rust` and `libssh2` as a dependency, with an automatic `brew cleanup` forced at the end, the whole process of doing that doesn't take very long:

```
$ /usr/bin/time brew install rust
==> Installing dependencies for rust: libssh2
==> Installing rust dependency: libssh2
==> Downloading https://homebrew.bintray.com/bottles/libssh2-1.9.0.mojave.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/02/0226917e00c2f5c003c441c11d06852d582cd6ddcb42042bf1f82515623528d5?__gda__=exp=1564
######################################################################## 100.0%
==> Pouring libssh2-1.9.0.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/libssh2/1.9.0: 184 files, 911.9KB
==> Installing rust
==> Downloading https://homebrew.bintray.com/bottles/rust-1.36.0.mojave.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/13/13b650304f6160d33629cf638ec955ec00f8e054651e4fdf128528f04bc22f40?__gda__=exp=1564
######################################################################## 100.0%
==> Pouring rust-1.36.0.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/rust/1.36.0: 26,366 files, 784.7MB
==> `brew cleanup` has not been run in 30 days, running now...
       85.27 real        22.77 user        39.39 sys
```

That's less than 90 seconds.  But again, I think that assumes you have a supported configuration where they can do a binary install.

**Comment by ogham** [comment]
Homebrew should really be doing binary releases by now.

**Comment by ariasuni** [comment]
Could you provide the command you used? Brew is distributing exa’s binaries for every supported platforms [according to their website](https://formulae.brew.sh/formula/exa#default)…

**Comment by olivertzeng** [comment]
> according to their website

me too having the same problem
i now currently dont have the logs
you can do `brew install -v exa`

**Comment by olivertzeng** [comment]
> > Homebrew should really be doing binary releases by now.
> 
> /usr/local/Cellar/rust/1.67.0: 36,041 files, 899.5MB, built in **107 minutes 25 seconds**
> 
> on Macbook Pro mid-2014.

if you are in catalina or lower, executables isn't avalible. so do `rust install exa`
