### ISSUE TITLE
Don't display file byte counts with thousands separator

### ISSUE THREAD

**Issue by bknowles** [ogham/exa#554]
Folks,

When using the `-B` option with `exa -l`, the output will include actual byte counts for each file in question, but those byte counts will include a thousands separator.  This is inconsistent with the behaviour of `/bin/ls` when providing byte counts, and would require that a developer using this command as part of a pipeline will need to be able to detect the thousands separator and remove it, if they are going to try to do any calculations on this number.

I understand the desire to be able to display a large number with a thousands separator, but I do not believe that this should be the default in this case.

Of course, I'm assuming that if you do provide a thousands separator, that this is language and locale appropriate, so while we might see a comma here in the US, other places might see a simple space character or a period or some other character that the language/locale specifies as the thousands separator.

**Comment by ogham** [comment]
> Of course, I'm assuming that if you do provide a thousands separator, that this is language and locale appropriate, so while we might see a comma here in the US, other places might see a simple space character or a period or some other character that the language/locale specifies as the thousands separator.

It does indeed [go through the locale routines](https://github.com/ogham/exa/blob/03cd3a81ff00b0e1dba095e5e8923ea365b5e2b0/src/output/render/size.rs#L32).

I'm going to defer this issue to the very old feature request #13, which is to provide some sort of structured output, which will probably be JSON. Tools like `exa` and `ls` certainly look almost-machine-parseable, but having them be _fully_ machine-parseable is not a road I want to go down without an explicit flag to enable this mode.

**Comment by themadsens** [comment]
The thousand sep behaviour is extremely obnoxious when cutting/pasting into calculations. 
Please consider a flag to control this
