### ISSUE TITLE
[Question] What does exa stands for?

### ISSUE THREAD

**Issue by ghost** [ogham/exa#571]
[Question] What does exa stands for?

**Comment by AntonHermann** [comment]
Maybe "examine"?

**Comment by samueldple** [comment]
Could also reference its better ability than `ls` to handle larger data and be based on the [SI prefix](https://en.wikipedia.org/wiki/Exa-)?

**Comment by ogham** [comment]
It stands for _integrity_

It stands for _compassion_

It stands for _not answering github issues for a long time_

But it also stands for "examine"
