### ISSUE TITLE
Feature request: explain Git letters in the manpage

### ISSUE THREAD

**Issue by adiabatic** [ogham/exa#578]
I ran `exa -l --git` in one of my projects' directories and I'm not sure what this dimmed-out `I` in the second column means. My _guess_ is that it means "some items in this directory are covered by a .gitignore rule".

**Comment by daviessm** [comment]
https://github.com/ogham/exa/blob/master/src/output/render/git.rs#L29 seems to suggest you're right about 'I'.

**Comment by hrlmartins** [comment]
yep, that is it.

**Comment by ariasuni** [comment]
I didn’t notice there was already an opened bug report about this. I’m closing this one in favor of #778 to avoid duplicates.
