### ISSUE TITLE
Feature: add --group-directories-first option

### ISSUE THREAD

**Issue by tsurai** [ogham/exa#58]
GNU ls has an option called --group-directories-first which groups directories before files and then applies other sorting options. This is currently not possible unless I'm missing something.
I personally use that option on all my machines because I prefer to have directories and files listed separate from eachother.

If this feature is wanted I'll implement it and open a pull request. Unless you would prefer to do it yourself of course.

**Comment by ogham** [comment]
Aaaah, we have `--group-directories-first`! It was implemented in #27. But you probably didn't see it, as it's missing from the README. I'll just go fix that.
