### ISSUE TITLE
tab completion not working

### ISSUE THREAD

**Issue by patrick-motard** [ogham/exa#585]
Using exa, oh-my-zsh, and zsh, i get the following when attempting to tab complete a directory using ls:
```
ls /usr/           
(eval):1: _exa: function definition file not found
(eval):1: _exa: function definition file not found
(eval):1: _exa: function definition file not found
```

I expect to see something similar to `cd`'s output:

```
cd /usr/
bin/      include/  lib/      lib32/    lib64@    libexec/  local/    sbin@     share/    src/      var/    
```

**Comment by jpninanjohn** [comment]
I am not able to replicate this issue. Tab completion seems to be working for me.

**Comment by patrick-motard** [comment]
It's working for me right now. I'll keep testing to see if i can get it to happen again. If I can't, I'll follow up on this and close it.

**Comment by nickdex** [comment]
For me tab completion works for files/folders but can't seem to get any flag (- or --) completion. 
I'm using omz and zsh as well.

**Comment by ecanja** [comment]
I had the same problem with zsh and omz.

How did you install exa? I had to install it manually (see "Manual installation" under https://the.exa.website/install/linux).

I somehow extracted a solution out of [this issue](https://github.com/zsh-users/zsh-completions/issues/277). omz's compinit process seems to somehow break adding completion files manually (see [apjanke's comment](https://github.com/zsh-users/zsh-completions/issues/277#issuecomment-157191280)), but [this](https://github.com/zsh-users/zsh-completions/issues/277#issuecomment-72867242) helped. The exa completion file also has a hint:

```
# Save this file as _exa in /usr/local/share/zsh/site-functions or in any
# other folder in $fpath.  E. g. save it in a folder called ~/.zfunc and add a
# line containing `fpath=(~/.zfunc $fpath)` somewhere before `compinit` in your
# ~/.zshrc.
```

So what I did in the end was:

1. Download the exa completion file for zsh (from [here](https://the.exa.website/install/linux))
2. Move this file to `/usr/local/share/zsh/site-functions` (which was also in my `fpath`, so no action needed here)
3. Rename it to `_exa`.
4. Add the command `compinit` to the `.zshrc` somewhere BELOW where `oh-my-zsh.sh` is sourced.

I actually added
```
rm -f ~/.zcompdump
autoload -Uz compinit
compinit
```
to my `.zshrc` (recommended by some Stackexchange threads), though it seems not necessary for solving the exa completion issue.

Up to now everything seems to work fine, so I hope this didn't break anything as indicated in [apjanke's comment](https://github.com/zsh-users/zsh-completions/issues/277#issuecomment-157191280).

**Comment by arkban** [comment]
Posting in case it helps someone else: I too had to manually add the exa completion file for zsh (from [here](https://the.exa.website/install/linux)), put it somewhere in my `fpath`, rename it to `_exa`, and made sure `autoload -U +X compinit && compinit` was in my `~/.zshrc` file, below where I've added OMZ's completion and `zsh-completion` are installed.

I also found that the file has to be named `_exa`, it can't be named `completions.zsh` like the original filename. (That might be totally obvious to everyone else but it wasn't to me.)

**Comment by crazy-matt** [comment]
Not able to make it work on my side, using Zinit, not picking up any flag (- or --) completion similarly to @nickdex .

**Comment by ariasuni** [comment]
Closing this in favor of #451.

**Comment by nemonein** [comment]
ecanja's method works, but it takes several seconds.
I've found [another suggestion](https://gist.github.com/ctechols/ca1035271ad134841284?permalink_comment_id=3994613#gistcomment-3994613), but it does not work for me.
```
autoload -Uz compinit
for dump in ~/.zcompdump(N.mh+24); do
  compinit
done
compinit -C
```

I'm using zsh omz on Ubuntu 20.04. I installed exa manually.

There are 2 solutions for this to work.
First, copy _exa to /usr/local/share/zsh/site-functions
`sudo cp _exa /usr/local/share/zsh/site-functions`

Second, copy _exa to ~/.oh-my-zsh/completions/. However, you must make this directory first.
```
mkdir ~/.oh-my-zsh/completions/
cp _exa ~/.oh-my-zsh/completions/ 
```
`autoload -Uz compinit ;; compinit` is not needed on .zshrc.

Auto completion `exa --<tab>` works fine, and zsh init time takes just a second.

**Comment by rostislaved** [comment]
If you have alias like this:
alias ls="exa"
try to replace it:
alias ls="eza"

I had the same problem. I installed exa via pacman and created an alias:
alias ls="exa"
but later I found out that there is no exa in repo and eza (community fork of unmaintained exa) is actually installed. This installation also create a soft link in /usr/bin/exa -> /usr/bin/eza, so exa command continue to work, but not with the alias.

**Comment by paulb-smartit** [comment]
On Manjaro

```shell
cd /usr/share/zsh/site-functions
sudo ln -s _eza _exa
```

**Comment by GannonTdW** [comment]
> On Manjaro
> 
> ```shell
> cd /usr/share/zsh/site-functions
> sudo ln -s _eza _exa
> ```

thx.

Or one line:

```bash
 sudo ln /usr/share/zsh/site-functions/{_eza,_exa}
```

**Comment by redeemefy** [comment]
I'm on mac and I just did `brew uninstall exa` and `brew install exa` and everything start working again
