### ISSUE TITLE
build fails on openssl-sys

### ISSUE THREAD

**Issue by mackenza** [ogham/exa#59]
I downloaded the latest nightly and fresh clone of exa. Also removed my .cargo folder to start fresh with new downloaded dependencies.
`make install` yields:
```
Compiling openssl-sys v0.6.0
Build failed, waiting for other jobs to finish...
failed to run custom build command for `openssl-sys v0.6.0`
Process didn't exit successfully: `/home/mackenza/exa/target/release/build/openssl-sys-d9a1dd4f363aedb0/build-script-build` (exit code: 101)
--- stdout
cargo:rustc-flags=-l dylib=crypto -l dylib=ssl
TARGET = Some("x86_64-unknown-linux-gnu")
CARGO_MANIFEST_DIR = Some("/home/mackenza/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.6.0")
OUT_DIR = Some("/home/mackenza/exa/target/release/build/openssl-sys-d9a1dd4f363aedb0/out")
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("3")
PROFILE = Some("release")
release 3
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = None
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = None
running: "cc" "-O3" "-c" "-ffunction-sections" "-fdata-sections" "-m64" "-fPIC" "/home/mackenza/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.6.0/src/old_openssl_shim.c" "-o" "/home/mackenza/exa/target/release/build/openssl-sys-d9a1dd4f363aedb0/out/src/old_openssl_shim.o"


command did not execute successfully, got: exit code: 1
```
cargo 0.0.1-pre-nightly (72c2e3d 2015-04-10) (built 2015-04-12)
rustc 1.0.0-nightly (47def3ef2 2015-04-13) (built 2015-04-13)

**Comment by ogham** [comment]
Gah, this works for me, making it really hard to diagnose. Are you able to compile https://github.com/alexcrichton/git2-rs, at least?

If not, you can still run `cargo build --release --no-default-features` to compile exa without needing that dependency.

**Comment by mackenza** [comment]
I have successfully built exa now on 2 different Ubuntu laptops. I am not sure exactly which step made it work but I did the following:

`apt-get install libssl0.9.8 libssl-dev libgit2-0`

I also tried to build `git2-rs` standalone before trying exa and was successful.

So... it all built fine and I aliased ls with exa and it's great... except...

my listings give no git columns?!? Am I missing something? I `cd exa` which is a git folder and run something like you show on the homepage like `ls -bghHliS and I get everything except the git column :( Ideas?

**Comment by ogham** [comment]
Oh, yeah, you need to pass in the `--git` parameter to show the Git columns now. There's a performance issue with viewing the column in large repositories, and as viewing files is a common operation, it should really be fast by default.

Let me just update the homepage...
