### ISSUE TITLE
brew install exa --without-git

### ISSUE THREAD

**Issue by gMan1990** [ogham/exa#595]
`--without-git` what's it mean? where is the document, I can't find it.

**Comment by mschilli87** [comment]
From the [README](https://github.com/ogham/exa#installation):

> exa depends on libgit2 for certain features. If you’re unable to compile libgit2, you can opt out of Git support by running cargo build --release --no-default-features.

Checking `Cargo.toml` you'll find:

https://github.com/ogham/exa/blob/479fdea02cf3b6555911b8f3f8db4827c4f3b052/Cargo.toml#L56-L59

So `--without-git` and `--no-default-features` seem to do one and the same thing which is to disable the support for Git for your build of exa.

Which features will be affected by this should pretty obviuous if you know what Git is/does. But I'm not aware of any document explicitely listing them.

**Comment by ogham** [comment]
[Homebrew has removed options for those in homebrew-core](https://brew.sh/2019/02/02/homebrew-2.0.0/) so you won't be able to use the `--without-git` flag anymore. It's still there as a Cargo feature however.
