### ISSUE TITLE
Request: Mac support

### ISSUE THREAD

**Issue by jc21** [ogham/exa#61]
Would love to have Mac support for this, using Brew most likely.

**Comment by ogham** [comment]
I'd like this too, but I have no idea how to go about making a Homebrew thing! Can anyone give me any pointers?

**Comment by Teovald** [comment]
I don't see why you would need homebrew, you can compile/execute Rust on OsX.

**Comment by ogham** [comment]
You can, no problem (and that's what I do). But it's nice to have both an easy way to update, and an easy way to uninstall them.

**Comment by iKevinY** [comment]
Since @ogham is uploading binaries of exa using GitHub's releases functionality, I'm currently working on writing a [Cask](https://github.com/caskroom/homebrew-cask). It would be nice to be able to just have a regular Homebrew formula, but I'm not entirely sure if Homebrew is compatible with compiling *any* Cargo programs at the moment.

**Comment by ogham** [comment]
What's kind of amusing is that it says `github.com is the official download host per the vendor homepage`, but I wrote the homepage before I started doing official releases, so the page said nothing at all about where you could get binary downloads! I just updated the homepage, so your comment is now correct.

**Comment by iKevinY** [comment]
No worries; thanks for updating the homepage to match the comment!

**Comment by dacresni** [comment]
Is this still an issue?

**Comment by jc21** [comment]
Not for me anymore. I just didn't want to have to compile for osx and now I don't have to. Installation via brew would be a bonus, but I don't need that to move forward.

**Comment by ogham** [comment]
I personally use the Homebrew Cask version, but I'm leaving this issue open so one day we can have Homebrew nightly builds available

**Comment by santagada** [comment]
is the cask version working on macOS 10.12.3 for you? I received error #140 when I tried.

**Comment by iKevinY** [comment]
@santagada Yeah, the current cask is broken on Sierra. When a new version of `exa` is released, I plan on submitting an updated formula (see #143).

**Comment by santagada** [comment]
should this wait a release? not supporting latest stable macOS seems like a big problem.

**Comment by iKevinY** [comment]
The issue is that the cask needs to download the binary from somewhere (which is currently just the GitHub release page). I suppose I could temporarily fork `exa` and publish a "new release" based on the current `master` — not sure what the etiquette around doing something like this is, though.

**Comment by santagada** [comment]
apparently the owner hasn't made a commit in 5 months... you don't need to wait anymore to make your fork. If the repo owner wants to  go back to update this he can just comment on this ticket and ask you to close your fork... now I really like the features of this but wanted to extend it... maybe I should do the same.

**Comment by iKevinY** [comment]
If I get a chance this weekend, I'll see what I can do regarding forking `exa` and updating the formula. As I mentioned in #143, I also wanted to change the formula from a cask to a regular formula, so I might have to do a bit of research on how to go about doing this.

**Comment by iKevinY** [comment]
Good news: `exa` has been officially added to Homebrew! 🎉 

@ogham: It might be worth updating the website to reflect the fact that you can now just run `brew install exa` (it doesn't require Homebrew Cask anymore).

**Comment by jc21** [comment]
Awesome, works perfectly :)

**Comment by vitorgalvao** [comment]
This issue can now be closed, as `exa` is now a formula.

I’ve opened [a small issue](https://github.com/ogham/exa/issues/148) on what needs to change on the website.

**Comment by ogham** [comment]
```
$ brew --prefix exa
/usr/local/opt/exa
```

_yussss_

Thanks so much for dealing with this.
