### ISSUE TITLE
Panic when temp_dir does not exist

### ISSUE THREAD

**Issue by piegamesde** [ogham/exa#615]
https://github.com/ogham/exa/blob/9fcd7ad1502ab10cb3f50e92a2637bfe6e0fc8cc/src/fs/file.rs#L475

This is a bad idea. `temp_dir` may return a path that does not exist. `metadata()` will fail in this case, panicking the whole application. Please don't assume "this won't ever happen" and `unwrap()`.

**Comment by ogham** [comment]
The `temp_dir` code is going away so this should cease to be a problem next release.
