### ISSUE TITLE
exa shows header line in fish shell, even when I don't have it declared

### ISSUE THREAD

**Issue by Trollwut** [ogham/exa#628]
Hey folks!

Have used awesome `exa` for a while under bash now and I love it. I'm currently transisting to fish shell and have a phenomenon.

These are my `.bashrc` aliases:

```bash
alias ls='exa --group-directories-first --git --icons'
alias ll='ls -l'
alias la='ls -la'
```

I guess they're pretty straight-forwarded. It doesn't matter which one I use, none of them show a header line, as expected.

Now I'm not a pro, but I tried to mirror this into my fish config:

```fish
function ls -d 'exa instead of ls'
    exa --group-directories-first --git --icons $argv
end

function ll -d 'alias ls -l'
    ls -l $argv
end

function la -d 'alias ls -la'
    ls -la
end
```

`exa` is being executed, as like the bash aliases, but with `ll` and `la` it *always* shows a header line on the output, where I have neither `-h` nor `--header` set. There's not even a single `h` in the code!

When I invoke `exa -la` directly in fish, everything's normal without a header.

Is this a known problem, or did I something wrong?

**Comment by ogham** [comment]
This is a super weird issue! It's the first I'm hearing of it, unfortunately. I use fish too (3.1.0) and I’m unable to replicate the behaviour here.

Does it continue to happen if you start using [fish aliases](https://fishshell.com/docs/current/cmds/alias.html) rather than functions? The only thing I can think of is that _something_, _somewhere_ is creating an alias for `ls -lah`, which is a fairly common thing to have aliased.

Other than that, maybe running fish in debug mode will glean some more information.

**Comment by Trollwut** [comment]
That's starting in debug:

```
 fish --debug 4
<2> fish: exec_path: '/usr/bin/fish', argv[0]: 'fish'
<2> fish: Using compiled in paths:
<2> fish: determine_config_directory_paths() results:
paths.data: /usr/share/fish
paths.sysconf: /etc/fish
paths.doc: /usr/share/doc/fish
paths.bin: /usr/bin
<2> fish: curses var TERM='xterm-kitty'
<2> fish: curses var TERMINFO='/usr/lib/kitty/terminfo'
<2> fish: curses var TERMINFO_DIRS missing or empty
<2> fish: default emoji width: 2
<2> fish: sourcing /usr/share/fish/config.fish
<2> fish: 'fish_term24bit' preference: 24-bit color enabled
<2> fish: sourcing /etc/fish/config.fish
<2> fish: sourcing /home/trollwut/.config/fish/config.fish
```

The source file in `etc` is empty, the other one doesn't have occurences of `ls` or `exa`.

It gets even weirder:

I open a fish shell. I use the `la` command and get the header line. Now I do `funced la`, which opens it in vim, I immediately close it without changing and type in `la` again: header line is gone.

I'm confused right now. :D

**Comment by ariasuni** [comment]
Does it still happen to you?

**Comment by ogham** [comment]
I still use fish (3.2.0 now) and I'm unable to reproduce this.
