### ISSUE TITLE
Fedora package is lost

### ISSUE THREAD

**Issue by FranklinYu** [ogham/exa#634]
The `rust-exa` package on Fedora is lost: https://apps.fedoraproject.org/packages/s/rust-exa

**Comment by bexelbie** [comment]
It is now a module, https://src.fedoraproject.org/modules/exa

**Comment by FranklinYu** [comment]
The page says that last commit is “demodularizing“?

**Comment by ariasuni** [comment]
It seems like Fedora’s package is still here, so closing this.

**Comment by leogouveia** [comment]
@ariasuni Still can't find it on fedora 39. In the https://src.fedoraproject.org/modules/exa/blob/master/f/dead.package it says dead package, and it seems there no commit for 4 years.
