### ISSUE TITLE
--git-ignore parses paths beginning with / incorrectly

### ISSUE THREAD

**Issue by fofoni** [ogham/exa#636]
If `.` is the root of a Git repository, and I want to ignore `./file.txt` but not `./dir/file.txt`, I can add the line `/file.txt` to `.gitignore`. Git supports this, but exa does not.

**Comment by whitelynx** [comment]
I'm also running into this issue. In one particular project I work on, `.gitignore` has the line:
```
/node_modules
```
which doesn't work, and therefore if I run `exa --git-ignore --tree`, it pegs one CPU core and doesn't finish. (I've let it run for more than 5 minutes this way before killing it)

It works as expected if I instead run `exa --git-ignore --tree -I node_modules`.
