### ISSUE TITLE
Panics with --git option in home directory 

### ISSUE THREAD

**Issue by quentm74** [ogham/exa#642]
Exa panics when I try to use --git option on my home directory.
I have a git repository directly in my home directory, that is maybe the cause of the issue.

![image](https://user-images.githubusercontent.com/11525523/77585249-77385200-6ee4-11ea-9bdd-62383a15f0dd.png)

It seems that the panic comes from the fs::feature::git::reorient function.

**Comment by cyclowns** [comment]
Getting a similar issue but not in my home directory and RUST_BACKTRACE doesnt give much useful info 
![image](https://user-images.githubusercontent.com/19853115/78335487-8c475d80-7542-11ea-9de7-168b0916664b.png)

**Comment by tamanishi** [comment]
In my case. Not in my home directory, but in git repository. With -l option only.

<img width="1164" alt="Screen Shot 2020-04-05 at 10 40 56" src="https://user-images.githubusercontent.com/1237835/78464933-93c95b00-772a-11ea-9d89-79c2b9a3e04b.png">

**Comment by Freaky** [comment]
Looks like #526, which was fixed in #584.

@tamanishi That looks like #596, #592, and #658, which is fixed in #670.

**Comment by msorens** [comment]
I ran into the same panic (on macOS) -- but only in one directory in one repo.
The command I used was `exa -l --git`.

 - panics in the root directory of one particular repo (backtrace the same as shown by @tamanishi )
 - works fine in any subdirectory of that repo root.
 - works fine in any root or subdirectory of several other repos I have tried.

**Comment by ariasuni** [comment]
As @Freaky said, those issues are fixed already, there just hasn’t been a new release made since then (yet).
