### ISSUE TITLE
Exa fails on looped symlink

### ISSUE THREAD

**Issue by soanvig** [ogham/exa#644]
Bug

If I create symlink to the directory itself (e.g. in case of some typo or something) exa cannot list files:

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 40, kind: Other, message: "Too many levels of symbolic links" }', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
gdfish: Job 2, 'exa -lh --git --icons $argv' zakończony sygnałem SIGABRT (Przerwij)
```

**Comment by lknix** [comment]
This could be loosely related to #629

**Comment by viluon** [comment]
Can confirm that this is indeed an issue:
[![asciicast](https://asciinema.org/a/njVwP3ppSUnUOQnulfZsgq9ST.svg)](https://asciinema.org/a/njVwP3ppSUnUOQnulfZsgq9ST)

**Comment by ogham** [comment]
This should be fixed now. Thanks for the asciinema bug report!
