### ISSUE TITLE
--no-user not recognized

### ISSUE THREAD

**Issue by ptrcvc** [ogham/exa#647]
--no-user flag appears to not be implemented.

`exa --no-user`

results in

`Unknown argument --no-user`

**Comment by Starchery** [comment]
None of the following "long view" commands seem to be implemented as of 0.9.0-1:

```
--no-permissions: suppress the permissions field
--no-filesize: suppress the filesize field
--no-user: suppress the user field
--no-time: suppress the time field
```
Running `$ exa --help` doesn't display any of them either:
```
...
LONG VIEW OPTIONS
  -b, --binary       list file sizes with binary prefixes
  -B, --bytes        ...
  ...
  --git              list each file's Git status, if tracked or ignored
  -@, --extended     list each file's extended attributes and sizes
$
```

**Comment by yangxyo** [comment]
> --no-user flag appears to not be implemented.
> 
> `exa --no-user`
> 
> results in
> 
> `Unknown argument --no-user`

+1

**Comment by GregoireHENRY** [comment]
up

**Comment by TonioGela** [comment]
+1

**Comment by learn2reid** [comment]
+1

**Comment by Spark3000** [comment]
Was about to create issue about: `--no-permissions` not being available. Is this on the radar? As I like the colours of exa but the colours of permissions are a bit jarring.

**Comment by mathaou** [comment]
+1

**Comment by DuboisS** [comment]
Feature date from august 2019 (if we look the README.md history).
But no release since july 2019 :/

**Comment by ariasuni** [comment]
Closing this since its been implemented; please wait for the next release or compile exa yourself if you want the feature now.
