### ISSUE TITLE
Colored icons get cut off.

### ISSUE THREAD

**Issue by TehNewbie** [ogham/exa#648]
Hello! It's not that big of a problem, but icons tend to get cut off when color gets applied to their corresponding filetypes. I'm attaching a screenshot, take a look at the .rlib file. 

I'm using Iosevka Term here, the non-mono variant. Since the mono variant has smaller glyphs, the problem  disappears when using that instead, so there's that. Anyways, thanks for all your work, and take care!

![Screenshot_20200405_155522](https://user-images.githubusercontent.com/5496550/78503516-8e820580-7756-11ea-831f-7e988e1d7512.png)

**Comment by ariasuni** [comment]
It’s an issue in Konsole: https://bugs.kde.org/show_bug.cgi?id=422776.

It may not be unreasonable to add a workaround on exa’s side, by coloring the spaces that come after the icons too.
