### ISSUE TITLE
question: what program you have used to make your shell prompt in README screenshot?

### ISSUE THREAD

**Issue by mobop** [ogham/exa#649]
reference

**Comment by ogham** [comment]
Oops, I got the close notification but not the open one. And I'm afraid I don't have the code that generated the prompt anymore — but it's fish and would have been a regular `fish_prompt`, I think with `vcprompt` doing the Git stuff. Sorry!

**Comment by mobop** [comment]
never mind ☺

**Comment by mobop** [comment]
you can checkout starship , written in rust

**Comment by mobop** [comment]
https://github.com/starship/starship
