### ISSUE TITLE
Feature request: use a color scale for file sizes and dates (like k)

### ISSUE THREAD

**Issue by dancek** [ogham/exa#65]
See this pull request to `k` for an example: https://github.com/supercrabtree/k/pull/35

![Example screenshot with file sizes in different colors](https://cloud.githubusercontent.com/assets/245394/6278774/55de1048-b8a2-11e4-9a7a-cf487dafed34.png)

This seems to enhance usability; it's easy to spot the largest or most recent files at a glance, for example. Should also be easy to implement.

**Comment by ogham** [comment]
Nice idea!

**Comment by Joshfindit** [comment]
Eureka; this is exactly what I was looking for when I found exa.
Please also let it work for human readable sizes.

**Comment by ogham** [comment]
<img width="453" alt="screen shot 2017-05-16 at 20 57 18" src="https://cloud.githubusercontent.com/assets/503760/26125525/59cc2350-3a7a-11e7-8423-3bdc4f0b6bfa.png">

Fairly sure this was the last thing I had to do for this!
