### ISSUE TITLE
[Enhancement] Make the `I` indicator in the git column only apply to the gitignore matches

### ISSUE THREAD

**Issue by ghost** [ogham/exa#656]
Imagine you have a git repo with the following structure

```
foo
|
\- bar
|  |
|  \- baz
|     |
|     \- project.iml
|
\- baz
```
and a gitignore that just contains `*.iml`.

At the moment, `exa -al --git` in the `foo/bar/baz` directory will produce the following output
```
<perms> <size> <username> <date modified>  -I  project.iml
```
which is expected. However, `exa -al --git` also produces the `-I` for the `bar` folder when run in the `foo` directory, and the `baz` directory when run in the `foo/bar` directory.

I would have expected this feature to only apply to direct matches. If the intent was to indicate that a directory contains an ignored file, that's understandable. However, it makes the meaning of `-I` ambiguous

**Comment by ariasuni** [comment]
That’s right, it makes sense for other statuses but not for ignored.
