### ISSUE TITLE
Column alignment ruined by certain file sizes in binary mode

### ISSUE THREAD

**Issue by tatsujin1** [ogham/exa#657]
example: `exa -b -l`
```
.rw-rw-r--@      30Ki xyz 19 apr 23:02 msvcp140_1.dll
.rw-rw-r--@     200Ki xyz 19 apr 23:02 msvcp140_2.dll
.rw-rw-r--@ 1 002Ki xyz 19 apr 23:02 ucrtbase.dll
.rw-rw-r--@     357Ki xyz 19 apr 23:02 vccorlib140.dll
.rw-rw-r--@      83Ki xyz 19 apr 23:02 vcruntime140.dll
```
Sizes between 1000 and 1023 (with size suffix) have this problem. It seems that it compensates for the wider size, but in the "opposite direction".

Apologies for the windoze-related example. :)

**Comment by Freaky** [comment]
I can't reproduce this, neither with 0.9 nor master.  What version of `exa` are you using?

**Comment by tatsujin1** [comment]
Version 0.9.0.
I had an idea, which I just confirmed.
It happens when `LC_NUMERIC` is `sv_SE.UTF-8`, not with `en_US.UTF-8`.
Not sure why this would be, as the resulting formatting is the same (apart from the alignment).

**Comment by Freaky** [comment]
Can't seem to convince it to use a locale with space as a thousands separator here, maybe not hooked up on FreeBSD or something.

I wonder if that is actually a space, or if it's some other multibyte codepoint exa is misjudging the size of.

**Comment by Freaky** [comment]
And indeed, copy and paste finds it is in fact a `NARROW NO-BREAK SPACE`.

**Comment by tatsujin1** [comment]
Oh I see, nicely discovered!
How devious of them...

**Comment by ariasuni** [comment]
I accidentally removed the thousands separator so the alignment problem is «fixed» in exa 0.10.0 (#822).

**Comment by tatsujin1** [comment]
Heh, accidental fixes are always welcome! ;) I'll try it out later.

**Comment by tatsujin1** [comment]
Looks fine now, but without the separator, of course.
