### ISSUE TITLE
What is the dark color scheme in the screenshot in the project page? 

### ISSUE THREAD

**Issue by garret** [ogham/exa#661]
Sorry, I know it's not a real issue but I really like the color scheme (and font) of the terminal shown on the main Github page of the project. In particular, I refer to the dark color scheme. 

May I kindly ask to share the info? Thank you very much in advance.

**Comment by cata0309** [comment]
The font is [PragmataPro Mono](https://www.fsd.it/shop/)
I am interested too in what color scheme that is and also terminal emulator.

**Comment by ogham** [comment]
The terminal emulator is iTerm for macOS. The colours are [Tomorrow Theme](https://github.com/chriskempson/tomorrow-theme) but I shifted the colours around a little.
