### ISSUE TITLE
quick win: in place replacement fix

### ISSUE THREAD

**Issue by ReSearchITEng** [ogham/exa#672]
Thanks for the great and long due refresh of basic / still daily commands!

I would love to be able to have it as a drop-in replacement when working in interactive mode.
There is one small fix which I think does not modify it's current functionality:

have "mod" the default mode for "-t" (don't force "-t" get a mode parameter).

i.e. Have  `exa -t` work the same way with `exa -t=mod`   

Why?
Many people are used with the `ls -lart`, (hardcoded in their brain), and it would be nice to have "-t" by default mimic the traditional ls.

**Comment by Freaky** [comment]
`-t` seems to have some odd behaviour, which I noticed when I tried setting its argument to optional.  I thought this was a side-effect of that, but this is with an unmodified exa master.

Sometimes it errors:

```
-% exa -t
Flag -t needs a value (choices: modified, changed, accessed, created)
To sort newest files last, try "--sort newest", or just "-snew"
```

Sometimes it silently consumes its argument:

```
-% exa -tl
build.rs  Cargo.lock  Cargo.toml  contrib  devtools  LICENCE  Makefile  README.md  screenshots.png  snap  src  target  testdir  Vagrantfile  xtests

-% exa -t erm
build.rs  Cargo.lock  Cargo.toml  contrib  devtools  LICENCE  Makefile  README.md  screenshots.png  snap  src  target  testdir  Vagrantfile  xtests

-% exa -t --help
build.rs  Cargo.lock  Cargo.toml  contrib  devtools  LICENCE  Makefile  README.md  screenshots.png  snap  src  target  testdir  Vagrantfile  xtests
```

**Comment by ReSearchITEng** [comment]
Does this mean it will be even easier to make it not error even when there is no arg ?

**Comment by ariasuni** [comment]
Closing this in favor of #519.

**Comment by ariasuni** [comment]
@Freaky: exa ignore `-t` because it’s an option only valid when using `--long`. It’s used to change what time is displayed for each file, so it’s irrelevant in other view modes.
