### ISSUE TITLE
Anything tracking changes for 0.10.0?

### ISSUE THREAD

**Issue by lightclient** [ogham/exa#673]
Is there any issue tracking the changes anticipated to land in `0.10.0` and possibly a timeline for that update?

**Comment by ariasuni** [comment]
There’s milestones [0.10.0](https://github.com/ogham/exa/issues?q=is%3Aopen+is%3Aissue+milestone%3Av0.10.0).

I personally believe it would be nice to polish `--icons` and its documentation a bit before cutting a new release.

I’ll see what I can do to help make 0.10.0 happen faster.

**Comment by Mic92** [comment]
It looks like all issues related to the milestone are closed?

**Comment by ariasuni** [comment]
Closing this since 0.10.0 has been released.
