### ISSUE TITLE
exa -l fails to show the the contents of directory

### ISSUE THREAD

**Issue by ASHWIN990** [ogham/exa#679]
Using the exa in the directory where i have stored my wordlists and inside that directory running the **exa -l** does'nt run.

*Content of directory*

```sh
hash.txt    md5-crack     sha1-crack      sha2-512-crack  sha3-512-crack
hbhc        md5-crack-mt  sha2-224-crack  sha3-224-crack  test.py
install.sh  README.md     sha2-256-crack  sha3-256-crack  uninstall.sh
LICENSE     screenshots   sha2-384-crack  sha3-384-crack  wordlist.txt
```

*when using exa -l*

```sh
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: SystemTimeError(1s)', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
Aborted (core dumped)
```

**Comment by Hollow-Glitch** [comment]
Hello, I am not a dev of this project, but I think as a first step, you could provide a description of your system, useful info-s could be:

- OS
- shell

And then set the environment variable as suggested by the error message,
in bash that would be('$' last prompt character):

`...$ RUST_BACKTRACE=1 `

afterwards, run the program in the same directory, and pin the output here.

**Comment by ASHWIN990** [comment]
Sorry for the uncompleted comment:-
```
uname  -a : Linux ashwini-main 5.4.40-1-MANJARO #1 SMP PREEMPT Sun May 10 14:17:40 UTC 2020 x86_64 GNU/Linux

shell : bash 5.0.16(1)-release (x86_64-pc-linux-gnu)
```

And after setting the environment variable RUST_BACKTRACE=1 

~~~
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: SystemTimeError(1s)', src/libcore/result.rs:997:5
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: __libc_start_main
  15: <unknown>
Aborted (core dumped)
```

**Comment by Hollow-Glitch** [comment]
Seems to be very similar to: https://github.com/ogham/exa/issues/596?fbclid=IwAR3KFbGd_AT2dOtKNkYzmko-DngaBlZN-RAlNQvXSom3_tmry-LuBloZl8c

I would suggest checking whether you have files with weird dates.
If you have not already, consider installing exa with `cargo install --git url_of_git_project`, maybe the problem has been already resolved in latest version.

**Comment by ASHWIN990** [comment]
The new update has resolved the issue, Thanks for this utility.
