### ISSUE TITLE
unable to build exa on raspberry pi

### ISSUE THREAD

**Issue by adgai19** [ogham/exa#681]
while building exa on raspberry pi i get following error. Just pasting the last few lines.
```
error[E0658]: use of unstable library feature 'copied' (see issue #57126)
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/zoneinfo_compiled-0.4.8/src/lib.rs:131:49
    |
131 |         let std_flag = tz.standard_flags.get(i).copied().unwrap_or_default() != 0;
    |                                                 ^^^^^^

error[E0658]: use of unstable library feature 'copied' (see issue #57126)
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/zoneinfo_compiled-0.4.8/src/lib.rs:132:44
    |
132 |         let gmt_flag = tz.gmt_flags.get(i).copied().unwrap_or_default() != 0;
    |                                            ^^^^^^

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0658`.
error: Could not compile `zoneinfo_compiled`.
warning: build failed, waiting for other jobs to finish...
error: build failed
make: *** [Makefile:21: target/release/exa] Error 101
```

**Comment by LovecraftianHorror** [comment]
I don't have a working raspberry pi at the moment to verify but it looks like `.copied()` is on stable now, so my best guess is that you're compiling with an older version of rust that didn't have it stabilized yet. If it's the package provided by raspberry pi then I know it tends to lag behind quite a bit, so that is likely the culprit.

**Comment by ogham** [comment]
Yeah, this feature was added in Rust 1.35, back in May 2019.

Exa used to unofficially track the latest version of the compiler, but that got confusing, so now the README and build instructions officially mention Rust 1.42 or more recent.
