### ISSUE TITLE
Rustfmt probably makes unwanted changes

### ISSUE THREAD

**Issue by Nicholas-Baron** [ogham/exa#682]
A simple run of `cargo fmt` causes about 900 additional lines with ~2,000 extra formats, according to `git diff --stat`. 

Making a `rustfmt.toml` for this codebase would both help in reformatting the existing code and allow future additions to be accepted faster by handing code style over to a tool.

**Comment by ogham** [comment]
There's a `.rustfmt.toml` there now, which contains this:

```toml
disable_all_formatting = true
```

Which I know isn't _quite_ what you meant, but I haven't been able to put together a set of formatting options that get it to work the way I like. I've accepted PRs using the default Rust which I just fix in one big go later.

**Comment by skyline75489** [comment]
Man this is messed up. I'm using stable and I'm getting:

```text
Warning: can't set `disable_all_formatting = true`, unstable features are only available in nightly channel.
```

All the files are messed up . Please also add `rust-toolchain` to avoid this.

**Comment by ariasuni** [comment]
That sounds annoying, but we can’t do better until rustfmt 2.0 is released, with the stabilized `ignore` option.

> Please also add `rust-toolchain` to avoid this.

What do you mean? I suppose you’re talking about specifying somewhere to use the nightly channel, but exa doesn’t need nightly and only requires 1.42.0.

**Comment by skyline75489** [comment]
I honestly don't know what happened. I thought it was because exa requires nightly so the error showed up and `cargo fmt` still messed up all the code. Maybe we should just wait for rustfmt 2.0
