### ISSUE TITLE
feature request: combine --tree with --long

### ISSUE THREAD

**Issue by basbebe** [ogham/exa#684]
I would love to have the possibility to combine `-tree` with `--long` and `--git` to get information of shallow nested structured at once.

**Comment by Hollow-Glitch** [comment]
I think that in most situations it wouldn't fit on the screen, could you hack together an expected output in a text editor?

**Comment by basbebe** [comment]
lsd does this (and I find it quite useful):

![Bildschirmfoto 2020-06-06 um 11 42 16](https://user-images.githubusercontent.com/7083188/83941339-c6ef9f80-a7ea-11ea-81d5-4e31cb6556ec.png)

**Comment by flying-sheep** [comment]
Exa already does this:

```console
$ exa -Tl
drwxr-xr-x    - phil 16 Okt 15:53 .
.rw-r--r--  208 phil 16 Okt 15:15 ├── index.rst
.rw-r--r-- 4,6k phil 16 Okt 15:50 └── static.ipynb
```

**Comment by ogham** [comment]
Yeah, this feature is already here!

**Comment by basbebe** [comment]
I see now what the problem was:
I hat an alias in my fish config:
```
    alias exa 'exa --icons --grid'
```

removing `--grid` solved the problem…
