### ISSUE TITLE
[Suggestion] Invert the -a flag

### ISSUE THREAD

**Issue by dertuxmalwieder** [ogham/exa#694]
According to the documentation, `exa` deliberately breaks with the `ls` defaults by not showing `.` and `..` without being asked explicitly (`--all --all`). I think it’s time to break one more convention: As it makes no sense *for most people*  to not see *all* files in a directory listing, I would argue that `exa` should show files starting with a dot *by default*. This would even be a [security advantage](http://pub.gajendra.net/2012/09/dotfiles) over `ls`.

I assume that most non-`exa` people aliased (or manually type) `ls -a` anyway. Are there really users among the `exa` target audience who prefer to *not* see all their files by default?

I could perfectly understand you to WONTFIX this suggestion, but I’d like you to, at least, consider it.

**Comment by ogham** [comment]
I'm aware of dotfiles' troubled nascence. I even have Rob Pike's [accumulated sludge post](https://github.com/ogham/exa/blob/13b91cced4cab012413b25c9d3e30c63548639d0/src/fs/filter.rs#L51-L77) in the source code!

I promise you I did consider it. However, I can honestly say I only use the `-a` flag less than 5% of the time. The files hidden by dots are almost always the files I don't want to be seeing, so I am going to keep exa the way it is.
