### ISSUE TITLE
New Release? Project Dead?

### ISSUE THREAD

**Issue by noqqe** [ogham/exa#697]
Hi,

since more than a year there has been no release. 

Many bugs have been fixed in the meantime that bother users all day. 

What is necessary to make this happen? Is @ogham still interested in running this project?

Would be happy to see this project coming back to life.

**Comment by noqqe** [comment]
see #621 for comparsion as well.

**Comment by kpcyrd** [comment]
I'm also very interested in a new release, I ended up here because of a bug that was first reported in #526 and fixed in #584 but keeps getting reported (#629, #711) because the fix was never released.

I'd be interested in joining as a co-maintainer if this is a time issue.

**Comment by clar-cmp** [comment]
Would love it if this project received some love. Definitely think it'd be reasonable to add more maintainers if @ogham doesn't have the time. :)

**Comment by mschilli87** [comment]
Have a look at https://github.com/ogham/exa/issues/621#issuecomment-670029389.

**Comment by ryuta69** [comment]
Haven't been merged for harf a year, and I realized this issue.
Hope he'll back someday.

**Comment by ryuta69** [comment]
@noqqe 
ogham now is active recently.
This issue should be closed

**Comment by kpcyrd** [comment]
We still need a new release :)

**Comment by ryuta69** [comment]
Oh , sure. I forgot about it.

**Comment by ariasuni** [comment]
Closing this — I think the author is well aware of the fact that a new release is eagerly awaited, and there are other issues asking for that anyway.

I’m no maintainer (can’t make a new release or update the website) but I can review and merge PRs, and I’ll see how I can help ogham cut a new release.

**Comment by kpcyrd** [comment]
@ariasuni please reach out and ask if you can get the required permissions to do releases, there's been discussion about dropping exa from Arch Linux because the last release contains too many bugs and the only person able to do releases is unreachable.
