### ISSUE TITLE
Panic on file with pre-Epoch timestamp

### ISSUE THREAD

**Issue by alerque** [ogham/exa#699]
```
$ touch -t 197001010000 foo
$ ls -l foo
-rw-r--r-- 1 caleb caleb 0 Jan  1  1970 foo
$ exa -l foo
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: SystemTimeError(7140s)', src/fs/file.rs:331:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[1]    409858 abort (core dumped)  exa -l foo
```

Note this is a failed attempt at setting an Epoch time stamp, Epoch is actually 2 am, not 0. GNU's `touch` can set this correctly with `touch -d @0`, but BSD's requires the long form format.

Still `exa` probably shouldn't panic in this case.

**Comment by ogham** [comment]
The fix for this has been merged (#670) and will go out with the next release.
