### ISSUE TITLE
--tree is not working

### ISSUE THREAD

**Issue by TN1ck** [ogham/exa#7]
I tested it under osx and ubuntu on both system in didn't do anything (no error message or similiar).
![screenshot 2015-02-22 00 33 53](https://cloud.githubusercontent.com/assets/2116347/6316554/a398a92c-ba2a-11e4-9715-feecd063cd7e.png)

**Comment by ogham** [comment]
Oops. You need to pass `--recurse` as well as `--tree`, since there's no point in a tree view that doesn't recurse.

It should warn you if you don't pass in both flags - I'll get a fix out ASAP.

**Comment by jpscharf** [comment]
What do you think about the following, when ```--tree``` is passed ```--recursive``` is implied:
```exa --tree``` ***=*** ```exa --tree --recursive```

**Comment by ogham** [comment]
I did consider doing exactly that when I implemented `--tree`, but ultimately went against it, as in my mind, tree-view is just another form of recursion... I'm considering changing it, though, given the number of people who don't seem to think like that!

**Comment by jpscharf** [comment]
I agree with you that tree-view is a recursive view. So that would that mean ```exa --tree --recursive``` is redundant? So all trees are recursive, but not all all recursions are trees :grinning:
