### ISSUE TITLE
Panic on --tree -l

### ISSUE THREAD

**Issue by zoulja** [ogham/exa#706]
➜  RUST_BACKTRACE=full exa --tree -l
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: SystemTimeError(10800s)', src/libcore/result.rs:999:5
stack backtrace:
   0:     0x555afd0988d3 - <unknown>
   1:     0x555afd096deb - <unknown>
   2:     0x555afd095e10 - <unknown>
   3:     0x555afd0959fd - <unknown>
   4:     0x555afd0a3035 - <unknown>
   5:     0x555afd0a6ccb - <unknown>
   6:     0x555afd070dcf - <unknown>
   7:     0x555afd052a11 - <unknown>
   8:     0x555afd059d41 - <unknown>
   9:     0x555afd08351c - <unknown>
  10:     0x555afd083f0b - <unknown>
  11:     0x555afd0a2b9d - <unknown>
  12:     0x555afd0a3a87 - <unknown>
  13:     0x7f29688d2608 - start_thread
  14:     0x7f29687de102 - __clone
  15:                0x0 - <unknown>
[1]    119610 abort (core dumped)  RUST_BACKTRACE=full exa --tree -l
➜  exa --version                    
exa v0.9.0
➜  uname -a
Linux kampukter 5.4.0-40-generic #44-Ubuntu SMP Tue Jun 23 00:01:04 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Found a lot of similar issues over here, but in my case -l itself doesn't lead to panic, only combination of --tree and -l

**Comment by Freaky** [comment]
It's the same issue - you have a file with a pre-epoch timestamp - it just happens to be in a subdirectory which is only shown when you make it recurse.

**Comment by ogham** [comment]
Yes, this is #670 — the fix for this has been merged and will go out with the next release.
