### ISSUE TITLE
unwrap called on input/output error

### ISSUE THREAD

**Issue by paholg** [ogham/exa#71]
Using version 0.3.0 (from AUR), calling exa on something that is no longer there (such as an external harddrive that has lost power), results in 

```
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os(5) }', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:731
```

whereas ls gives the error
```
ls: reading directory /storage: Input/output error
```

**Comment by ogham** [comment]
Yeah, that's not right. Could you re-run it, setting the environment variable `RUST_BACKTRACE=1`? It gives me a stack trace.
