### ISSUE TITLE
Months not correctly shortened in long view (ARM, en_GB.utf8)

### ISSUE THREAD

**Issue by eggbean** [ogham/exa#719]
On my Raspberry Pi, I have just noticed that August is not shortened like other months. This seems to only be happening on my ARM RasPi and not on my x86 servers.

![image](https://user-images.githubusercontent.com/815311/90350451-1f39ed80-e035-11ea-8342-f75afe3af763.png)

**Comment by eggbean** [comment]
https://github.com/messense/rust-musl-cross/issues/26#issuecomment-675868781

**Comment by 0x3333** [comment]
@eggbean will you create a PR? If not, tell me that I'll create it.

**Comment by 0x3333** [comment]
PR created.
