### ISSUE TITLE
`--icon` flag missing in `--help`

### ISSUE THREAD

**Issue by daniel-j-h** [ogham/exa#731]
Hey folks, I'm on v0.9.0 trying out the icon feature :hugs: 

It looks like the `--icon` flag is documented in the readme, but missing from the `exa --help` usage.

**Comment by SuperSandro2000** [comment]
Duplicate of https://github.com/ogham/exa/issues/568

**Comment by daniel-j-h** [comment]
Coolio! Looks like this was fixed in https://github.com/ogham/exa/pull/536 in January and is just waiting for a new release.

Is there a roadmap for a new release to get all those new features and fixes out? :hugs: cc @ogham
