### ISSUE TITLE
Extra character at the end of file permission when running exa 

### ISSUE THREAD

**Issue by schwindj** [ogham/exa#741]
when I do *exa -al --color=always --group-directories-first*, I get an '@' added to the end of the file permissions. Not sure why this is happening. I have not seen this in any of the posts or examples for the app. Please assist.

![image](https://user-images.githubusercontent.com/69474567/94363187-8c0dc200-008e-11eb-87e6-0ce71e5139a5.png)

**Comment by schwindj** [comment]
Curious enough exa appears to be rendering a '.' as '@'.  Has anyone seen this before? Are there any solutions? 

![image](https://user-images.githubusercontent.com/69474567/94363329-94b2c800-008f-11eb-9d30-523cec6f2e47.png)

**Comment by ogham** [comment]
These are [extended attributes](https://the.exa.website/features/xattrs) — if a file has one or more, it gets an `@` sign displayed after the permissions.

I'm curious about why it's showing up as a dot character though. What font are you using?
