### ISSUE TITLE
exa -l displays size of files but not directories

### ISSUE THREAD

**Issue by Fcktheworld58** [ogham/exa#745]
`exa -l`  displays size of files but not directories
`ls -l` displays directory sizes as well as that of files
My system:
`uname -a` output : `Linux computer 4.15.0-118-generic #119-Ubuntu SMP Tue Sep 8 12:30:01 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
operating on a `ext4` partition
Thinkpad E555

**Comment by kosayoda** [comment]
Just FYI: The `directory sizes` you mention are the sizes of the *directory itself* (which is a special file), and are very commonly just 4096 kilobytes (or multiples thereof as directory entries grow in number).

[See ham's justification for choosing to omit the directory size in exa here.](https://github.com/ogham/exa/blob/dbbc4e465b3bf4cff28fbb7e3bd541b6a1d915bc/src/fs/fields.rs#L143-L152)

That being said however having a flag to show directory sizes would be a nice feature.

**Comment by Fcktheworld58** [comment]
Thanks for the info and link! Have a great day!

**Comment by ogham** [comment]
Yeah, that's the reason

**Comment by Freaky** [comment]
I'd like to reopen this.  On BSDs the size field gives you the number of entities in the directory:

```
❯ /bin/ls -l ~/Maildir | egrep 'new|cur'
drwx------  2 freaky  freaky   1386 21 Oct 15:10 cur
drwx------  2 freaky  freaky      2 21 Oct 15:04 new
```

You can see instantly I have no new messages and 1,384 old ones.
