### ISSUE TITLE
Can't pipe colored output to a pager

### ISSUE THREAD

**Issue by lilydjwg** [ogham/exa#75]
ls has an option `--color=always`, and tree has an option `-C`, to always enable colored output, so I can pipe it to `less -R`. But exa doesn't have such an option.

Suggestions:
* use stdin instead of stdout to determine terminal size
* add an option `-C` in order to print colorful text to pipes

**Comment by ogham** [comment]
I tried using stdin instead of stdout, but this doesn't prevent colourful text being printed to pipes. So I'm going to add a `-C` option.

**Comment by lilydjwg** [comment]
You need the terminal size even when piping to a pager, so I guess you can try stdin when stdout is a pipe and the user asks for colours with `-C`.

**Comment by ogham** [comment]
Are you sure? When I'm piping to a pager, exa's stdout isn't to a terminal so I don't need to get the terminal size.

**Comment by lilydjwg** [comment]
You need the terminal size to do the layout. When I pipe output to a pager, I still view it in the terminal. One thing `ls` annoys me is when I pipe its output, it always puts each entry on a separate line.

The difference can be seen by comparing `exa /usr/bin` and `exa /usr/bin | less`.

**Comment by ogham** [comment]
Yeah, exa copies `ls`'s behaviour here because if your stdout isn't a terminal, then you can't assume any particular file layout.

(Also, I've seen cases where people write things like `for i in `ls *.txt` to loop over files, which only works if there's only one file per line. Not that I support doing that.)

**Comment by lilydjwg** [comment]
The user shouldn't expect one per line when they specify `-C` to add colours, because colours are harmful when using like that. When I pipe colourful things, I mostly pipe them to `less`, sometimes to a file then view with `less`.

Or maybe another option to specify the width of layout? I want to view a large numbers of file nicely.

**Comment by auscompgeek** [comment]
Piping `ls -C`/`ls -x` output to a pager seems an unusual use-case; column-ised 'short' listings don't seem particularly useful in large directories, since most people wouldn't be interested in the exact contents of such directories.

GNU `ls` does have a `-w, --width=COLS` to force `ls` to assume a particular terminal width.

**Comment by lilydjwg** [comment]
Piping `tree -C` outputt to a pager is more useful, as it will have longer contents, with listings from different subdirectories. e.g., in a Rust project, I may want to see the source codes, example codes and built executables, but not all kinds of `deps`, `.o`s and `.a`s. With a pager it's easy to skip those uninteresting contents.

`exa -Tl` provides more information than `tree`. However, I need some tricks to retain its colorful output.

**Comment by auscompgeek** [comment]
Yeah, I think we can all agree that exa needs a way to force colour output when stdout isn't a tty.

**Comment by ogham** [comment]
So, does something like this work for you?

<img width="668" alt="screen shot 2015-11-19 at 12 48 51" src="https://cloud.githubusercontent.com/assets/503760/11271125/eddde018-8ebb-11e5-90bd-93933adafa6f.png">

**Comment by lilydjwg** [comment]
Yes, thanks!

PS: so many cats :-)
