### ISSUE TITLE
panics when outputs to a pipe that closes early

### ISSUE THREAD

**Issue by lilydjwg** [ogham/exa#76]
`exa /usr/bin | less`, then quit `less` without scrolling should trigger the following:

```
thread '<main>' panicked at 'failed printing to stdout: Broken pipe (os error 32)', src/libstd/io/stdio.rs:582
```

This is the same issue that `svn log` has (or had; I haven't used svn for a long time).

**Comment by ogham** [comment]
Me neither... fortunately.

However, panicking when printing fails is the correct behaviour (see http://roscidus.com/blog/blog/2013/06/09/choosing-a-python-replacement-for-0install/#safety and #50).

**Comment by lilydjwg** [comment]
You have to find a directory that has many files so that the output can fill up the buffer of the pipe. I have 5062 files under `/usr/bin`.

Printing to a read-only file descriptor will cause a different error:
```
>>> ls 1< /dev/null
ls: write error: Bad file descriptor
```

If the file descriptor refers to a file on which there's no space left, you'll get another error::

```
>>> ls > /dev/full
ls: write error: No space left on device
```

```
>>> ls | echo

>>> echo $pipestatus
141 0
```

Programs exit with an exit code of 141 on SIGPIPE, but no output. You don't expect an error message when you exit your pager, right? When you see it, you have to distinguish where it comes from, the content you're viewing or the program printing?

I don't think a SIGPIPE while printing to a pipe is unexpected; it's expected, indicating the user (or the receiving program) doesn't want (or need) to read more.

**Comment by ogham** [comment]
I made some changes today (turning `println` into `writeln` with a handle that we pass around) and this doesn't seem to come up anymore. Does anyone know if Rust made a change to stop this happening? I'm 99% sure I'm unwrapping all the results.

**Comment by lilydjwg** [comment]
I don't get the error for the command I gave. Then I tried with another:

```
exa -Tl /var | less
```

And I got the error back :-)

**Comment by gemmarx** [comment]
More simply,  on top of exa's git repository

    $ ./target/debug/exa --recurse | head -1

makes a panic as follows
    >>thread '<main>' panicked at 'IO error: Error { repr: Os { code: 32, message: "Broken pipe" } }' .

My execution environment is RHEL 7.2 x86_64 with a dual core CPU.

Cheers.

**Comment by gemmarx** [comment]
If you spoil return value from writeln!,  this trouble goes out of sight.
In lines.rs, grid.rs and details.rs,
```
    - try!(writeln!(....
    + let _ = writeln!(....
```
For the time being, this change hides panicked messages.
Of course, it is desirable that the errors are ignored only if its state is "Broken pipe".

**Comment by Don42** [comment]
Shouldn't this be closed now?

**Comment by kbknapp** [comment]
This is a known "gotcha" that the Rust CLI working group is tracking and hoping to find a solution to. Whether that is better documentation, or official guides with these known footguns is TBD though.

**Comment by ariasuni** [comment]
Seems fixed to me.
