### ISSUE TITLE
please add an "almost all" option

### ISSUE THREAD

**Issue by saltedcoffii** [ogham/exa#764]
`ls` has a `-A` or `--almost-all` option that shows all hidden files except for the current directory (`.`) and the parent (`..`). This is nice as it's slightly less cluttery as `ls -a`. Would you please add this feature to exa?, e.g. `exa -A`?

Here's an example:
![image](https://user-images.githubusercontent.com/55339220/101265551-44458f80-36fc-11eb-80a9-051759f0e28e.png)

**Comment by kidonng** [comment]
Use `-aa`:

![Screenshot_20201206100047.png](https://user-images.githubusercontent.com/44045911/101269442-03a44f80-37aa-11eb-97b1-b1b48a390702.png)

**Comment by saltedcoffii** [comment]
alright this seems like a user error then, thanks for the help
