### ISSUE TITLE
Icons displayed as U+F15B on iTerm and Terminal.app

### ISSUE THREAD

**Issue by DanielRamosAcosta** [ogham/exa#765]
- The version of exa being used: `exa v0.9.0`
- The command-line arguments you are using `exa -l --icons`
- Your operating system and hardware platform: `macOS`, `11.0.1`, `20B50`

When I list files with icons I see the following:

```
terminal-app on  master
❯ exa -l --icons
.rw-r--r-- 8,9k danielramos  7 dic 20:41  Dracula.terminal
.rw-r--r--  551 danielramos  7 dic 20:41  INSTALL.md
.rw-r--r-- 1,1k danielramos  7 dic 20:41  LICENSE
.rw-r--r--  897 danielramos  7 dic 20:41  README.md
.rw-r--r-- 424k danielramos  7 dic 20:41  screenshot.png
```

Which, in my terminal I see as the following:

![image](https://user-images.githubusercontent.com/11427028/101403557-53c80280-38cd-11eb-99ab-8058827ab938.png)

I've tried using JetBrains Mono and Fira Code font, same result. Any ideas?

**Comment by kuroidoruido** [comment]
I have the same issue on ArchLinux with exa v0.9.0

**Comment by hrqmonteiro** [comment]
Are you using a patched Nerd Font on terminal?

**Comment by kuroidoruido** [comment]
It seems after a reinstall of nerd font (https://www.archlinux.org/packages/community/x86_64/ttf-nerd-fonts-symbols-mono/) it works for me :slightly_smiling_face:

**Comment by ogham** [comment]
Yes, you'll need a patched font for icons. The Nerd Fonts are a really good choice for this.

There's now a [page on the website](https://the.exa.website/features/icons) that explains what to do in this situation. (It wasn't there when you wrote this question — don't worry, you didn't miss anything)
