### ISSUE TITLE
randomly ordered list

### ISSUE THREAD

**Issue by hoodie** [ogham/exa#77]
I noticed that when selecting a certain subset of files in a directory
eg `exa --long foo*` or just `exa foo*` the results are arranged in a random fashion.
The first result is usually first still, but the order of the subsequent items is different every time.

**Comment by kbknapp** [comment]
I haven't actually looked at the implementation of `exa` but if they're storing the results in a `Vec` that's probably why. They'd either need to sort the vec, or store the results in an ordered collection. 

Feel free to ignore this if I'm way off. I've just had similar issues with projects I've been working on ;)

**Comment by ogham** [comment]
You're not too far off! exa happily sorts the contents of a directory - but I didn't think about the case when the user passes in files on the command-line. These aren't sorted but are loaded by a pool of threads, which explains why you're getting them in a random order.

**Comment by hoodie** [comment]
is the a matter of simply adding a `.sort()` somewhere?

**Comment by ogham** [comment]
So I took the long route and fixed this by moving the place where the threading is done, meaning that the command-line arguments will always get sorted! It's fixed on the branch, but I don't fully *trust* it yet so I'll merge it in the next few days.

It *would* have been possible to just add a `.sort()` somewhere, but doing that would mask the architectural changes that needed to take place. When you use multiple threads, you aren't guaranteed to get the results in any order -- hence this bug. But every directory that gets expanded for recursing or tree-ing used to be sorted *anyway*, and doing it again just meant doing it twice. This way, they're only sorted after they get filtered and processed, which is the more "correct" solution.

Speaking of correct solutions... do you think it makes more sense to sort the arguments by name (or whatever the user wants to sort by), or to keep them in the command-line order? I think there are reasons for both.

**Comment by hoodie** [comment]
What do you mean by sorting arguments by name?

**Comment by ogham** [comment]
I mean, if the user types something like `exa b.txt a.txt --sort=name`, should it display `b.txt` first, or `a.txt` first? The user has requested to sort by name, but has passed in the arguments in a particular order, and the `--sort` argument is used with directory listing only.

**Comment by ctgreybeard** [comment]
It should follow the argument. If I entered exa *.txt --sort=mtime (for
instance) the arguments get expanded because of the glob, exa doesn't know
whether I entered them or globbed them, thus the sort argument.

Bill W

**Comment by ogham** [comment]
What about if there were no `--sort` argument? Should that keep the command-line order?

**Comment by ctgreybeard** [comment]
Yes, I would agree with that. For my example I believe that would be
alphabetical due to the shell glob. But if I had a script, let's say, that
built the command then I might have a specific order in mind. Otherwise I'd
use --sort, no?

Bill

On Thursday, September 3, 2015, Ben S <notifications@github.com> wrote:

> What about if there were no --sort argument? Should that keep the
> command-line order?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ogham/exa/issues/77#issuecomment-137595389>.
>


-- 
Sent from my iPad

**Comment by kbknapp** [comment]
I would vote for keeping the default glob sort or lack there of when no sort is specified by the user. I'd imagine that's slightly faster, and if the user wants it sorted they'll say so, or at least they have the option to.
