### ISSUE TITLE
exa -lU on WSL

### ISSUE THREAD

**Issue by ChrisTsou** [ogham/exa#775]
When using `exa -lU` on wsl(archwsl specifically), inside a windows filesystem folder, crashes.
`ls -lU` works as intended.
`exa -lU` inside the wsl filesystem works as intended.

![Capture](https://user-images.githubusercontent.com/25465975/102990718-86eed080-4520-11eb-99c7-7fc0db0d5a6c.PNG)

**Comment by ariasuni** [comment]
This was fixed in #616, there just hasn’t been a new release made since then.

**Comment by ChrisTsou** [comment]
should i close this then? kinda new to github.

**Comment by ariasuni** [comment]
Yes, open issues here are only used to track problems that are not fixed in the development version.
