### ISSUE TITLE
exa -l on a directory with a file that's too old causes panic

### ISSUE THREAD

**Issue by Pagwin-Fedora** [ogham/exa#776]
## system info
version: `0.9.0`
command line arguments: `-l`
operating system: `x86_64 linux`

## bug info
crash text: ```thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: SystemTimeError(68400s)', src/fs/file.rs:331:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace```

additional info: this error will occur if the directory exa has been run on has any files which have had their last modified date set to any date before the unix epoch

**Comment by ariasuni** [comment]
This was fixed in #670, there just has been a new release made since then.
