### ISSUE TITLE
Add shortcut for tree view

### ISSUE THREAD

**Issue by Ticki** [ogham/exa#78]
If find myself using the command `exa -T -L 2` a lot. Like ls and l, add a shortcut in exa for `exa -T -L {n}` (this is trivial to do you self, but it could be nice for integrated support).

**Comment by kbknapp** [comment]
I know it's not quite what you're asking, but IMO just removing the spaces and extra `-`s helps a lot (`exa -TL2` ) and isn't really too much worse than adding another flag which just does a `-T -L {n}`.

**Comment by ogham** [comment]
I agree -- having to type `exa -TL2` is just one character more than the minimum possible!
