### ISSUE TITLE
Outdated `Cargo.lock` file?

### ISSUE THREAD

**Issue by carlocab** [ogham/exa#785]
exa is currently failing to build for Homebrew with Rust 1.49 on Apple Silicon: https://github.com/Homebrew/homebrew-core/pull/68089

It appears this is due to a stale lock file, causing `cargo install --locked` to pull in dependencies that do not work for exa on Apple Silicon. Is it possible for the `Cargo.lock` file to be updated? If this could be done with a new release, that would be especially helpful.

Related: https://github.com/ogham/exa/issues/780, https://github.com/Homebrew/homebrew-core/issues/68301

**Comment by johnalanwoods** [comment]
I guess eventually for exa we will also need a working `ghc` but it would be great to get this fixed when the fix is so simple...

**Comment by carlocab** [comment]
As long as you don't do `brew install --HEAD exa` then you don't need `ghc`. The `pandoc` dependency is only needed for `HEAD` installs.

**Comment by johnalanwoods** [comment]
@carlocab yep, but eventually `HEAD` will be the release version :)

**Comment by johnalanwoods** [comment]
Could someone pls make a release with an update? Would be great to see this in brew again for ARM macs.

**Comment by carlocab** [comment]
Closed in https://github.com/Homebrew/homebrew-core/commit/5952b28a281c15ba801ad2611b73efcb0d8ca27b.
