### ISSUE TITLE
Add NO_COLOR support

### ISSUE THREAD

**Issue by Dialga** [ogham/exa#788]
Check the NO_COLOR environment variable to turn off color support.
See https://no-color.org.

**Comment by sschlesier** [comment]
I almost made the same suggestion a few weeks ago.  Then I considered that at least for me exa is all about the improved user experience and for that color is a core feature.  Situations where I would use NO_COLOR would be for scripts, and in those cases ls is a more reliable option anyway.

NO_COLOR support wouldn't be a bad thing, but it might be of limited practical use.
