### ISSUE TITLE
add `autocomplete`

### ISSUE THREAD

**Issue by Stefanqn** [ogham/exa#789]
please add autocomplete scripts (e.g. like https://github.com/sharkdp/fd/) to the created artifacts.

**Comment by ariasuni** [comment]
I believe you’re talking about putting shell completion scripts in the “Assets” section of the releases on GitHub, is that correct?

**Comment by Stefanqn** [comment]
or in the released `.zip`. I'm using a zsh packet manager (zinit), which can download and install resources (like `exa`) automatically for different environments. It works mostly nice, but for `exa` `_exa` is missing for autocompletion.

**Comment by ariasuni** [comment]
Note that starting with exa 0.10.0, there is an «accoutrements» file:
https://github.com/ogham/exa/releases/download/v0.10.0/exa-accoutrements-v0.10.0.zip

Please note that the zsh autocompletion script is called `exa.zsh` and should be renamed `_exa`.

I’m closing this, see #451 for the `_exa` issue.
