### ISSUE TITLE
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: SystemTimeError(6795364578.871345152s)'

### ISSUE THREAD

**Issue by mrichman** [ogham/exa#798]
Version 0.9.0 on macOS 10.15.7.

It looks like malformed timestamps from `hugo` like this one induce the errorr:

`drwxr-xr-x  23 wheel   736 Aug 30  1754 public/`

Command: `exa -abghl` aliased as `ll`.

Stack trace:
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: SystemTimeError(6795364578.871345152s)', src/fs/file.rs:331:70
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: exa::output::table::Table::display
   4: exa::output::table::Table::row_for_file
   5: <F as scoped_threadpool::FnBox>::call_box
```

**Comment by tbodt** [comment]
I'm seeing this too

**Comment by tbodt** [comment]
Looks like it was fixed in #557. @ogham could you release a new version? It's been a few years...

**Comment by olbrew** [comment]
It indeed appears to have the same cause as #556. @ogham said there he would deploy it with the next release. When it is, this issue can be closed as well.

**Comment by ariasuni** [comment]
I’m gonna close this since it’s fixed on master. It helps me to see what needs to be done next and make issues manageable.

**Comment by ariasuni** [comment]
By the way, exa is now at 0.10.1 (with this problem fixed).
