### ISSUE TITLE
exa --git doesn't list each file's status

### ISSUE THREAD

**Issue by hohosoft49** [ogham/exa#805]
Ubuntu 20.04.2 
exa v0.9.0

exa --git (or exa -l --git) doesn't show the Git status column

I have tried all combinations of flags, e.g.
    exa -l --git
    exa --git -l
    exa -la --git
    exa --git -la
    exa -lh --git
    ...

I can't figure out how to get it to display git status column

**Comment by eggbean** [comment]
See here: https://github.com/ogham/exa/issues/761

**Comment by ariasuni** [comment]
Closing since there’s already #761.
