### ISSUE TITLE
-A vs -a vs -a -a

### ISSUE THREAD

**Issue by vmiheer** [ogham/exa#808]
I switched to exa as ls. But while trying out [this answer](https://superuser.com/questions/352289/bash-scripting-test-for-empty-directory), exa doesn't work.
I am not sure if exa wants to be [posix compliant](https://pubs.opengroup.org/onlinepubs/007904875/utilities/ls.html), but if wants to be posix compliant, I guess it should print out `.` and `..` when run as `ls -a`.
I am just not sure about choice of `-a -a` over just `-a` and not additionaly providing `-A` option.

**Comment by ariasuni** [comment]
> I am not sure if exa wants to be posix compliant […]

Well, no. From the README:
> By deliberately making some decisions differently, exa attempts to be a more featureful, more user-friendly version of `ls`.

See also the FAQ on the website:
https://the.exa.website/#faq

I would say that `exa` is often not more useful than `ls` for scripts and less portable anyway, so in this case using `ls` would be preferable.

>  I am just not sure about choice of -a -a over just -a and not additionaly providing -A option.

It could be added for compatibility, that’s #497.

**Comment by eggbean** [comment]
@vmiheer You can use this wrapper script to make `exa` behave the same as `ls`: https://gist.github.com/eggbean/74db77c4f6404dd1f975bd6f048b86f8

**Comment by gek169** [comment]
how about a flag for exa to make it behave identically to LS?
exa --ls-compat

**Comment by ariasuni** [comment]
The idea of a «ls mode» is tracked there: https://github.com/ogham/exa/issues/332
