### ISSUE TITLE
exa -l with total

### ISSUE THREAD

**Issue by black7375** [ogham/exa#810]
command `ls -l` show `total` count.
It would be convenient if you provide it.

![image](https://user-images.githubusercontent.com/25581533/110568385-cce42980-814a-11eb-8eb2-2df56f06bde2.png)
- [Image ref](https://serverfault.com/questions/290081/why-does-ls-lh-and-ls-ldh-give-me-varying-file-size)

**Related**
#799

**Comment by snuglove** [comment]
support,also need this feature

**Comment by eggbean** [comment]
You could make a wrapper script that uses `du` to make that line, although the figure `du` comes up with seems to be different to `ls` for some reason.

**Comment by gek169** [comment]
I vote yes

**Comment by ariasuni** [comment]
Closing this since exa is unmaintained (see https://github.com/ogham/exa/issues/1243), and a similar issue has been open for [the active fork eza](https://github.com/eza-community/eza). Thanks!

(see https://github.com/eza-community/eza/issues/389)

**Comment by black7375** [comment]
Thank you for keeping project!!
