### ISSUE TITLE
Issue in Hugo project root dir

### ISSUE THREAD

**Issue by EricDriussi** [ogham/exa#811]
This happens to me only in the root dir of a hugo project. Just one specific hugo project, tried it in another one and didn't happen.

- The version of exa being used (`exa --version`)
  exa v0.9.0

- The command-line arguments you are using
  exa -l

- Your operating system and hardware platform
  Arch linux, AMD CPU, HP Laptop

Output:

```sh
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: SystemTimeError(2147483648s)', src/fs/file.rs:331:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[1]    113407 abort (core dumped)  exa -l
```

**Comment by ariasuni** [comment]
This was fixed a while ago, there just hasn’t been a new release made since then.
https://github.com/ogham/exa/issues/710#issuecomment-713609499

My advice is to use `touch` on the files that have a date in the distant past, or to use exa compiled from source.
