### ISSUE TITLE
Incorrect FIle size with `exa -l`

### ISSUE THREAD

**Issue by Krysme** [ogham/exa#812]
version: `exa v0.9.0`

how it can be reproduced:
create a 32G file on disk and run `exa -l` on this file

unexpected result: 
it says the file is with the size of 34 GB instead of 32 GB.

something must be wrong with the size calculation, I presume.

**Comment by cho-m** [comment]
I think this is a difference in units.
34 Gigabytes (34 x 1000<sup>3</sup>) ≈ 32 Gibibytes (32 x 1024<sup>3</sup>).

Use `-b` if you want binary units, e.g.
```console
❯ exa -l -B testfile.txt
.rw-r--r-- 6,439,669,760 cho-m 21 Mar 01:54 testfile.txt

❯ exa -l -b testfile.txt
.rw-r--r-- 6.0Gi cho-m 21 Mar 01:54 testfile.txt

❯ exa -l testfile.txt
.rw-r--r-- 6.4G cho-m 21 Mar 01:54 testfile.txt
```

**Comment by ariasuni** [comment]
There’s something else going on.

```
$ exa -lB
.rw-r--r--   1 871 ariasuni 11 Jan 19:42   build.rs
.rw-r--r--  10 735 ariasuni 11 Jan 19:42   Cargo.lock
.rw-r--r--   1 504 ariasuni 11 Jan 19:42   Cargo.toml
.rw-r--r--   1 858 ariasuni  4 Jan 01:24   Justfile
.rw-r--r--   1 080 ariasuni  3 juil.  2019 LICENCE
.rw-r--r--  11 200 ariasuni 14 Jan 16:29   README.md
.rw-r--r-- 454 908 ariasuni  3 juil.  2019 screenshots.png
.rw-r--r--   6 068 ariasuni 11 Jan 23:44   Vagrantfile
$ ls -l --si
-rw-r--r-- 1 ariasuni ariasuni 1,9k 11 janv. 19:42 build.rs
-rw-r--r-- 1 ariasuni ariasuni  11k 11 janv. 19:42 Cargo.lock
-rw-r--r-- 1 ariasuni ariasuni 1,6k 11 janv. 19:42 Cargo.toml
-rw-r--r-- 1 ariasuni ariasuni 1,9k  4 janv. 01:24 Justfile
-rw-r--r-- 1 ariasuni ariasuni 1,1k  3 juil.  2019 LICENCE
-rw-r--r-- 1 ariasuni ariasuni  12k 14 janv. 16:29 README.md
-rw-r--r-- 1 ariasuni ariasuni 455k  3 juil.  2019 screenshots.png
-rw-r--r-- 1 ariasuni ariasuni 6,1k 11 janv. 23:44 Vagrantfile
$ exa -l
.rw-r--r-- 1,9k ariasuni 11 Jan 19:42   build.rs
.rw-r--r--  10k ariasuni 11 Jan 19:42   Cargo.lock
.rw-r--r-- 1,5k ariasuni 11 Jan 19:42   Cargo.toml
.rw-r--r-- 1,9k ariasuni  4 Jan 01:24   Justfile
.rw-r--r-- 1,1k ariasuni  3 juil.  2019 LICENCE
.rw-r--r--  11k ariasuni 14 Jan 16:29   README.md
.rw-r--r-- 454k ariasuni  3 juil.  2019 screenshots.png
.rw-r--r-- 6,1k ariasuni 11 Jan 23:44   Vagrantfile
```


| size in bytes | size in ls (SI) | size in exa (SI) |
|-|-|-|
| 1 871 | 1.9k | 1.9k |
| 10 735 | 11k | 10k |
| 1 504 | 1.6k | 1.5k |
| 1 858 | 1.9k | 1.9k |
| 1 080  | 1.1k | 1.1k |
| 11 200 | 12k | 11k |
| 454 908 | 455k | 454k |
| 6 068 | 6.1k | 6.1k |

ls seems to use the ceiling of the size while exa uses rounding; however, it seems that exa is rounding incorrectly in some cases.

**Comment by cho-m** [comment]
@ariasuni I took a look at GNU coreutils docs: https://www.gnu.org/software/coreutils/manual/html_node/Block-size.html#Block-size

> Fractional block counts are rounded up to the nearest integer.

I would recommend documenting exa's choice whether it decides to keep current logic of traditional rounding, or if it adopts `ls` choice of rounding up to whole block.

**Comment by ariasuni** [comment]
Ah, thanks for the documentation section describing this! I guess it makes sense to keep rounding since e.g. exa doesn’t disclose the size of directories on disk like `ls`… but the choice to do that should totally be documented somewhere. I’ll see if I can find an appropriate place to do so, and add it to my PR.
