### ISSUE TITLE
File permission in octal

### ISSUE THREAD

**Issue by TheFern2** [ogham/exa#816]
I might be the weird one out of the bunch, but I prefer to see file permissions in octal at times. For example if a tutorial is telling me to make sure a file has certain permissions 99% of the times is in octal. I did a very simple implementation of ls in python a while back that does this. Don't know if is a feature that people might like. If is something that you're not interested, please feel free to close the issue.

https://github.com/TheFern2/lspy

lx is an alias for ls.py which is installed in $HOME/.local/bin
```bash
~/g/fab-mentorship  (master) ❯❯❯ lx -ln
775 2 fernandob fernandob 4096 Jul 28 15:48 Career-Tips
775 3 fernandob fernandob 4096 Jul 28 15:48 Docs
775 3 fernandob fernandob 4096 Jul 28 15:48 Getting-Started
775 2 fernandob fernandob 4096 Jul 28 15:48 Images
775 4 fernandob fernandob 4096 Jul 28 15:48 Language-Specific
664 1 fernandob fernandob 1067 Jul 28 15:48 LICENSE
775 3 fernandob fernandob 4096 Jul 28 15:48 Misc
775 7 fernandob fernandob 4096 Jul 28 15:48 Projects
664 1 fernandob fernandob  246 Jul 28 15:48 README.md
775 3 fernandob fernandob 4096 Jul 28 15:48 Resources
775 2 fernandob fernandob 4096 Jul 28 15:48 Stories
775 2 fernandob fernandob 4096 Jul 28 15:48 Tech-Paths
775 5 fernandob fernandob 4096 Jul 28 15:48 Tools
~/g/fab-mentorship  (master) ❯❯❯ ls -l
total 52
drwxrwxr-x 2 fernandob fernandob 4096 Jul 28  2020 Career-Tips/
drwxrwxr-x 3 fernandob fernandob 4096 Jul 28  2020 Docs/
drwxrwxr-x 3 fernandob fernandob 4096 Jul 28  2020 Getting-Started/
drwxrwxr-x 2 fernandob fernandob 4096 Jul 28  2020 Images/
drwxrwxr-x 4 fernandob fernandob 4096 Jul 28  2020 Language-Specific/
-rw-rw-r-- 1 fernandob fernandob 1067 Jul 28  2020 LICENSE
drwxrwxr-x 3 fernandob fernandob 4096 Jul 28  2020 Misc/
drwxrwxr-x 7 fernandob fernandob 4096 Jul 28  2020 Projects/
-rw-rw-r-- 1 fernandob fernandob  246 Jul 28  2020 README.md
drwxrwxr-x 3 fernandob fernandob 4096 Jul 28  2020 Resources/
drwxrwxr-x 2 fernandob fernandob 4096 Jul 28  2020 Stories/
drwxrwxr-x 2 fernandob fernandob 4096 Jul 28  2020 Tech-Paths/
drwxrwxr-x 5 fernandob fernandob 4096 Jul 28  2020 Tools/

```

**Comment by PatriotRossii** [comment]
There are "octal-permissions" flag which does what you want
https://github.com/ogham/exa/blob/f42957fab8ef1f750315bd957a16baa848177f19/src/options/flags.rs#L65

**Comment by TheFern2** [comment]
I didn't see any OCTAL flags in the readme, maybe I missed it. Can you please provide example how to use this octal flag?

**Comment by PatriotRossii** [comment]
Yes. For some reason, this flag isn't mentioned in README (I'll create the pull request describing it in it). But mentioned in help, which can be accessed with `exa --help`
https://github.com/ogham/exa/blob/86de17b788c676c08814441aac1becf2d2e40bdf/src/options/help.rs#L56

It can be used by any other flag. For example, `exa -l --octal-permissions`

**Comment by TheFern2** [comment]
I think I found the reason for not being on the README, this flag isn't on the latest release. 0.9.0. But either way I'll compile when I get home, nice to know the flag is there! Thanks! 😃
