### ISSUE TITLE
How do I use --long with other options?

### ISSUE THREAD

**Issue by mrjayviper** [ogham/exa#823]
setup: running manjaro + exa 0.9.0

I think this is best explained with an example:

- exa -l -b => works ok
- exa -l --binary => works ok
- exa -l -m => works ok
- exa -l --modified => works ok
- exa -l --octal-permissions => does not work
- exa -l --no-permissions => does not work
- exa -l --no-user => does not work

The error I get in "invalid argument"

Thanks

**Comment by MostHated** [comment]
I am having an issue with --octal-permissions as well. I had not tried the others, though.

```sh

alias la='exa -lhUma --time-style=default --git --color-scale' 

~ » la --octal-permissions                                    mosthated@pop-os
Unknown argument --octal-permissions

```

**Comment by AbhinavAchha** [comment]
Yes I am also facing this issue

**Comment by ariasuni** [comment]
All these options have been added after the last release. Just check if the option is present in `--help`, this should you tell what’s actually in your version of exa.

If you want to use these new options, you have to wait for a new release or compile exa from source.
