### ISSUE TITLE
Time formating for the months does not follow the locale

### ISSUE THREAD

**Issue by Oxyriser** [ogham/exa#833]
### The version of exa being used
`v0.10.0`

### The command-line arguments you are using
```
LC_TIME=fr_FR.UTF-8 exa -l /
```

### The issue
![exa-report](https://user-images.githubusercontent.com/19289632/114094670-dfbe5b00-98bc-11eb-948d-4f12e2ddd906.png)

Since v0.10.0, in the long format, with the time-style set to default, exa only respects the locale for timestamps from previous years.

**Comment by ariasuni** [comment]
It’s funny because I noticed that but I totally forgot I started working on a fix, so thanks for reminding me of this issue!
