### ISSUE TITLE
`EXA_GRID_ROWS` does not work

### ISSUE THREAD

**Issue by j-tai** [ogham/exa#835]
The `EXA_GRID_ROWS` environment variable no longer works at all in v0.10.0. It worked in v0.9.0.

Bisection returned the commit 0f414cf0b9b75e948424ae153a50f6f2b489a63c.

To reproduce:
1. Create a directory with 2 files in it
2. `export EXA_GRID_ROWS=8`
3. `exa -Gl`
    → The files are displayed in a grid with 1 row

exa version: built from master (2aaead1)
OS: Pop!_OS 20.10

**Comment by ariasuni** [comment]
I definitely have a very bad habit of introducing regressions with my fixes, damn.
