### ISSUE TITLE
Unclear error when using incorrect environment variable

### ISSUE THREAD

**Issue by ariasuni** [ogham/exa#839]
```
$ COLUMNS=a exa
exa: Failed to parse number: invalid digit found in string
$ EXA_GRID_ROWS=a exa -l
[works]
$ EXA_GRID_ROWS=a exa -lG
exa: Failed to parse number: invalid digit found in string
$ EXA_ICON_SPACING=a exa
[works]
$ EXA_ICON_SPACING=a exa --icons
exa: Failed to parse number: invalid digit found in string
```

The error message doesn’t tell which environment variable is wrong, or even that the problem is coming from an environment variable. Combined with the fact that the error message isn’t displayed if the variable isn’t used, it can be very confusing and hard to debug (`EXA_DEBUG=1` doesn’t help in this case).

Instead, exa could display an error message like this one:
```
$ COLUMNS=a exa
Error: environment variable COLUMNS is incorrect, its value should be a number.
```

**Comment by ogham** [comment]
This is a good idea. When I tested all those cases, I already knew which environment variable I was testing so I didn't think about it.
