### ISSUE TITLE
Using Japanese breaks consistency of month's name format

### ISSUE THREAD

**Issue by alker0** [ogham/exa#844]
My `LANG` is `ja_JP.utf8`.
When a directory includes both files that created in current year and other one, month's name format is no longer consistent.

![exa_time](https://user-images.githubusercontent.com/51204827/114290021-473ffa80-9ab7-11eb-9a26-46dda0243e9e.png)

```
$ exa --version
exa - list files on the command-line
v0.10.0 [+git]
https://the.exa.website/
```
OS: WSL2 Ubuntu_20.04

**Comment by ariasuni** [comment]
This is the same issue as #833 and was fixed by #837, and will be in the next exa release.
