### ISSUE TITLE
Issue with -l flag and --git flag when invalid symbolic link is present

### ISSUE THREAD

**Issue by jsosulski** [ogham/exa#845]
> - The version of exa being used (`exa --version`)

exa v0.9.0

> - The command-line arguments you are using

`exa -l --git`

> - Your operating system and hardware platform

Ubuntu 20.04.2 LTS x86_64 with an Intel i7-4710MQ

> If it’s a crash, please include the full text of the crash that gets printed to the screen.

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/jan/.cargo/registry/src/github.com-1ecc6299db9ec823/exa-0.9.0/src/fs/feature/git.rs:271:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)
```

---

Hey, I noticed a bug that appears if I am using the `--git` flag in combination with the `-l` flag when there's an invalid symbolic link in the current directory.

MWE:

```bash
mkdir test_git
cd test_git
git init
exa -l --git  # works
ln -s /invalid/link here
exa -l  # works
exa --git  # works
exa -l --git  # does not work
```

**Comment by ariasuni** [comment]
This issue is the same as #526, and that it has been fixed in #584, you should wait for Ubuntu to update the package or install exa 0.10.0 manually.
