### ISSUE TITLE
Homebrew upgrade exa to the latest version 0.10.1 get error

### ISSUE THREAD

**Issue by kondongx** [ogham/exa#847]
- The version of exa being used `0.9.0`
- The command-line arguments you are using `brew upgrade exa`
- Your operating system and hardware platform `macOS 11.2.3`
---

When upgrade `exa` with Homebrew (tried many times):
```txt
✗ brew upgrade exa
==> Upgrading 1 outdated package:
exa 0.9.0 -> 0.10.1
==> Downloading from https://homebrew.bintray.com/bottles/exa-0.10.1.big_sur.bottle.tar.gz
-#O#- #   #
curl: (22) The requested URL returned error: 404 Not Found
```

I guess it's not Homebrew's problem or something went worng with my network.

Because when I upgrade `fd` with Homebrew, it works:
```txt
✗ brew upgrade fd
==> Upgrading 1 outdated package:
fd 8.1.1 -> 8.2.1
==> Upgrading fd 8.1.1 -> 8.2.1
==> Downloading from https://homebrew.bintray.com/bottles/fd-8.2.1.big_sur.bottle.tar.gz
######################################################################## 100.0%
```

**Comment by ariasuni** [comment]
Your log shows that `brew` failed with a 404 to download a package of exa built by Homebrew, on what I presume is a Homebrew mirror. You should report this problem on [Homebrew/brew/issues](https://github.com/Homebrew/brew/issues).
