### ISSUE TITLE
Broken Package Link In Arch Linux

### ISSUE THREAD

**Issue by akhilmhdh** [ogham/exa#849]
I tried to install exa via pacman in my `manjaro kde`. Got 404 link not found on accessing the given url from pacman.

Attaching the screenshot:
![image](https://user-images.githubusercontent.com/31166322/115122400-69fd7200-9fd5-11eb-9c8c-3277f1bbd5ef.png)

**Comment by ariasuni** [comment]
Well, you are getting a 404 on Manjaro’s mirrors, so not an issue on our side.

On an up-to-date, I can find [exa 0.9.0-3](https://mirror.easylee.nl/manjaro/stable/community/x86_64/exa-0.9.0-3-x86_64.pkg.tar.zst), so I guess you just need to do `sudo pacman -Sy` and try again, and if it still fail, open a bug report on Manjaro’s side.
