### ISSUE TITLE
Use exa as a library

### ISSUE THREAD

**Issue by sayanarijit** [ogham/exa#851]
Hi, it would be nice to be able to use `exa` as a library. For example, [xplr](https://github.com/sayanarijit/xplr) could use some of `exa`s sorting, filtering and symlink parsing mechanism for displaying directory content.

**Comment by sayanarijit** [comment]
Let me know if this sounds good. I can contribute.

**Comment by ariasuni** [comment]
I don’t think this is ever gonna happen, so I’m closing this (especially because, well, exa’s internals are tuned for exa and not adapted for anything else…).
