### ISSUE TITLE
thread '<unnamed>' panicked - Exa with --long

### ISSUE THREAD

**Issue by jessefogarty** [ogham/exa#864]
**Version**: 0.9.0
**Args**: --long
**OS**: EndeavourOS (arch), x1 carbon 6G

**Raw output**:
```sh
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: SystemTimeError(6795364578.871345152s)', /home/jesse/.cargo/registry/src/github.com-1ecc6299db9ec823/exa-0.9.0/src/fs/file.rs:331:70
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/option.rs:1300:5
   3: exa::output::table::Table::display
   4: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
   5: <F as scoped_threadpool::FnBox>::call_box

```

**Additional Comments**
Could the SystemTimeError be the culprit and if so, would it be on my end? Sorry if that's a pretty straightforward question / answer but, this oddly only occurs in my jekyll directory for the GH pages site.

Thanks

---

**Comment by ariasuni** [comment]
This is fixed since exa 0.10.0 (in #670).

My advice is to use `touch` on the files that have a date in the distant past or to [install manually a new version of exa](https://the.exa.website/install/linux#manual).
