### ISSUE TITLE
exa takes super long on home folder that is a git repo

### ISSUE THREAD

**Issue by wohltat** [ogham/exa#876]
`exa -l --git` hangs and is using 1/3 of my CPUs on

`> exa --version`
v0.10.1 [+git]

```
> git init
> exa -l --git
```
takes pretty long. I guess it searches all of the folders.

if i add a git ignore file, like the following, it works fast 
```
# ignore all
*
# include dot files (including .gitignore)
!.*
```

operating system and hardware platform:
Linux Mint 20.1

**Comment by ariasuni** [comment]
Well, libgit2 is notoriously slow at some operations, in this case listing statuses of files.

Here, listing the newly created repository statuses means that you have a status (untracked) for each file in every subdirectory of `$HOME`, but when ignoring dotfiles there’s only an ignored status for each top-level dotfile/dot directory.

Closing in favor of #28.
