### ISSUE TITLE
Timestamps on English or Spanish depending on the year

### ISSUE THREAD

**Issue by ricpelo** [ogham/exa#884]
If exa does something unexpected, or its output looks wrong, or it displays an error on the screen, or if it outright crashes, then please include the following information in your report:

- The version of exa being used (`exa --version`)
- The command-line arguments you are using
- Your operating system and hardware platform

If it’s a crash, please include the full text of the crash that gets printed to the screen. If you’re seeing unexpected behaviour, a screenshot of the issue will help a lot.

---

## Description

Exa shows timestamps on English or Spanish depending on the year.

If the file date is in the current year, exa shows it in English. Otherwise, it shows it in Spanish.

![2021-05-27-102805_1920x1039_scrot](https://user-images.githubusercontent.com/616169/119793675-171db100-bed7-11eb-8f57-2313aa9c7ef4.png)

## Exa version:

```console
$ exa -v
exa - list files on the command-line
v0.10.0 [+git]
https://the.exa.website/
```

## Command line arguments:

```
exa --long
```

## Operating system and hardware

- Ubuntu 20.04.2 LTS on AMD Ryzen 7 2700X

```console
$ echo $LANG
es_ES.UTF-8
$ echo $LC_TIME
es_ES.UTF-8
```

**Comment by ariasuni** [comment]
This is the same issue as #833 and was fixed by #837, and is fixed in 0.10.1.

**Comment by ricpelo** [comment]
Oh, sorry, I didn't realize there's a newer version. The «Installation» section in the webpage links to `v0.10.0` version yet.

Thank you very much.

**Comment by ariasuni** [comment]
@ricpelo oh right, that should be fixed.

I added a comment on another bug so it will not be forgotten: https://github.com/ogham/exa/issues/757#issuecomment-849765279.
