### ISSUE TITLE
Adding Last change in git as the timestamp field

### ISSUE THREAD

**Issue by edwinclement08** [ogham/exa#889]
Using something like this over each file
`git log -1 --pretty="format:%ci" /path/to/repo/anyfile.any)`

It is possible to find the date a file last changed. 
I think it would be a useful data point that can be shown as a column on exa. In large repositories, it will help in quickly building context as one can ignore the files which have not changed in a long time.

**Comment by ariasuni** [comment]
It’s a good idea! and it’s already tracked in #545.
