### ISSUE TITLE
Shows an extra space after XML icon in --long listings

### ISSUE THREAD

**Issue by ricpelo** [ogham/exa#891]
Exa shows an extra space after XML icon in `--long` listings:

```bash
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
```

```bash
$ exa --version
exa - list files on the command-line
v0.10.1 [+git]
https://the.exa.website/
```

```bash
$ exa --icons --long *.xml *.py
```

![2021-06-19-105249_1189x279_scrot](https://user-images.githubusercontent.com/616169/122636987-80669d80-d0ec-11eb-907a-5e9d32e50c09.png)

**Comment by ariasuni** [comment]
Can confirm with several terminal emulators: Konsole and Kitty, Arch Linux, nerd-fonts-hack 2.1.0 (latest).

It seems that the XML icon (U+FABF) is displayed with a larger width, resulting visually in a additional space. I don’t think it’s supposed to work like that, it will need further investigation.

**Comment by ariasuni** [comment]
I opened a bug report on Nerd Fonts’ end, it would to nice if you could add your setup info there:
https://github.com/ryanoasis/nerd-fonts/issues/637

**Comment by ricpelo** [comment]
Interestingly, I've recently realized Exa sometimes uses another slightly different icon, but without the extra-space problem.

I attach an screenshot to illustrate.
![2022-01-12-223848_967x381_scrot](https://user-images.githubusercontent.com/616169/149225534-0ee0eea6-e078-4272-9834-3fbd41432270.png)

The icon near `lib` directory shows OK, and it's not exactly the same icon used in the `.xml` files.

Maybe Exa should use the working icon everywhere?
