### ISSUE TITLE
no size info  when using exa -l command

### ISSUE THREAD

**Issue by primeNumberAndMe** [ogham/exa#894]
I just installed exa on my mac, and when i use the command ```exa -l```, the **size** info misses, just a **-** there.
> The doc says ```-l``` includes ```-B```, so size info should be there.

My exa version is **v0.10.1**, and my os is **macOS Catalina 10.15.6**, hardware is **MacBook Pro (Retina, 13-inch, Early 2015)**.

**Comment by ariasuni** [comment]
> I just installed exa on my mac, and when i use the command exa -l, the size info misses, just a - there.

In every directory? It should only display `-` for directories in your case, and show the size for the files. Describing an issue without an output or screenshot demonstrating the problem doesn’t tell me much about what’s going on…

> The doc says `-l` includes `-B`, so size info should be there.

Where did you see that? Size is included by default when using `-l`, that is correct. But `-B` changes how the size is displayed («List file sizes in bytes, without any prefixes.» in the man), and should be used explicitly with `-l`.

**Comment by primeNumberAndMe** [comment]
Sorry, my fault, I haven't read the doc carefully.
I just compared the output of exa with ls -l, and ls shows the size of a directory, so I opened this issue.
Sorry

**Comment by ariasuni** [comment]
No worry, these sort of things happen, and this was sorted out quickly. :slightly_smiling_face:
