### ISSUE TITLE
[Packaging] Arch Linux PKGBUILD

### ISSUE THREAD

**Issue by K900** [ogham/exa#9]
I wrote an Arch Linux PKGBUILD for exa. Is that something you're interested in having somewhere in the source repository? I can upload it to the AUR when it's tested a bit more.

**Comment by ogham** [comment]
I have absolutely no idea! Is it a standard practice to have PKGBUILDs in the main repository?

**Comment by K900** [comment]
Some projects have their packaging related stuff in the main repository, some just rely on distro maintainers. It varies, really.

**Comment by ogham** [comment]
Ok then, I'll take it! I think an `etc` folder would be good for such things, as well as tab-completion files and other stuff.

**Comment by K900** [comment]
Cool. I'll send a pull request next time I'm on my Arch box. Maybe something like `dist/arch`? So you can also have `dist/debian` and `dist/rpm` and whatnot if anyone wants to contribute those.

**Comment by evaryont** [comment]
Another convention (though not the only one, of course) is to have a `contrib/` directory that collects all user contributions (but external to the main code base). Same idea as the `etc` folder, but a different name really.

PS: Thanks @K900 for the PKGBUILD! Works great on my Arch laptop. :smile:
