### ISSUE TITLE
Website link to bash completion needs to be updated

### ISSUE THREAD

**Issue by boomshadow** [ogham/exa#902]
Greetings! I'm a big fan of `exa`; I love this tool!

I noticed that the link to the bash completion files needs to be updated (on this page: https://the.exa.website/install/linux). 

Bash currently points to: https://raw.githubusercontent.com/ogham/exa/master/contrib/completions.bash

It needs to point to: https://raw.githubusercontent.com/ogham/exa/master/completions/bash/exa

**Comment by ariasuni** [comment]
That’s right, this problem is tracked in #757.

**Comment by ariasuni** [comment]
Also, glad you love exa! :slightly_smiling_face:
