### ISSUE TITLE
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err`

### ISSUE THREAD

**Issue by MostHated** [ogham/exa#904]
#### Double Edit: It looks like it is fixed after manually adding v0.10.x. I feel like I put a ticket in for something like this already in the past and had upgraded, perhaps when I upgraded to Pop_OS v21.04 it goofed something up and grabbed a lower version.

---
 
Hello, 
    I attempted to use the below command in a small (2mb) temp ramdisk drive that I mount on login which is used for script output to feed to Conky, but received an error that is also listed below.

#### Command: `alias la='exa -lhUma --git --color-scale'`

```sh
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "creation time is not available for the filesystem" }', src/fs/file.rs:346:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[1]    1731968 IOT instruction (core dumped)  exa -lhUma --git --color-scale
```

Thanks,
-MH

**Comment by ariasuni** [comment]
Yeah it’s been fixed for a while, and sadly version of packages such as exa in Ubuntu repositories (that Pop!_OS uses) are freezed. If you’re interested, here’s the pull request: https://github.com/ogham/exa/pull/616

By the way, it’s good practice to try to reproduce with the fewer possible flags, so it’s easier to identify the problem. Thanks for reporting anyway!
