### ISSUE TITLE
Remove icons/type indicator when redirecting output

### ISSUE THREAD

**Issue by sklages** [ogham/exa#905]
Nice to have these icons in  in interactive terminals. But when piping/redirecting `exa`  output, I don't need any icons or file types. So `exa` should fallback to plain `ls` behaviour. This is how `lsd` and `bat-cat` work AFAIK: when it detects an interactive terminal it shows decorations and falls back to plain `ls`/`cat` mode if it doesn't ..

**Comment by ariasuni** [comment]
This issue is tracked at #511 already, but yeah it’s an annoying problem that should be solved.

**Comment by ariasuni** [comment]
Ah oops I didn’t see you were talking also about the `--classify`/`-F` option, I’ll add that to the other bug report.

**Comment by sklages** [comment]
yes, any "visual helpers" should be removed in a pipe ..  I haven't seen #691 indeed .. 
`--classify/-F` is an issue with standard `ls` as well, decorations are not removed in a pipe .. that's why I never used `-F` with `ls` (aliased) since the beginning of time ;-)
