### ISSUE TITLE
Add shell icon to `.dash` files

### ISSUE THREAD

**Issue by izhakjakov** [ogham/exa#906]
Please add a shell icon to [dash](https://en.wikipedia.org/wiki/Almquist_shell?#Dash) files :)

![image](https://user-images.githubusercontent.com/18270061/124636706-d6f70a00-de56-11eb-9e0a-2fd99d4a6aaf.png)

**Comment by ariasuni** [comment]
Well, is this extension widely used? It seems to me that it’s either used for MPEG-Dash, or the export data format of Dashlane.

- https://fileinfo.com/extension/dash
- https://www.file-extension.org/extensions/dash
- https://file.org/extension/dash

**Comment by izhakjakov** [comment]
fair enough.  I'll close the issue
