### ISSUE TITLE
Color Last time Modified

### ISSUE THREAD

**Issue by horseinthesky** [ogham/exa#913]
Is there an option to have automatic different coloring for modified files/dirs as `lsd` does it?
![image](https://user-images.githubusercontent.com/19948672/125673141-ad56d16d-20c7-4466-b44b-fa057edf2b4f.png)

It really helps to fix expected/unexpected changes.

**Comment by ariasuni** [comment]
No there’s isn’t. Such feature has already been requested in #233.
