### ISSUE TITLE
Add option to list files with their absolute path.

### ISSUE THREAD

**Issue by amosbird** [ogham/exa#92]
It would be useful if `exa` can print absolute path of files so that `urxvt-matcher-launcher` can open these file correctly.

**Comment by ogham** [comment]
Good idea.

**Comment by ogham** [comment]
This is #88 as well, isn't it?

**Comment by ogham** [comment]
Since this issue was opened, terminal hyperlinks have become more popular, and I would rather exa go down that route than have it support another option (which outside of opening things, I think is relatively niche).

**Comment by fallalex** [comment]
I was looking for this too. After https://github.com/ogham/exa/commit/9b87ef1da2231acef985bb08f7bd4a557167b652 you can work around this by doing something like the following
```
exa $PWD/*
```

**Comment by aubreypwd** [comment]
> I was looking for this too. After [9b87ef1](https://github.com/ogham/exa/commit/9b87ef1da2231acef985bb08f7bd4a557167b652) you can work around this by doing something like the following
> 
> ```
> exa $PWD/*
> ```

This works for my case where instead of `.` I would rather have the full path shown:

```
exa $PWD -l -g --icons --tree --level=1 -a
```

And what I get is, e.g.:

![image](https://user-images.githubusercontent.com/1753298/157287063-de5530d0-c06f-48b3-b339-223594f5d52d.png)

👏

**Comment by zohnannor** [comment]
> `exa $PWD -l -g --icons --tree --level=1 -a`

One caveat though: if you'd `ls some-dir/`, it will print both `some-dir` and `$PWD`.

![image](https://user-images.githubusercontent.com/35764628/159121427-9b909484-b645-413b-885f-18384bbfca42.png)
