### ISSUE TITLE
support `+FORMAT` in option `--time-style=` and environment variable `TIME_STYLE`

### ISSUE THREAD

**Issue by toymil** [ogham/exa#923]
This is a quote from [`ls` manpage](https://manpages.debian.org/testing/coreutils/ls.1.en.html):
> The `TIME_STYLE` argument can be `full-iso`, `long-iso`, `iso`, `locale`, or `+FORMAT`. `FORMAT` is interpreted like in date(1). If `FORMAT` is `FORMAT1<newline>FORMAT2`, then `FORMAT1` applies to non-recent files and `FORMAT2` to recent files. `TIME_STYLE` prefixed with 'posix-' takes effect only outside the POSIX locale. Also the `TIME_STYLE` environment variable sets the default style to use.

For `ls`, `+FORMAT` can be used inline with option `--time-style=+<format>` or in the `TIME_STYLE` environment variable.  And the form `FORMAT1<newline>FORMAT2` is particularly useful for customization (examples below).

---

setup:
```
ls_time_style_short="+\
%Y-%m-%d %H %:::z
--%m-%d %H:%M %:::z\
"
ls_time_style_long="+\
%Y-%m-%d %H:%M:%S %:z
   --%m-%d %H:%M:%S %:z\
"
alias "ll"="ls -AFhl --time-style='${ls_time_style_short}'"
alias "lll"="ls -aFhl --time-style='${ls_time_style_long}'"
```

output:
```
$ ll
--08-04 01:51 -05 .gitconfig
--07-30 16:22 -05 .inputrc
2020-01-27 15 -05 .lesshst
2018-04-26 13 -05 .profile

$ lll
   --08-04 05:28:29 -05:00 ./
2018-04-26 13:57:02 -05:00 ../
   --08-04 01:51:31 -05:00 .gitconfig
   --07-30 16:22:42 -05:00 .inputrc
2020-01-27 15:29:17 -05:00 .lesshst
2018-04-26 13:57:02 -05:00 .profile
```

**Comment by ariasuni** [comment]
Note that this is annoying because we need support exactly the same syntax, and I don’t think we want that. However, we could offer something pretty similar, instead of the current situation where we try to interpret `TIME_STYLE` while clearly not supporting it entirely.

**Comment by MaartenStaa** [comment]
@ariasuni I was considering taking a crack at this, do you think it would be acceptable to depend on either the `time` or `chrono` crate to greatly simplify the formatting involved?

**Comment by ariasuni** [comment]
I’ll probably merge #867 soon, but I’m not sure I want to depend specifically on chrono. There’s like several possible approach:
- Supports same syntax as ls (translates between ls and chrono syntax)
- Supports chrono syntax without trying to support ls syntax
- Both (support legacy syntax with `TIME_STYLE` and chrono syntax directly via `EXA_TIME_STYLE`)

I think supporting ls syntax would need some solid unit tests and I’m not sure it’s worth pursuing… especially since it’ll probably not work exactly the same (e.g. we (almost) don’t support localization…).

**Comment by StayPirate** [comment]
I use `TIME_STYLE=+%d-%m-%Y %H:%M:%S %z` which is not handled by `exa`. Do you know if #867 will solve this? Any idea about when it can be merged?

**Comment by ariasuni** [comment]
I’m working on merging my work in [the active fork eza)[https://github.com/eza-community/eza), I haven’t looked at `TIME_STYLE` (yet?)

**Comment by StayPirate** [comment]
Can this issue be moved to `eza` or is it already fixed via https://github.com/eza-community/eza/pull/58?

**Comment by ariasuni** [comment]
I’m still monitoring issues on here, and closing them when they’re fixed in eza, but if you want to can open a new issue on eza’s side (with the link to this one for the history) and I could close this one.

**Comment by ariasuni** [comment]
Closing this issue since you opened an equivalent one on eza’s side (→ https://github.com/eza-community/eza/issues/371)
