### ISSUE TITLE
Add compression icon to .tXX files

### ISSUE THREAD

**Issue by izhakjakov** [ogham/exa#930]
- [ ] recognize `tgz` files as backup file similar to `tar.gz` files.
	- https://fileinfo.com/extension/tgz
	- https://www.file-extension.org/extensions/tgz
	- https://file.org/extension/tgz
	
- [ ] recognize `txz` files as backup file similar to `tar.xz` files.
	
	- https://fileinfo.com/extension/txz
	- https://www.file-extension.org/extensions/txz
	- https://file.org/extension/txz
	
- [ ] recognize `tlz` files as backup file similar to `tar.lz` files.
	- https://fileinfo.com/extension/tlz
	- https://www.file-extension.org/extensions/tlz
	- https://file.org/extension/tlz

**Comment by izhakjakov** [comment]
Or anything else if I missed.
I noticed that `tbz` and `tbz2` are already recognized

**Comment by jim4067** [comment]
working on this 👍🏾

**Comment by izhakjakov** [comment]
thanks :)

**Comment by izhakjakov** [comment]
Looks like it is no longer an issue
Thanks you jim4067 and ariasuni
