### ISSUE TITLE
Should installation via package installer give version `v0.9.0`?

### ISSUE THREAD

**Issue by Delta456** [ogham/exa#931]
Should installation via package manager have the version `v0.9.0` as [v0.10.1](https://github.com/ogham/exa/releases
/tag/v0.10.1) seems to be the most recent and stable release.

![image](https://user-images.githubusercontent.com/28479139/129446534-20c94028-d0d0-470d-88ff-a9dc60a3f202.png)

**Comment by ariasuni** [comment]
Yep, that’s because Debian hasn’t updated exa, so Ubuntu hasn’t updated exa.

See my comment on another issue [with the different ways to install a more up-to-date exa](https://github.com/ogham/exa/issues/912#issuecomment-879858039).
