### ISSUE TITLE
[feature] respect LANG

### ISSUE THREAD

**Issue by Freed-Wu** [ogham/exa#934]
![Screenshot from 2021-08-19 02-15-50](https://user-images.githubusercontent.com/32936898/129951216-dfe18432-6ecc-46c1-9728-335fe71318ee.png)

Why not let exa respect `$LANG`?

Thanks!

**Comment by ariasuni** [comment]
Because we need to program it, it’s very hard and time-consuming to do that from scratch, and there’s no collation (locale-aware sorting) library in Rust that does that yet.

There’s already an open issue about this lack: #410

Note that you can use `--sort=Name` to sort with capitals first.
