### ISSUE TITLE
Allow suppression of owner from long output

### ISSUE THREAD

**Issue by nothingmuch** [ogham/exa#94]
For personal use on my laptop, the username column is essentially a very wide vertical divider ;-)

For bonus points, being able to control the column set and order by specifying an arbitrary list of fields would handle similar requests

**Comment by ogham** [comment]
I feel like at some point I'll need to do the second part anyway... there'll always be requests to change which columns are shown.

**Comment by laughedelic** [comment]
Related: #182 and #161

**Comment by ogham** [comment]
Thanks to #577 you will be able to use `--no-user`.
