### ISSUE TITLE
Publish website repo

### ISSUE THREAD

**Issue by jtagcat** [ogham/exa#942]
Can't make PRs… Disable issues on the website's repo: encourages PRs for small changes, and prevents misfiling of actual exa things.

Changes I'd like to see:
 - Without using a package manager section: Older Debian/Ubuntu versions, workaround:
   ```sh
   wget http://archive.ubuntu.com/ubuntu/pool/universe/r/rust-exa/exa_0.9.0-4_amd64.deb
   apt install ./exa_0.9.0-4_amd64.deb
   rm exa_0.9.0-4_amd64.deb
   ```

**Comment by Absobel** [comment]
I don't understand, why can't you make a PR for this ?

**Comment by ariasuni** [comment]
exa is unmaintained, use [the active fork eza](https://github.com/eza-community/eza) instead (see https://github.com/ogham/exa/issues/1243).

Also, @ogham, the website owner, has been inactive a for a serious while, so I’m closing this issue.
