### ISSUE TITLE
Display extended attributes and symbolic link destinations on Grid too

### ISSUE THREAD

**Issue by 0xTadash1** [ogham/exa#943]
Thanks for the great tool!
One of the features I like is the `-lG` display. 

However, currently this mode seems to leave out some information compared to a simple `-l` display. 
It would be very nice to be able to show the destination of links and extended attributes too.

**Comment by ondrej-ivanko** [comment]
I second that. It would be nice if it can be displayed. It always bothered me that it's not working even if using `exa- al --grid` on single file. I guess the layout render which displays results and sort the results into grid does not (or cannot take) into account the extended file attributes.

**Comment by ariasuni** [comment]
Yeah you’re right, let’s close this in favor of the other two issues.
