### ISSUE TITLE
Why no default for -t?

### ISSUE THREAD

**Issue by ahcm** [ogham/exa#944]
We all have our common flags that we are used to, one of mine is -lrt and it gives an error message in exa.
I just wonder, why not default was chosen.
$ exa -lrt
Flag -t needs a value (choices: modified, changed, accessed, created)
To sort newest files last, try "--sort newest", or just "-snew"

Also if the choices are "modified, changed, accessed, created" what would "newest" mean?
To me -snew just looks wrong as it should mean -s -n -e -w and "--sort modified" would be very long.

E.g. ls has -c for sorting or displaying "changed".

**Comment by ariasuni** [comment]
Thanks for reporting. There’s already #519 open for this, please see/add your comment there, and I’m gonna close this issue.
