### ISSUE TITLE
Feature request: Add new command line option `--dirs-first`

### ISSUE THREAD

**Issue by bessarabov** [ogham/exa#946]
I would love to see the new option in `exa` — `--dirs-first`. With this option `exa` should show all the directories before files.

Here is a screenshot of `exa`  and the screenshot of `tree` command that is showing dirs first:

![Screen Shot 2021-09-05 at 19 36 35](https://user-images.githubusercontent.com/47263/132134510-93b13b3c-9a5f-4fc6-816a-228b49690945.png)

In `tree` the option is called `--dirsfirst`, but for `exa` I think that the name `--dirs-first` should be used, that will match the existing option names like `--only-dirs`, `--ignore-glob`, `--git-ignore` and others.

**Comment by CamJN** [comment]
You might want `--group-directories-first`?

**Comment by bessarabov** [comment]
Yes, thank you. Now I'm trying to find out why I have missed this option in README.md

I think that I understand why I didn't find it. I've found `--list-dirs` and `--only-dirs` and then I was searching for `dirs` word in REAME.md

It's a bit confusing that in some options the word `dirs` is used, and in this option it is `directories`.

Thank you!

**Comment by stevengreg2020** [comment]
hello Ivan im Steven how are you today"

well i really want to be your friend i want to always communicate with you directly maybe via whatsap or any other 
fast app for communication i want to learn from you please send me your whatsap number or any other convenient chatting app 
please 

thank you
