### ISSUE TITLE
exa doesnt display --icons inside vs code integrated terminal

### ISSUE THREAD

**Issue by alexzanderr** [ogham/exa#949]
- The version of exa being used (`exa --version`)
```shell
> exa --version
exa - list files on the command-line
v0.10.1 [+git]
```

- The command-line arguments you are using
```bash
alias ls="exa --icons"
alias la="exa --all --icons"
```
this also doesnt work for `--tree`
![image](https://user-images.githubusercontent.com/54772464/132551303-3cbd55e9-d795-413d-8cf5-ff500e7b5855.png)

- Your operating system and hardware platform
```
                  .o+`                   ------------------
                 `ooo/                   OS: Manjaro Linux x86_64
                `+oooo:                  Host: GL553VD 1.0
               `+oooooo:                 Kernel: 5.10.60-1-MANJARO
               -+oooooo+:                Uptime: 6 hours, 41 mins
             `/:-:++oooo+:               Packages: 1465 (pacman)
            `/++++/+++++++:              Shell: zsh 5.8
           `/++++++++++++++:             Resolution: 1920x1080
          `/+++ooooooooooooo/`           DE: Xfce 4.16
         ./ooosssso++osssssso+`          WM: Xfwm4
        .oossssso-````/ossssss+`         WM Theme: borderless-windows
       -osssssso.      :ssssssso.        Theme: Matcha-dark-aliz [GTK2], Adwait
      :osssssss/        osssso+++.       Icons: Papirus-Dark [GTK2], Adwaita [G
     /ossssssss/        +ssssooo/-       Terminal: tmux
   `/ossssso+/:-        -:/+osssso+-     CPU: Intel i7-7700HQ (8) @ 3.800GHz
  `+sso+:-`                 `.-/+oso:    GPU: Intel HD Graphics 630
 `++:.                           `-/+/   GPU: NVIDIA GeForce GTX 1050 Mobile
 .`                                 `/   Memory: 11769MiB / 15891MiB
                                         GPU Driver: ASUSTeK Computer Inc. Devi
                                         CPU Usage: 16%
                                         Disk (/): 40G / 213G (20%)
                                         Battery0: 100% [Full]
```

---
hello. i love this program. changed my life.

but when trying to `exa --icons` in vscode's `integrated terminal` i get this:
![image](https://user-images.githubusercontent.com/54772464/132550480-9c482130-1d74-42c9-b8ed-f6e2c345e3b3.png)
as you can see:
- i have nerd fonts installed successfully ( currently is meslo LG S ) 
- i selected the nerd font for vs code settings
- when trying to print `unicode` in integrated terminal, its `works` like a charm

as you can see, in `alacritty` printing icons it works:
![image](https://user-images.githubusercontent.com/54772464/132551817-2e5ff490-3a53-4a6f-b963-d927def36f61.png)

first i thought it was vscode's problem with rendering unicode, i researched about it, the solution was to use a `nerd font`. i've used a nerd font and it works... just for priting unicode.

but when `ls` with exa i dont get the beautiful icons.

then i thought maybe its exa's problem with printing icons, then i've raised this issue.

maybe someone can help me solve this problem.

**Comment by alexzanderr** [comment]
okey so, after a quick look in the source code i found this:

in `exa/src/output/icons.rs`
```rs
    else if let Some(icon) = extensions.icon_file(file) { icon }
    else if let Some(ext) = file.ext.as_ref() {
        match ext.as_str() {
            "ai"            => '\u{e7b4}', // 
            "android"       => '\u{e70e}', // 
            "apk"           => '\u{e70e}', // 
            "apple"         => '\u{f179}', // 
            "avi"           => '\u{f03d}', // 
            "avro"          => '\u{e60b}', // 
            "awk"           => '\u{f489}', // 
            "bash"          => '\u{f489}', // 
            "bash_history"  => '\u{f489}', // 
            "bash_profile"  => '\u{f489}', // 
...
...
```
and so on. i guess from here icons are imported to use when printing.

i tested printing a char in vs code integrated terminal
- char: `\u{e7b4}`
```
> echo "\u{e7b4}" 
{e7b4}
```
after removing the curly braces:
```
> echo "\ue7b4"  

```
on my screen is the same `empty box`; aparently not even github can render this.

on my terminal (`alacritty`):
```
> echo "\ue7b4"

```
okey so, on my terminal works. `adobe ilustrator icon` showed, not even github can render this.

conclusion:
on every other terminal printing icons works like a charm ( the icons provided from that rust file ).
but when priting the icons from the rust file inside vs code terminal we got a problem with rendering. so there is a problem with vs code rendering that type of unicode.

any ideas, guys?

**Comment by alexzanderr** [comment]
aparently, all electron based apps are displaying icons with problems

**Comment by ariasuni** [comment]
Thanks for investigating!
