### ISSUE TITLE
Exa Dotfile for Customization?

### ISSUE THREAD

**Issue by AviFS** [ogham/exa#953]
Doing a bit of a deep-dive into the documentation in a fanboyish moment and noticed this:

> **Warning!**
>
> The behaviour of EXA_COLORS may change between different versions of exa, because its use cases are still being worked out: there *must* be an easier way to customise exa than by stuffing data into an environment variable.

I must be missing something but what about a dotfile? Looking for a name like .exarc in the home directory by def, and then having the optional environment variable to set an alternate path for .exarc.

Just have to ask! Thanks for a great project; my `ls` has been aliased to `exa` for longer than I can remember!

**Comment by ProfessorConfundus** [comment]
Please add this feature! Just an `.exa.config` or `.exarc` in the user home dir would be such a good addition!

**Comment by kidonng** [comment]
See #511

**Comment by ariasuni** [comment]
Closing since it’s already reported and discussed in #511.
