### ISSUE TITLE
upgraded libgit2 (1:1.1.1-1 -> 1:1.2.0-1) breaks exa execution (this is an unfixed upstream git2-rs issue)

### ISSUE THREAD

**Issue by matu3ba** [ogham/exa#962]
If exa does something unexpected, or its output looks wrong, or it displays an error on the screen, or if it outright crashes, then please include the following information in your report:

- The version of exa being used (`exa --version`)

This command does not work, because unconditionally loads shared library `libgit2.so.1.1`. I am using the latest crates.io version.

- The command-line arguments you are using

`exa` in any folder

- Your operating system and hardware platform

Linux 5.14, x86_64 Intel Skylake

If it’s a crash, please include the full text of the crash that gets printed to the screen. If you’re seeing unexpected behaviour, a screenshot of the issue will help a lot.

---

```txt
$ exa --version
exa: error while loading shared libraries: libgit2.so.1.1: cannot open shared object file: No such file or directory
```

This bears some questions:
1. Why are the features `exa` provides with `libgit` not documented in the README?
2. Would it be possible to gracefully not load libgit2 (ie weak linkage) or does the Rust type system not allow this?
3. https://github.com/rust-lang/git2-rs/issues/746 exists, so would it be possible to have CI coverage for libgit2 and combine them with libgit2 and git2-rs release information? 
The release is [on github](https://github.com/libgit2/libgit2/releases) and 12 days ago (before it was packaged), but the CI could also take the latest release every week and test it.
4. Why is this not fixed in git2-rs, even though cargo generate had [the same very issue](https://github.com/rust-lang/git2-rs/issues/746)?

**Comment by ariasuni** [comment]
1. They are, search for «Git» in the README.
2. I think exa is already built dynamically against your system libgit2 if it’s present, that why you have problem. It’s possible to force the embedding of libgit2 by using its `vendored-libgit2` feature.
3. The issue you link doesn’t seem to be related. I thought about improving the CI, but it takes time (which I don’t have a lot of)
4. As you said it’s an upstream issue, so I don’t know, it’s not my package.

Now, does rebuilding exa fixes your problem?

**Comment by matu3ba** [comment]
1. As I read this includes only "--git: list each file’s Git status, if tracked or ignored"
2. For now I fixed my issue with disabling the git features, which I dont use (I have a pile of git aliases)
3. ok, no problem. the workaround was easy, just annoying that it breaks.
4. ok, just wanted to ask if you know a fix.

Yes. Thanks for the kind reply. Should I close this?

**Comment by ariasuni** [comment]
Another flag that uses libgit2 is `--git-ignore`. It’s annoying that it breaks but it’s pretty standard: distributions are supposed to update packages when libraries have breaking changes like this, and if you compiled it yourself your on your own. We could had an exa feature to force the embedding of the libgit2, at least it would make sense for the musl build, I should check out how it works someday but it’s not really a priority.
