### ISSUE TITLE
exa: error while loading shared libraries: libgit2.so.1.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Xyhlon** [ogham/exa#985]
If exa does something unexpected, or its output looks wrong, or it displays an error on the screen, or if it outright crashes, then please include the following information in your report:

- The version of exa being used (`exa --version`)
- The command-line arguments you are using
- Your operating system and hardware platform

If it’s a crash, please include the full text of the crash that gets printed to the screen. If you’re seeing unexpected behaviour, a screenshot of the issue will help a lot.

---
No version is printable with exa --version however the version is 10.1-4 according to pacman
var/cache/pacman/pkg/exa-0.10.1-4-x86_64.pkg.tar.zst

command line arguements
exa -al --color=always --group-directories-first

Hardware Software
                 `ooo/                   OS: Arch Linux x86_64
                `+oooo:                  Host: Surface Book 3 124I:00037T:000M:0200000D:0B:05F:1C:05P:48S:01E:0Y:1K:0U:00R:2
               `+oooooo:                 Kernel: 5.15.5-arch1-1
               -+oooooo+:                Uptime: 34 mins
             `/:-:++oooo+:               Packages: 1159 (pacman)
            `/++++/+++++++:              Shell: zsh 5.8
           `/++++++++++++++:             Resolution: 3240x2160
          `/+++ooooooooooooo/`           DE: GNOME 41.1
         ./ooosssso++osssssso+`          WM: Mutter
        .oossssso-````/ossssss+`         WM Theme: Adwaita
       -osssssso.      :ssssssso.        Theme: Adwaita [GTK2/3]
      :osssssss/        osssso+++.       Icons: Adwaita [GTK2/3]
     /ossssssss/        +ssssooo/-       Terminal: alacritty
   `/ossssso+/:-        -:/+osssso+-     CPU: Intel i7-1065G7 (8) @ 3.900GHz
  `+sso+:-`                 `.-/+oso:    GPU: NVIDIA Quadro RTX 3000 Mobile / Max-Q
 `++:.                           `-/+/   GPU: Intel Iris Plus Graphics G7
 .`                                 `/   Memory: 2732MiB / 31694MiB

The error message
exa: error while loading shared libraries: libgit2.so.1.2: cannot open shared object file: No such file or directory

I tried to downgrade the libgit2 version to 1.2 because it says it needed it and I knew I had libgit2-1:1.3.0-1

However my package downgrader warned me that exa needed a different version (the version I had installed ) and if I would downgrade it would break its dependency

:: installing libgit2 (1:1.2.0-1) breaks dependency 'libgit2.so=1.3-64' required by exa

So what is going on how can I fix this.

**Comment by daviessm** [comment]
This looks like a packaging error, you should file a bug with Arch.

**Comment by Xyhlon** [comment]
First of all thanks for the reply. Sorry for  asking, but what should I tell them exactly? And is this the correct site https://bugs.archlinux.org/. Never filed a bug with Arch

**Comment by daviessm** [comment]
I don't use Arch but I would do pretty much the same as you have here: show the command that failed and the output from the package manager which complains about downgrading the library.

**Comment by Xyhlon** [comment]
According to https://bugs.archlinux.org/task/72872. Everything built fine with libgit2 1.3.0-1 and exa 10.1-4 so why would exa say it would need libgit2 1.2?

**Comment by Xyhlon** [comment]
I had two conflicting version of exa one installed with cargo the other installed with pacman the cargo seems to out of date 
https://bbs.archlinux.org/viewtopic.php?pid=2005988#p2005988
