### ISSUE TITLE
cd insfollow

### ISSUE THREAD

**Issue by Abo00k** [ogham/exa#986]
If exa does something unexpected, or its output looks wrong, or it displays an error on the screen, or if it outright crashes, then please include the following information in your report:

- The version of exa being used (`exa --version`)
- The command-line arguments you are using
- Your operating system and hardware platform

If it’s a crash, please include the full text of the crash that gets printed to the screen. If you’re seeing unexpected behaviour, a screenshot of the issue will help a lot.

---

**Comment by ariasuni** [comment]
Hi, looks like a mistake, so I’m closing this issue. Please create another issue if you have a problem with exa.
