### ISSUE TITLE
Gentoo ebuild

### ISSUE THREAD

**Issue by ehegnes** [ogham/exa#99]
I will be writing, submitting, and maintaining a Gentoo ebuild for `exa`. I am simply opening this issue for record-keeping purposes. :)

**EDIT:** After some research, it looks as though this package should be in [rust overlay](https://github.com/gentoo/gentoo-rust) rather than in the main Portage tree. This may be helpful to know for anybody trying to find the package.

**Comment by ogham** [comment]
If you can make a build, I can add installation instructions to the exa home page for Gentoo.

**Comment by sanxiyn** [comment]
Update: exa is now packaged in Gentoo's main portage tree: https://packages.gentoo.org/packages/sys-apps/exa

**Comment by raspher** [comment]
Exa is removed from gentoo main portage tree. Someone know why?

//Edit
Oh, thats why - https://github.com/ogham/exa/issues/1243
