### ISSUE TITLE
[Feature Request] Add clickable hyperlink as `ls` do

### ISSUE THREAD

**Issue by CoelacanthusHex** [ogham/exa#992]
`ls` in the coreutils has added a function to generate clickable hyperlink (enable by `--hyperlink`),
I think we can add the same function.
This is commit added by`ls`, https://github.com/coreutils/coreutils/commit/799bac0d06cfabe9491498727308df8d1aca6d98
This is a summary of hyperlink escape sequence, https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda

**Comment by chapmanjacobd** [comment]
This is a duplicate of https://github.com/ogham/exa/issues/396 :-)
