### ISSUE TITLE
Option to show permissions in Octal

### ISSUE THREAD

**Issue by alohawolf** [ogham/exa#996]
Even though I've been using unix systems for 20 years, I can never remember how to convert a permissions mask to octal in my head, so I have to use a little calculator to convert it, a killer feature for exa would be to show permissions in octal as well as the standard permissions mask style.

**Comment by ariasuni** [comment]
I’m not sure if that’s very useful to have both displayed at the same time? It would be the first time that exa displays the same information twice in different formats…

**Comment by alohawolf** [comment]
Even if you only offer a flag to display it in octal, this would still be
helpful, I did read the man page, and saw no way to do that currently.

https://news.ycombinator.com/item?id=29609388#29617182

There were others who felt it might have some use, anyhow. Offering a
switch for just octal, or ideally, allowing me to list both methods is
ideal.

it's in much the same way you might want to see username and uid /
groupname and gid

**Comment by ariasuni** [comment]
> Even if you only offer a flag to display it in octal, this would still be helpful, I did read the man page, and saw no way to do that currently.

It’s missing from the man page in the current released version, but there’s `--octal-permissions`.

> it's in much the same way you might want to see username and uid / groupname and gid

I guess it can be useful, but it would complicate exa quite a bit to be able to handle those kind of cases, so I want to be sure it would useful to a significant portion of the people using exa. Right now, I think that’s the first time I’ve been asked for «duplicated info in different formats», so I prefer to see if there’s interest before investing my time and energy on it.

**Comment by virchau13** [comment]
I would also like this functionality (only displaying octal permissions.)

> I guess it can be useful, but it would complicate exa quite a bit to be able to handle those kind of cases

May I offer a suggestion? I'm not familar with `exa`'s code base, but by a cursory glance into `src/output/table.rs`, it seems the easiest way to do this would be to split the `Column::Permission` into two - `Column::ReadablePermissions` and `Column::OctalPermissions`, and provide flags for toggling both.

This way, no more extra complexity is added, and users have an option on whether they want to display both (the current `--octal-permissions`), one or the other, or neither.

Also, in my opinion, it would be nice to be able to remove the leading zeroes.

**Comment by virchau13** [comment]
> Column::ReadablePermissions and Column::OctalPermissions, and provide flags for toggling both.

I just realised this is actually the current behaviour... Sorry about that. :)

**Comment by ariasuni** [comment]
Yeah, the current behavior is:
– By default, show permissions in rwx style
– With `--no-permissions`, don’t show permissions
- With `--octal-permissions`, show permissions in octal

But yeah I’m gonna close that.
