### ISSUE TITLE
Exa asks for strange permissions when listing files on macOS

### ISSUE THREAD

**Issue by noahtallen** [ogham/exa#997]
I'm trying `exa` on macOS. When I ran `exa --tree` from my home directory, macOS asked if I wanted to give my terminal emulator (iTerm 2) several permissions:

- Contacts
- Calendar
- Photos
- Reminders

I imagine macOS might make this situation unavoidable, but I did find it strange. Normally, CLI tools don't need permission to access these things, and it might not be obvious to most that macOS probably just automatically prompts when you try to access files like these. I wonder if there is a way to avoid asking for permissions if not needed, or a better way to communicate what's happening. I think the current situation might make some wary towards `exa`.

**Comment by ariasuni** [comment]
Hum, wtf? I don’t think exa is asking for these permissions. Where did you get exa from?

**Comment by 404galore** [comment]
This isn't exa's fault. It happens because macos detects that the terminal app is trying to access your photos folder.

**Comment by ariasuni** [comment]
Ah well I didn’t read carefully the first comment. Then I guess we can’t do nothing about it? Except if there’s a simple and very fast way to detect that iTerm 2 or whatever terminal emulator don’t have the permissions to access the files before it asks for the permissions, which I doubt. But I suppose most CLI tools on macOS don’t try to do such stuff and just let the terminal and the OS handle permission on their own.

**Comment by noahtallen** [comment]
Yeah, that's a good point. I'll close this then!
