### ISSUE TITLE
Confused by file size output

### ISSUE THREAD

**Issue by mrusme** [ogham/exa#998]
I'm a little confused by the output of file sizes, maybe anyone here can clarify on whether this is a bug or I'm overlooking something:

```sh
 ▲  /bin/ls -lab ./enwiki-latest-pages-articles.*
-rw-r--r-- 1 mrus mrus 32415795972 Dec 19 13:09 ./enwiki-latest-pages-articles.json
-rw-r--r-- 1 mrus mrus 86591331146 Dec  2 01:53 ./enwiki-latest-pages-articles.xml
 ▲  exa -laB ./enwiki-latest-pages-articles.*
.rw-r--r-- 32,415,795,972 mrus 19 Dec 13:09 ./enwiki-latest-pages-articles.json
.rw-r--r-- 86,591,331,146 mrus  2 Dec 01:53 ./enwiki-latest-pages-articles.xml
 ▲  /bin/ls -lah ./enwiki-latest-pages-articles.*
-rw-r--r-- 1 mrus mrus 31G Dec 19 13:09 ./enwiki-latest-pages-articles.json
-rw-r--r-- 1 mrus mrus 81G Dec  2 01:53 ./enwiki-latest-pages-articles.xml
 ▲  exa -lah ./enwiki-latest-pages-articles.*
Permissions Size User Date Modified Name
.rw-r--r--   32G mrus 19 Dec 13:09  ./enwiki-latest-pages-articles.json
.rw-r--r--   87G mrus  2 Dec 01:53  ./enwiki-latest-pages-articles.xml
```

On a byte level everything seems fine, however, with the *human readable* output the sizes differ significantly.

**Comment by Zitrax** [comment]
I think `ls` uses powers of 1024 by default, while `exa` uses 1000 (i.e. GiB vs GB), but quite confusing when they both just print `G`.

In `ls` you can use 1000 by passing `--si` while in `exa` you can get 1024 by passing `--binary`.

**Comment by mrusme** [comment]
@Zitrax thanks, it's getting closer:

```sh
 ▲  /usr/bin/exa -l --binary enwiki-latest-pages-articles.*
.rw-r--r-- 30Gi mrus 19 Dec 13:09 enwiki-latest-pages-articles.json
.rw-r--r-- 81Gi mrus  2 Dec 01:53 enwiki-latest-pages-articles.xml
```

Still a bit off for the json file though.

**Comment by ariasuni** [comment]
I think it’s because the size rounding logic of exa is different than the one of ls: https://github.com/ogham/exa/issues/838

So I guess I can close this issue in favor of the other one?
